### ISSUE TITLE
Incorrect description for 0 0 0 ? * MON-FRI *

### ISSUE THREAD

**Issue by mallim** [jmrozanec/cron-utils#105]
Version: 4.1.1

Test class: com.cronutils.parser.CronParserQuartzIntegrationTest 

```
@Test
    public void testDoWRangeStringMapping(){
        parser.parse("0 0 0 ? * MON-FRI *");
    }
```

will return 00:00 every day between Tuesday and Saturday for cron description

**Comment by jmrozanec** [comment]
@mallim thank you for reporting this!

**Comment by dsavickas** [comment]
I noticed that in
[https://github.com/jmrozanec/cron-utils/blob/master/src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java#L177](url)
`CronDefinitionBuilder.quartz()` uses `withMondayDoWValue(2)`

**Comment by jmrozanec** [comment]
@dsavickas thanks for pointing that out!

**Comment by pangyikhei** [comment]
In 6.0.2 the descriptor for this expression returns:
`at 00:00 every day between Monday and Friday`

**Comment by pangyikhei** [comment]
@jmrozanec I think this was fixed at some point.

This test passes in com.cronutils.utils.descriptor.CronDescriptorQuartzIntegrationTest.

```
    @Test
    public void testDoWRange() {
        CronDescriptor descriptor = CronDescriptor.instance();
        String description = descriptor.describe(parser.parse("0 0 0 ? * MON-FRI *"));
        assertEquals("at 00:00 every day between Monday and Friday", description);
    }
```

**Comment by jmrozanec** [comment]
@pangyikhei great! Will merge as soon as you send the PR! Thanks!

**Comment by jmrozanec** [comment]
@mallim @dsavickas Solved! Kudos to @pangyikhei!
