### ISSUE TITLE
All code should use the same indentation settings

### ISSUE THREAD

**Issue by espiegel** [jmrozanec/cron-utils#111]
For example here: https://github.com/jmrozanec/cron-utils/blob/master/src/main/java/com/cronutils/model/time/ExecutionTime.java#L56

Some of the code is indented with tabs and some is indented with 4 spaces. Not sure if this is something that I introduced in my pull request but I say we indent the whole project with 4 spaces.

**Comment by jmrozanec** [comment]
@espiegel perhaps you can work with @albuhuba to ensure we get a Mavenized code style? That way, anyone can run a goal and get a regular format.

**Comment by jmrozanec** [comment]
- [Formatter plugin](http://code.revelc.net/formatter-maven-plugin/formatter-maven-plugin/usage.html)
- [turn off break line](http://stackoverflow.com/questions/3242360/how-to-turn-off-break-line-in-eclipse)
- [provide parameters to ensure line ending is Unix style](http://code.revelc.net/formatter-maven-plugin/formatter-maven-plugin/examples.html#System_Independent_Line_Endings)

**Comment by jmrozanec** [comment]
Desired properties:
- normalize indentation.
- do not affect break lines, since user puts more intelligence into how to split code that a formatter can.
- enforce UTF-8 encoding.
- enforce Unix style line endings.
- run formatter previous to compilation process.

**Comment by jmrozanec** [comment]
@espiegel @albuhuba I am closing this issue since seems there are not persons interested on it and is not a project bug. You are welcome to work on it at any moment. Thanks!
