### ISSUE TITLE
Dependency cleanup

### ISSUE THREAD

**Issue by amanteaux** [jmrozanec/cron-utils#113]
Currently cron-utils depends on:

- slf4j,
- common-lang,
- htime -> guava.

htime is only used to bring the guava dependency.
common-lang is only used to validate that arguments are not null.
Guava is only used to create ArrayList and HashSet.

Actually my use case is that I want to use cron-utils to build a lightweight scheduler with a minimal footprint. So since I will depend on cron-utils, I would also like to minimize cron-utils footprint.

The job of removing these dependencies (or at least to put them in the test scope) is easy. But I want to validate the idea before doing anything.
If that is ok, I can do the changes in cron-utils.

**Comment by jmrozanec** [comment]
@amanteaux I am ok with it. Go ahead!

**Comment by amanteaux** [comment]
Great, thank you!
