### ISSUE TITLE
Describe day of week is incorrect

### ISSUE THREAD

**Issue by ElazarNeeman** [jmrozanec/cron-utils#115]
CronDescriptor descriptor = CronDescriptor.instance(locale);
CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(QUARTZ);
CronParser parser = new CronParser(cronDefinition);
Cron quartzCron = parser.parse("0 0 8 ? * SUN *");
descriptor.describe(quartzCron); //returns "at 08:00 at Monday day" instead of "at 08:00 at Sunday"

Same for all days of week lag of 1.

**Comment by jmrozanec** [comment]
@ElazarNeeman thank you for reporting the issue. You are welcome to contribute a test for it, and a fix is always welcome :)
