### ISSUE TITLE
Last Day of month Skipped on Quartz Expression: 0 * * ? * *

### ISSUE THREAD

**Issue by DanoOM** [jmrozanec/cron-utils#117]
nextExecution(..) will skip the last day of month incorrectly with the cron expression: 0 * * ? * *

Pull Request coming with test repro coming shortly.

notes:
This appears to have 'broken' with 4.0+ (I know it worked in past, but not sure which version).

**Comment by jmrozanec** [comment]
@DanoOM Thank you for reporting and contributing the fixes! They are now merged into master.
