### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by DanoOM** [jmrozanec/cron-utils#122]
We were hit again by issue #117 as its the last of the month...

Any chance we will get new release soon with the fix?

**Comment by jmrozanec** [comment]
@DanoOM sure. We can release this weekend. Will keep you posted. Thank you for reminding us!

**Comment by DanoOM** [comment]
Any update on this?

**Comment by jmrozanec** [comment]
@DanoOM not released yet. Will try to do so asap - most probably over weekend.

**Comment by jmrozanec** [comment]
@DanoOM new release 5.0.1 is available now. Thank you for contributing to cron-utils!
