### ISSUE TITLE
every expression is not working specifically start minute

### ISSUE THREAD

**Issue by hubsn** [jmrozanec/cron-utils#124]
For example, I used expression `0 3/27 10-14 * * ? *` and base time was `2016-01-01 10:00:00`.
And next execution was `2016-01-01 10:27:00`, but I expected `2016-01-01 10:03:00`.
Please check this out. cron-utils version is 4.1.1. Thanks in advance.

**Comment by jmrozanec** [comment]
@hubsn thank you for reporting this!

**Comment by jmrozanec** [comment]
@hubsn Fixed! We expect to have a new release soon with this fix.

**Comment by hubsn** [comment]
I really appreciate that your cooperation. Thanks.

2016-11-18 2:11 GMT+09:00 jmrozanec <notifications@github.com>:

**Comment by jmrozanec** [comment]
@hubsn The fix was released with version 5.0.5
