### ISSUE TITLE
Incorrect range validation of "and" expression values

### ISSUE THREAD

**Issue by keyade** [jmrozanec/cron-utils#128]
Hi,

It seems to me there is a problem with the validation of "and" expressions (ie: the ones with ","). The range validation of each value of the expression is not enforced at all. So unix crontab like these ones are said to be valid when they are not as range enforcing is activated :

`* * 10,20,30,40 * *  => 40 > 31`
`* * * 1,3,6,9,12,13 * => 13 > 12`
`* * * * 0,3,7,8 => 8 > 7`

After looking at the code, it looks like the problem comes from the fact that the validation visitor doesn't visit each of the sub expression of the and expression. So changing 

```java
	@Override
	public And visit(And and) {
		return and;
	}
```

To 

```java
    @Override
    public And visit(And and) {
        for(FieldExpression expression: and.getExpressions()) {
        	visit(expression);
        }
    	return and;
    }
```
in com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor should do the trick.

I applied this change to 4.1.1 tag and master branch locally without breaking any unit tests. Can create pull request with additional unit tests if you want to :)

Best regards,

K

**Comment by jmrozanec** [comment]
@keyade you are most welcome to send a pull request with the fixes and unit tests. Thank you for reporting and contributing!

**Comment by jmrozanec** [comment]
@keyade thank you for contributing a fix and tests with #131 
If you agree, I will now close the issue. Thanks!

**Comment by keyade** [comment]
@jmrozanec I also did the fix for v4.1.1 (my project is sadly running on java 7). could you create a 4.1.1 branch so that I can submit the fix also for the old version ?

**Comment by jmrozanec** [comment]
@keyade yes, we can do that. I created the branch 'b4.1.1' After the PR, we can release a new 4.x.y version by Friday/Saturday. Thanks again!

**Comment by keyade** [comment]
sweet :) I'll send the pull request asap :)

**Comment by jmrozanec** [comment]
Just merged #132 Thanks!

**Comment by jmrozanec** [comment]
@keyade version 4.1.2 was released with this fix! Thank you for helping us improve cron-utils!
A new branch will remain for 4.x.y updates: 4.x.y

**Comment by keyade** [comment]
Sweet ! Thanks a lot !
