### ISSUE TITLE
QUARTZ cron definition: 31 not supported on the day-of-month field

### ISSUE THREAD

**Issue by Jingyi244** [jmrozanec/cron-utils#133]
quartz supports blow cron expression:
0 0 0 31 * ?
while CronDefinition with CronType.QUARTZ raise exception.

**Comment by jmrozanec** [comment]
@Jingyi244 Thank you for reporting this. Could you create a test case for it and send a pull request? Thanks!

**Comment by jmrozanec** [comment]
@Jingyi244 can you please validate if the issue was fixed? We just pushed a test with it, and seems to parse the expression without issues. Thanks!

**Comment by jmrozanec** [comment]
@Jingyi244 The fix was released with version 5.0.5
