### ISSUE TITLE
No day number translation when mapping Unix  Cron to Quartz Cron

### ISSUE THREAD

**Issue by foxalfabravo** [jmrozanec/cron-utils#14]
Unix syntax * * * * 3,5-6 becomes  0 * * * * 3,5-6 * when using a CronType.UNIX to CronType.QUARTZ mapper

The result should be 0 * * * * 4,6-7 * as Monday is shifted in Quartz syntax

**Comment by jmrozanec** [comment]
@foxalfabravo thank you for reporting this.

**Comment by foxalfabravo** [comment]
Test case added in my repository

**Comment by jmrozanec** [comment]
@foxalfabravo thank you for contributing the tests! We'll use them and merge as soon as we have a solution.
