### ISSUE TITLE
IllegalArgumentException: Values must not be empty

### ISSUE THREAD

**Issue by francisdb** [jmrozanec/cron-utils#140]
Reproducer below (scala)

```scala
      val cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ)
      val parser = new CronParser(cronDefinition)
      val parsed = parser.parse("0 0 10 ? * SAT-SUN")
      val executionTime = ExecutionTime.forCron(parsed)
      val next = executionTime.nextExecution(ZonedDateTime.now)
```

```
[error]    java.lang.IllegalArgumentException: Values must not be empty (Preconditions.java:224)
[error] com.cronutils.utils.Preconditions.checkNotNullNorEmpty(Preconditions.java:224)
[error] com.cronutils.model.time.TimeNode.<init>(TimeNode.java:27)
[error] com.cronutils.model.time.ExecutionTime.generateDaysDoWAndDoMSupported(ExecutionTime.java:327)
[error] com.cronutils.model.time.ExecutionTime.generateDays(ExecutionTime.java:314)
[error] com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:164)
[error] com.cronutils.model.time.ExecutionTime.nextExecution(ExecutionTime.java:118)
```

This error could explain a bit more about what values it is talking?
seems there were other similar issues: #75 #70 #27

**Comment by jmrozanec** [comment]
@francisdb thanks for reporting this. We can improve the Exception message - will mark it as an enhancement. Thanks!

**Comment by francisdb** [comment]
@jmrozanec Could you tell me what is wrong in the expression

**Comment by francisdb** [comment]
@jmrozanec I think this should have the bug tag as we see these on cron expressions that are happily accepted by Quartz

**Comment by jmrozanec** [comment]
@francisdb done. Thanks!

**Comment by jmrozanec** [comment]
@francisdb Fixed! Thank you for reporting the issue!

**Comment by jmrozanec** [comment]
@francisdb version 6.0.0 was released with this fixes!

**Comment by francisdb** [comment]
upgrading right away 🎉

**Comment by francisdb** [comment]
Actually I wonder if Quartz will actually trigger on this kind of expression? Currently requesting nextExecution using cronutils yields an absent Optional.

the workaround is using `SAT,SUN` instead of `SAT-SUN`

**Comment by jmrozanec** [comment]
@francisdb thank you for the case considered. We will check on Quartz and come back.
