### ISSUE TITLE
Wrong ExecutionTime create with slash

### ISSUE THREAD

**Issue by Ksisu** [jmrozanec/cron-utils#141]
**My cron expression:** 
3/5 * * * * ?

**My test Code:**
```scala
val cronDefQuartz = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ)
val cronParser = new CronParser(cronDefQuartz)
val cron = cronParser.parse("3/5 * * * * ?")

System.out.println(cron.retrieve(CronFieldName.SECOND).getExpression.asString()) // == 3/5

val executionTime: ExecutionTime = ExecutionTime.forCron(cron)
var d = ZonedDateTime.now().withSecond(59)
var i = 20
while (i > 0) {
  i = i - 1
  d = executionTime.nextExecution(d)
  System.out.print(" " + d.getSecond)
}
```

**Expected Result:** 
3 8 13 18 23 28 33 38 43 48 53 58 3 8 13 18 23 28 33 38

**Actual result:**
0 5 10 15 20 25 30 35 40 45 50 55 0 5 10 15 20 25 30 35

http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html
> **Special characters**
> / - used to specify increments. For example, 
> “0/15” in the seconds field means “the seconds 0, 15, 30, and 45”.  And
>  “5/15” in the seconds field means “the seconds 5, 20, 35, and 50”.
>  You can also specify ‘/’ after the ‘’ character - in this case ‘’ is equivalent to having ‘0’ before the ‘/’. ‘1/3’ in the day-of-month field means “fire every 3 days starting on the first day of the month”.

**Comment by jmrozanec** [comment]
@Ksisu thank you for reporting this. From the description sounds like a duplicate of [issue 123](https://github.com/jmrozanec/cron-utils/issues/123). Which version are you using? May we ask to send a PR with a test case to reproduce the issue? Thanks!

**Comment by Ksisu** [comment]
Ohh. I used 5.0.4 
After updated to 5.0.5, it works fine. 
Thx!

**Comment by jmrozanec** [comment]
@Ksisu great to hear that! Thanks! :) And Merry Christmas!

**Comment by jmrozanec** [comment]
@Ksisu version 6.0.0 was released with this!
