### ISSUE TITLE
Special Character L for day of week behaves differently in Quartz

### ISSUE THREAD

**Issue by laxgoalie392** [jmrozanec/cron-utils#142]
According to [Quartz](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html) using L for DoW is the last day (Saturday) in the week but cron-utils seems to return last Friday of the month. Am I doing something wrong or is this an issue?

```
    @Test
    public void lastDayOfTheWeek() throws Exception {
        Cron cron = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ))
                .parse("0 0 0 ? * L *");

        ZoneId utc = ZoneId.of("UTC");

        ZonedDateTime date = LocalDate.parse("2016-12-22").atStartOfDay(utc);

        ZonedDateTime cronUtilsNextTime = ExecutionTime.forCron(cron).nextExecution(date);// 2016-12-30T00:00:00Z

        org.quartz.CronExpression cronExpression = new org.quartz.CronExpression(cron.asString());
        cronExpression.setTimeZone(TimeZone.getTimeZone(utc));
        Date quartzNextTime = cronExpression.getNextValidTimeAfter(Date.from(date.toInstant()));// 2016-12-24T00:00:00Z

        assertEquals(quartzNextTime.toInstant(), cronUtilsNextTime.toInstant()); // false
    }
```

**Comment by jmrozanec** [comment]
@laxgoalie392 thank you for using cron utils. I am trying to reproduce the test above. Are you using the latest version? Wouldn't you mind sending a PR with the test in order to merge to the project? Thanks!

**Comment by laxgoalie392** [comment]
Here are the following versions I am using. Is there any part in particular that isn't working for you? The LocalDate I am using is from the java.time package.

```
        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
            <version>2.1.7</version>
        </dependency>
        <dependency>
            <groupId>com.cronutils</groupId>
            <artifactId>cron-utils</artifactId>
            <version>5.0.5</version>
        </dependency>
```

I won't be able to to submit a PR for a few weeks. I'm going on vacation. For the time being I am just using the Quartz CronExpression to calculate execution times. But I really would love to be using this library instead!

Thanks for looking into this for me!

**Comment by jmrozanec** [comment]
@laxgoalie392 could you have a look at the issue? Thanks!

**Comment by jmrozanec** [comment]
@laxgoalie392 Fixed! Kudos to @meincs for this!

**Comment by jmrozanec** [comment]
@laxgoalie392 @meincs version 6.0.0 was released with this.
