### ISSUE TITLE
ExecutionTime return unexpected dates for incremental hour period

### ISSUE THREAD

**Issue by emsyzz** [jmrozanec/cron-utils#144]
`ExecutionTime` returns unexpected results for Quartz expressions when defining periodic incremental hours and month.

For example, `0 0 16-19/2 1 * ?` will generate next five dates as follows (relative to date this issue is created):
- 01.01.2017 00:00:00
- 01.01.2017 02:00:00
- 01.01.2017 04:00:00
- 01.01.2017 06:00:00
- 01.01.2017 08:00:00

Expected values:
- 01.01.2017 16:00:00
- 01.01.2017 18:00:00
- 01.02.2017 16:00:00
- 01.02.2017 18:00:00
- 01.03.2017 16:00:00

Replacing day of month with wildcard `*` produces unexpected results as well `0 0 16-19/2 * * ?`:
- 27.12.2016 16:00:00
- 27.12.2016 18:00:00
- 27.12.2016 20:00:00
- 27.12.2016 22:00:00
- 28.12.2016 00:00:00

Expected values:
- 27.12.2016 16:00:00
- 27.12.2016 18:00:00
- 28.12.2016 16:00:00
- 28.12.2016 18:00:00
- 29.12.2016 16:00:00

**Comment by jmrozanec** [comment]
@emsyzz Thank you for reporting this. May I ask you to put the case into a test and contribute it with a pull request? We will be eager to accept it. Thanks!

**Comment by emsyzz** [comment]
I have made a pull request #146 with generalized test case for this issue.

**Comment by meincs** [comment]
Provided PR #212 to fix the issue.

**Comment by jmrozanec** [comment]
@meincs Thanks! 😄  Merged! Tomorrow we get a new release!
