### ISSUE TITLE
Cron.validate() should throw a checked exception instead of IllegalArgumentException (RuntimeException)

### ISSUE THREAD

**Issue by hareluya86** [jmrozanec/cron-utils#149]
Hi, just a suggestion that a checked exception class should be created and thrown in the case where cron expression is invalid so that the client application can catch it explicitly to display the exception message. 

My application is calling creating a Cron object through an EJB, hence when RuntimeExceptions are thrown, the EJB will throw an EJBException with IllegalArgumentException wrapped in it. For the client application to see the message, it has to "dig" the EJBException's cause stack to find a specific type of exception. A checked exception will force the EJB method at compile time to either handle it or throw it upwards, where the client will have to handle. This will also benefit non-EJB methods.

I'll be glad to contribute. Let me know what you think. Thanks!

**Comment by amanteaux** [comment]
Hi,

So your saying that the actual system is not explicit enough and that you may forget to catch the `IllegalArgumentException`. The consequence will be that the `IllegalArgumentException` will be wrapped in an `EJBException`, so you find it more difficult to debug.

As a result, you want to break the API and force people to catch the potential checked Exception event if they want to re-throw it?

Aurélien

**Comment by jmrozanec** [comment]
@amanteaux thank you for providing a quick answer. @hareluya86 I agree with @amanteaux regarding API compatibility and I don't see value in wrapping the exception into another exception. 

I am open, though, to a discussion on this. When creating the current API, I found no value in specifying checked exceptions for each case. Perhaps you can help us understand more scenarios where this would be valuable, and we may change our minds. Thanks!

**Comment by hareluya86** [comment]
Let's say you offer the users a text field to input the cron expression and there is an error in the expression. I didn't even know it is throwing IllegalArgumentException until I looked into the code. In this case I need to expect a checked exception because I would want my application to catch it and return it to the user. Of course I can read the code and learn that it is throwing a RuntimeException, but it is not obvious enough, especially if the client is expected to have their inputs validated. IllegalArgumentException should be a checked exception instead.

Well I've not thought about breaking the API. Perhaps it is of no value and people should deploy their code to production and learn that it is throwing an exception that they have not caught until they look at their server logs or check out your code.

**Comment by amanteaux** [comment]
@hareluya86 you are right, the API should mention it can raise an `IllegalArgumentException`, the javadoc is missing on `Cron.validate()`. I think @jmrozanec will be happy to merge your request if you provide documentation on this method.

About checked exception, they are more and more considered as bad practice: http://stackoverflow.com/questions/6115896/java-checked-vs-unchecked-exception-explanation

As of Java 8 and the introduction of lambda expression, checked exception are really a pain and they should be avoided as much as possible: http://stackoverflow.com/questions/18198176/java-8-lambda-function-that-throws-exception

**Comment by jmrozanec** [comment]
@hareluya86 if you agree, we can document the case. I am looking forward to merge the PR. We can also reference this conversation for greater detail on the decision. Thank you for reaching out!

**Comment by hareluya86** [comment]
@amanteaux @jmrozanec Sure, that will work for me. I'll submit a pull request. 

@amanteaux Thanks for sharing the links too! While I have not used lambda expressions yet, I hope they do provide for it in future Java releases because I think checked exceptions are still useful for developers.

**Comment by jmrozanec** [comment]
@hareluya86 @amanteaux Merged! Thank you both!

**Comment by jmrozanec** [comment]
@hareluya86 If the application you are working on has a public domain, you are welcome to share the URL with us. We would like to open a wiki section highlighting projects that leverage cron-utils.

**Comment by jmrozanec** [comment]
@hareluya86 @amanteaux version 6.0.0 was released with this!
