### ISSUE TITLE
Quartz L-x calculation fails in day of month with RuntimeException

### ISSUE THREAD

**Issue by knechtandreas** [jmrozanec/cron-utils#151]
This expression:
`0 15 10 ? * MON-FRI`

Fails with `Value -1 for dayOfMonth must be in the range [1,31]`.  This should be a valid Quartz cron expression.

This is on version 4.1.1 with the built in QUARTZ definition.

**Comment by jmrozanec** [comment]
@knechtandreas Thank you for reporting the issue. Can you verify if still unresolved for the latest version? In that case, we would be glad to merge a test for it. Thanks!

**Comment by knechtandreas** [comment]
@jmrozanec so I just tested with 5.0.5 and `0 15 10 ? * MON-FRI` works!  Great.

However I did run into 1 more that should work, but doesn't :(:
`0 15 10 L-2 * ?`: Reports `java.lang.RuntimeException: Non integer values at intervals are not fully supported yet.`

This was on the latest version.

**Comment by jmrozanec** [comment]
@knechtandreas Thanks! May I ask you for a test for this case? We will be eager to accept a PR with it. Thanks!

**Comment by knechtandreas** [comment]
@jmrozanec yeah sure - it will take me a couple of hours (got some other tasks first). I'll post back when it's ready.

**Comment by knechtandreas** [comment]
@jmrozanec ok I added a failing test now in PR #152 .  Let me know if you want me to get rid of the code formatting cleanups (couple of removed unused imports and a few missing spaces).

**Comment by jmrozanec** [comment]
@knechtandreas Great! Just merged the PR to the codebase. Thank you for contributing :)

**Comment by jmrozanec** [comment]
@knechtandreas Fixed! Kudos to @meincs for this!

**Comment by jmrozanec** [comment]
@knechtandreas @meincs version 6.0.0 was released with this!
