### ISSUE TITLE
Extend ExecutionTime API to allow save determination of next execution dates.

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#155]
Currently it is not possible to savely determine all potential execution dates in the future, if the cron expression limits the range, e.g. limit to year 2017. In that case a call to ExecutionTime#nextExecution with argument ZonedDateTime.of(2018, 1, 1, 0, 0, 0, 0, ZoneId.systemDefault())) will result in an IllegalArgumentException. Knowing the implementation it is surely possible to catch this exception, but it is not save to do so, since the implementation may change. Therefore it would be better to safely signal to the user, that no more execution dates exist, e.g. by providing an additional ExceutionTime method which could be implemented as follows:
```java
    /**
     * Provide nearest date for next execution, if such a date exists. Otherwise
     * an {@code Optional} instance with no contained reference.
     * 
     * @param date - ZonedDateTime instance. If null, a NullPointerException
     *            will be raised.
     * @return optional ZonedDateTime instance, never null. Next execution time,
     *         if one exists. An {@code Optional} instance with no contained
     *         reference otherwise.
     */
    public Optional<ZonedDateTime> nextExecutionIfExistent(final ZonedDateTime date) {
        Preconditions.checkNotNull(date);
        try {
            ZonedDateTime nextMatch = nextClosestMatch(date);
            if (nextMatch.equals(date)) {
                nextMatch = nextClosestMatch(date.plusSeconds(1));
            }
            return Optional.of(nextMatch);
        }
        catch (final NoSuchValueException e) {
            return Optional.empty();
        }
    }
```
I guess the same extension would be helpfull for lastExecution.

**Comment by jmrozanec** [comment]
@meincs this is a good idea. If you post a pull request, we will be eager to accept and merge it. Thanks!

**Comment by jmrozanec** [comment]
@meincs we implemented the suggested changes. Thanks!
