### ISSUE TITLE
CLI suggestions

### ISSUE THREAD

**Issue by bflorat** [jmrozanec/cron-utils#165]
Hi,
- I would prefer options without arguments :  -v for validation instead -a "validate"
- Currently, we need to -cp <dependencies.jar> to make the CLI work, I find easier to use a uber jar (see maven code bellow). Maybe could you provide an uber jar version of cron-utils or at least add this is your pom ?
Cheers,
Bertrand

```
<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>com.cronutils.cli.CronUtilsCLI</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>

mvn assembly:assembly -DdescriptorId=jar-with-dependencies
```

**Comment by jmrozanec** [comment]
@bflorat we totally agree with both proposals. If you send a pull request with the proposed changes, we will be eager to merge to master. 
After that we may need to review the deployment, to ensure the jar with and without dependencies included are released with different classifiers under the same version. Thanks!

**Comment by jmrozanec** [comment]
Reference to PR: #166

**Comment by ankitjaininfo** [comment]
As the PR https://github.com/jmrozanec/cron-utils/pull/166 is merged, is this safe to make this closed?

The reason I am requesting to mark this close is, there are 74 commits (https://github.com/jmrozanec/cron-utils/compare/5.0.5...master ) waiting to be release for 6.0. This one is last in the milestone.

@gs-mkavali FYI.

**Comment by ankitjaininfo** [comment]
We are waiting for https://github.com/jmrozanec/cron-utils/commit/0ef0cf8f7f883c11c9117d4a6c8eb0d44332718b to be released.

**Comment by jmrozanec** [comment]
@ankitjaininfo we can release a new version. Before marking this issue closed, we wanted to provide CLI for other features as well. We will release a version with everything done up to now, and soon follow with another one complementing the CLI functionality. Thanks!
