### ISSUE TITLE
Support OSGi meta data in provided JAR

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#171]
This would be usefull for all that intend to use the library in a OSGi runtime environment. Otherwise one needs to work with customized JARs. Guava and SLF4J stuff is shipped with OSGi meta data too.

The generation of OSGi meta data can easily be achieved with the Gradle build system.

Please find below a sample Gradle build file:
```gradle
apply plugin: 'java'
// Add manifest OSGi meta data
apply plugin: 'osgi'
// Support Eclipse IDE
apply plugin: 'eclipse'

group = 'com.cronutils'
version = '5.0.6-SNAPSHOT'

description = """cron-utils"""

tasks.withType(JavaCompile) {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    options.encoding = 'UTF-8'
}


repositories {

     maven { url "http://repo.maven.apache.org/maven2" }
}

ext {
    guavaVersion = '18.0'
	slf4jVersion = '1.7.12'
}


dependencies {
    compile group: 'org.slf4j', name: 'slf4j-api', version: slf4jVersion
    compile group: 'com.google.guava', name: 'guava', version: guavaVersion
	
    compile group: 'commons-cli', name: 'commons-cli', version:'1.4'
    compile group: 'com.jakewharton.threetenabp', name: 'threetenabp', version:'1.0.5'
    compile group: 'org.threeten', name: 'threetenbp', version:'1.3.2'

    testCompile group: 'org.slf4j', name: 'slf4j-log4j12', version:'1.7.12'
    testCompile group: 'eu.lp0.slf4j', name: 'slf4j-android', version:'1.7.22-0'
    testCompile group: 'log4j', name: 'log4j', version:'1.2.17'
    testCompile group: 'junit', name: 'junit', version:'4.12'
    testCompile group: 'org.mockito', name: 'mockito-core', version:'1.10.19'
    testCompile group: 'org.powermock', name: 'powermock-module-junit4', version:'1.6.2'
    testCompile group: 'org.powermock', name: 'powermock-api-mockito', version:'1.6.2'
    testCompile group: 'org.quartz-scheduler', name: 'quartz', version:'2.2.3'
}


jar {
	manifest {
		attributes("Sealed": true)
		// NOTE: in OSGi versionRange=X.Y.Z is equivalent to [X.Y.Z, infinity), e.g. accept any Guava greater or equal to guavaVersion until compatibility is broken
		instruction 'Import-Package', 'com.cronutils.*', "com.google.common.*;version=\"${guavaVersion}\"", "org.slf4j.*;version=\"${slf4jVersion}\"", /* handle any other dependencies as optional */ "'*';resolution:=optional"
	}
}
```

**Comment by jmrozanec** [comment]
@meincs thank you for the suggestion! 😄  We will consider including this.

**Comment by meincs** [comment]
Unfortunately I'm not really familiar with Maven. So if the provided working example based on Gradle can't be used, maybe the following link could help to contribute:
http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

**Comment by jmrozanec** [comment]
@meincs great! Will check that. We will release a new version this weekend with progress done up to know, and right after that we may consider this issue. Porting to gradle would be a great win - also for Android based projects.

**Comment by Naxos84** [comment]
For creating bundles with maven you could use:

<plugin>
			<groupId>org.apache.felix</groupId>
			<artifactId>maven-bundle-plugin</artifactId>
			<version>2.3.7</version> 
			<extensions>true</extensions>
			<configuration>
				<instructions>
					<Bundle-Name>cron-utils</Bundle-Name>
					<Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
					<Bundle-Version>${project.version}</Bundle-Version>
					<Bundle-RequiredExecutionEnvironment>JavaSE-1.7</Bundle-RequiredExecutionEnvironment>
					<Export-Package>com.cronutils.*</Export-Package>
				</instructions>
				<niceManifest>true</niceManifest>
			</configuration>
		</plugin>

**Comment by Naxos84** [comment]
For creating bundles with Maven you could use:

```
<plugin>
			<groupId>org.apache.felix</groupId>
			<artifactId>maven-bundle-plugin</artifactId>
			<version>2.3.7</version> 
			<extensions>true</extensions>
			<configuration>
				<instructions>
					<Bundle-Name>cron-utils</Bundle-Name>
					<Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
					<Bundle-Version>${project.version}</Bundle-Version>
					<Bundle-RequiredExecutionEnvironment>JavaSE-1.7</Bundle-RequiredExecutionEnvironment>
					<Export-Package>com.cronutils.*</Export-Package>
					<!-- <Private-Packages>org.slf4j.*</Private-Packages> -->
				</instructions>
				<niceManifest>true</niceManifest>
			</configuration>
		</plugin>
```

**Comment by jmrozanec** [comment]
@Naxos84 thank you for the details above! If you send us a PR, we would be glad to merge it :smile: Thanks!
