### ISSUE TITLE
Crontab field not support multiple special characters

### ISSUE THREAD

**Issue by caojingwei** [jmrozanec/cron-utils#177]
like "0 2-5/1 * 1-3 * ? *"

        String quartzCronExpression = "0 2-5/1 * 1-3 * ? *";

        CronParser quartzCronParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(QUARTZ));

        Cron parsedQuartzCronExpression = quartzCronParser.parse(quartzCronExpression);
        System.out.println(
                String.format("Original expression: '%s', After parsing to Cron: '%s'. Are the same? %s",
                        quartzCronExpression,
                        parsedQuartzCronExpression.asString(),
                        quartzCronExpression.equals(parsedQuartzCronExpression.asString())
                )
        );

I get:

Original expression: '0 2-5/1 * 1-3 * ? *', After parsing to Cron: '0 2-5 * 1-3 * ? *'. Are the same? false

**Comment by jmrozanec** [comment]
@caojingwei thank you for reporting this issue! If you have some time to contribute a fix or the snippet as a test, will be highly appreciated. Thanks!

**Comment by meincs** [comment]
Is this really an issue? Period one applied on a range is simply superfluos. Thus
2-5/1 is semantically equivalent with 2-5, or 2,3,4,5.
Or is it really required that Cron#asString() returns the unparsed cron expression?

**Comment by caojingwei** [comment]
what about "0 0-22/2 * 1-3 * ? *"
so it must be "0 0,2,4,6,8,10,12,14,16,18,20,22 * 1-3 * ? *" 
I can't ask others to write that.
