### ISSUE TITLE
lastExecution returns incorrect value

### ISSUE THREAD

**Issue by mspiegel** [jmrozanec/cron-utils#18]
Here's a new unit test for ExecutionTimeIntegrationTest. The println is just for debugging.

    @Test
    public void testHourlyIntervalTimeFromLastExecution() throws Exception {
        DateTime now = DateTime.now();
        int hour = now.getHourOfDay();
        int previousHour = (hour > 0) ? (hour - 1) : 23;
        String quartzCronExpression = "0 0 " + previousHour + " * * ?";
        ExecutionTime executionTime = ExecutionTime.forCron(quartzCronParser.parse(quartzCronExpression));
        System.out.println(executionTime.lastExecution(now));
        assertTrue(executionTime.timeFromLastExecution(now).getStandardMinutes() <= 120);
    }

**Comment by jmrozanec** [comment]
Thanks! Yes, this is a bug. Help on it is appreciated!

**Comment by jmrozanec** [comment]
@mspiegel issue solved! Thank you for reporting!
