### ISSUE TITLE
Bad asString() representation for 0/1 expressions

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#180]
If I were to pass in 0/1 for the minutes field, I'd expect 0/1 or * as a possible output. Instead, I see 0, which to me seems wrong because it'd be 0 minute (out of 0-59).

This issue was reported by @tastle at #178

**Comment by meincs** [comment]
@jmrozanec  Can be closed, since test case EveryTest#testAsString no longer fails.

**Comment by meincs** [comment]
@jmrozanec Issue 180 can effectively be closed. Both test cases on the issue pass or do I miss something?

**Comment by tastle** [comment]
I just updated my clone to test it out and I agree that the problem reported has been fixed.

**Comment by jmrozanec** [comment]
@tastle @meincs thank you for checking for this. We are closing the issue based on your feedback!
