### ISSUE TITLE
cronutils should not depend on slf4j-log4j12

### ISSUE THREAD

**Issue by francisdb** [jmrozanec/cron-utils#187]
cronutils should not depend on a logger implementation (except for testing), only slf4j

since `6.0.0` there is a dependency on `slf4j-log4j12` which redirects all logging to log4j!

from https://www.slf4j.org/legacy.html#log4jRecursion
> slf4j-log4j12.jar, that is the log4j binding for SLF4J, will force all SLF4J calls to be delegated to log4j

this is a serious issue as it will affect all users using other logging frameworks like logback

**Comment by jmrozanec** [comment]
@francisdb you are right about this. Thank you for reporting - will issue a new release without this dependency soon. Thanks!

**Comment by francisdb** [comment]
In my eyes this is a bug and not a enhancement :-)

**Comment by jmrozanec** [comment]
@francisdb dependency scope was updated to test. A new release will follow soon. Thank you for reporting! 😄

**Comment by francisdb** [comment]
In the current pom the dependency is added twice!
