### ISSUE TITLE
Cron expressions with DoY fields return unexpected results if DoY is omitted or set to question mark

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#188]
Cron definitions with additional DoY field added shall behave as their counterpart definitions if the DoY field is omitted or set to question mark.

**Comment by meincs** [comment]
As long as the issue isn't fixed one could use the extended parser iff the  DoY is present and its counterpart parser otherwise.

**Comment by jmrozanec** [comment]
@meincs great. We just merged the PR and will release a new version soon. Thanks!

**Comment by jmrozanec** [comment]
@meincs we just released version [6.0.1](https://github.com/jmrozanec/cron-utils/releases/tag/6.0.1) with this fix! Thanks again for contributing to cron-utils! :smile:
