### ISSUE TITLE
ExecutionTime#isMatch does not work correctly if called with the lower bound value

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#192]
E.g. the first day of year 2017 should match for both of the following Quartz Cron expressions:

"0 0 0 1 * ?" 
"0 0 0 1 * ? 2017"

However ExecutionTime#isMatch fails for the second Cron expression constraint to year 2017.

**Comment by jmrozanec** [comment]
@meincs thank you for reporting this. We are merging the PR but not closing the issue, since we see a test failing still: ExecutionTimeQuartzIntegrationTest.mustMatchLowerBoundDateMatchingCronExpressionRequirements
Thanks!
