### ISSUE TITLE
Ensure full compliance of quartz CronDefinition to Quartz specification

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#194]
- do not accept special character # (hash) in DoM field
- do not accept W in DoW field

**Comment by jmrozanec** [comment]
@meincs we cannot close the issue, since there is a failing test: FieldParserTest.testParseOnWithHash01

**Comment by jmrozanec** [comment]
@meincs merged! Thanks! 😄

**Comment by jmrozanec** [comment]
@meincs we released a new version! 6.0.2 is now available!
