### ISSUE TITLE
ExecutionTime.isMatch() is too strict when checking ZonedDateTimes against Cron Expressions.

### ISSUE THREAD

**Issue by breathermachine** [jmrozanec/cron-utils#200]
package com.test;

    import com.cronutils.model.Cron;
    import com.cronutils.model.definition.CronDefinition;
    import com.cronutils.model.definition.CronDefinitionBuilder;
    import com.cronutils.model.time.ExecutionTime;
    import com.cronutils.parser.CronParser;
    import org.junit.*;
    import org.threeten.bp.ZoneId;
    import org.threeten.bp.ZonedDateTime;

    import static com.cronutils.model.CronType.QUARTZ;
    import static org.junit.Assert.*;

    /**
     * Created by johnpatrick.manalo on 6/19/17.
     */
    public class ExecutionTimeIsMatchTest {
        // Does not pass!
        @Test
        public void testShouldMatchCronEvenIfNanoSecondsDoesNotMatch() {
            CronDefinition cronDefinition =
                    CronDefinitionBuilder.instanceDefinitionFor(QUARTZ);

            CronParser parser = new CronParser(cronDefinition);
            Cron quartzCron = parser.parse("00 00 10 * * ?");

            quartzCron.validate();

            // NOTE: Off by 3 nano seconds
            ZonedDateTime zdt = ZonedDateTime.of(1999, 07, 18, 10, 00, 00, 03, ZoneId.systemDefault());

            // Must be true
            assertTrue(ExecutionTime.forCron(quartzCron).isMatch(zdt));
        }

        // Nano second-perfect (passes, no surprises here)
        @Test
        public void testMatchExact() {
            CronDefinition cronDefinition =
                    CronDefinitionBuilder.instanceDefinitionFor(QUARTZ);

            CronParser parser = new CronParser(cronDefinition);
            Cron quartzCron = parser.parse("00 00 10 * * ?");

            quartzCron.validate();

            ZonedDateTime zdt = ZonedDateTime.of(1999, 07, 18, 10, 00, 00, 00, ZoneId.systemDefault());

            assertTrue(ExecutionTime.forCron(quartzCron).isMatch(zdt));
        }
    }

**Comment by jmrozanec** [comment]
@breathermachine thank you for reporting this. May we ask you for a PR with this tests? Thanks!

**Comment by meincs** [comment]
@breathermachine What is the expected behaviour and where do I find the (Quartz) specification on that issue? Should nanos be erased or round in a mathematical sense?

**Comment by breathermachine** [comment]
@meincs The specific cron specification (Quartz, etc.) doesn't matter as I believe all of the cron dialects supported by cron-utils do not support nanosecond precision. Thus, comparing Cron schedules with nanosecond precision would be wrong, which fortunately, was easy to catch.

Here is the link for the Quartz cron trigger:
http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

**Comment by jmrozanec** [comment]
@breathermachine this is accurate. In general, we should consider the precision the cron format allows to specify - if up to seconds, then seconds (Quartz), if up to minutes, then minutes (unix crons, cron4j).

**Comment by breathermachine** [comment]
@jmrozanec Yes to have varying granularity of checking is the best solution.

**Comment by mohanarpit** [comment]
@jmrozanec Would appreciate it if you could review the pull request with the code change that makes this test pass.

**Comment by jmrozanec** [comment]
@breathermachine @meincs Fixed! Kudos to @mohanarpit!

**Comment by mohanarpit** [comment]
@jmrozanec Thanks for the quick response. BTW, thank you for merging my first code-related PR to an OSS project. 😄

**Comment by jmrozanec** [comment]
@mohanarpit Congrats! You are welcome! 😄
