### ISSUE TITLE
"sun" is parsed to 7 for cron4j CronDefinition, causing an IllegalArgumentException

### ISSUE THREAD

**Issue by pangyikhei** [jmrozanec/cron-utils#202]
Build: 6.0.1
Attempting to parse a cron expression (using a CronParser defined with the cron4j definition) with the alias for Sunday ("sun") results in a IllegalArgumentException:

Test program:
```
package com.cronutils;

import com.cronutils.model.Cron;
import com.cronutils.model.CronType;
import com.cronutils.model.definition.CronDefinitionBuilder;
import com.cronutils.parser.CronParser;
import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class TestCron4jDefinition {

  @Test
  public void testSunday() throws Exception {
    CronParser cronParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.CRON4J));
    Cron cron = cronParser.parse("* * * * sun");
    assertThat(cron.asString(), is("* * * * 0"));
  }
}

```

Result:
```
java.lang.IllegalArgumentException: Failed to parse '* * * * sun'. Value 7 not in range [0, 6]
...
Caused by: java.lang.IllegalArgumentException: Value 7 not in range [0, 6]
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.isInRange(ValidationFieldExpressionVisitor.java:158)
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:132)
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:69)
	at com.cronutils.model.field.expression.FieldExpression.accept(FieldExpression.java:44)
	at com.cronutils.model.Cron.validate(Cron.java:92)
	at com.cronutils.parser.CronParser.parse(CronParser.java:96)
	... 23 more
```

**Comment by jmrozanec** [comment]
@pangyikhei Thank you for reporting this. We would greatly appreciate a PR with this test cases. Thanks!

**Comment by pangyikhei** [comment]
@jmrozanec is there a specific reason that the `FieldConstraintsBuilder.daysOfWeekMapping` uses 1 (MON) - 7 (SUN) instead of 0 (SUN) to 6 (SAT)?

`FieldConstraintsBuilder.forField` sets the endRange to 6 for DAYS_OF_WEEK (so 0-6) by default.

If someone makes a custom cron definition with the default `withDayOfWeek()` `FieldDayOfWeekDefinitionBuilder` using the "SUN" alias also fails to parse.

When the Monday DoW is set to 1, no mapping shifts are performed for the day of week mapping.

The Quartz definition sets Monday DoW to 2 (with range 1-7) so it shifts the mapping to SUN(1) - SAT(7).
If the mapping was SUN (0) - SAT (6) it would shift it to SUN(1) - SAT(7) too.

**Comment by jmrozanec** [comment]
@pangyikhei thank you for contributing a fix!
