### ISSUE TITLE
timeToNextExecution returns Duration evaluates to 0

### ISSUE THREAD

**Issue by greenlaw110** [jmrozanec/cron-utils#21]
Firstly very nice tool! thank you!

Now the problem:

1. I use the tool to schedule tasks to be executed periodically
2. The following code calculates the next time the job shall be invoked:

```
@Override
void schedule(AppJobManager manager, _Job job) {
    DateTime now = DateTime.now();
    ExecutionTime executionTime = ExecutionTime.forCron(cron);
    Duration nextExecution = executionTime.timeToNextExecution(now);
    long seconds = nextExecution.getStandardSeconds();
    manager.executor().schedule(job, seconds, TimeUnit.SECONDS);
}
```

Problem is I found it always returns `0` for the next time. Thus the job is executed huge number of times (>300) while I expected it to be executed for 1 time. The schedule method is called after the time is due and job is executed.

**Comment by jmrozanec** [comment]
@greenlaw110 thank you for reporting this! 
Could you please provide the cron expression you are using to execute the code, and perhaps a test that reproduces the issue? Thank you in advance!

**Comment by greenlaw110** [comment]
Actually any cron expression lead to the same result. That's because the pattern I've used to applying cron-util. As you see `schedule` method is executed right at the time cron task should invoke (actually just invoked), thus you want to get the `timeToNextExecution` exactly when it's due to execution, the library returns 0, which is the `timeToCurrentExecution`.  I end up with something like following to workaround the issue:

```java
void schedule(AppJobManager manager, _Job job) {
    DateTime now = DateTime.now();
    ExecutionTime executionTime = ExecutionTime.forCron(cron);
    Duration nextExecution = executionTime.timeToNextExecution(now.withDurationAdded(1, 1));
    long seconds = nextExecution.getStandardSeconds();
    int times = 1;
    while (seconds == 0) {
        nextExecution = executionTime.timeToNextExecution(now.withDurationAdded(1, times++));
        seconds = nextExecution.getStandardSeconds();
    }
    manager.executor().schedule(job, seconds, TimeUnit.SECONDS);
}
```

**Comment by jmrozanec** [comment]
I tried to reproduce the issue, but I do not get the issue.
If you have too short intervals, then you will get zero seconds; depending on the cron expression you consider. But if you invoke nextExecution.getMillis(), you may notice that time to next execution decreases accurately.

Also looking at different cron setups, returns accurate results, where Duration interval to next execution is not zero seconds. Example: using the following code, you get a non-zero value most of time.

    ExecutionTime executionTime = ExecutionTime.forCron(quartzCronParser.parse("5 * * * * *"));
    DateTime now = DateTime.now();
    Duration nextExecution = executionTime.timeToNextExecution(now);
    long seconds = nextExecution.getStandardSeconds();
