### ISSUE TITLE
Maven overlapping Class

### ISSUE THREAD

**Issue by notes-jj** [jmrozanec/cron-utils#211]
There is a class overlapping cronutils uses threetenbp:jar:1.3.2, while threetenabp depends on threetenbp:jar:no-tzdb:1.3.3. 

Expected Behavior:

cronutils depends on threetenbp:jar:1.3.3

### Maven Build warning

    [WARNING] threetenbp-1.3.3-no-tzdb.jar, threetenbp-1.3.2.jar define 198 overlapping classes: 
    [WARNING]   - org.threeten.bp.chrono.ChronoZonedDateTimeImpl$1
    [WARNING]   - org.threeten.bp.LocalDate$1
    [WARNING]   - org.threeten.bp.LocalDateTime$2
    [WARNING]   - org.threeten.bp.chrono.JapaneseDate
    [WARNING]   - org.threeten.bp.ZoneRegion
    [WARNING]   - org.threeten.bp.chrono.ChronoZonedDateTime$1
    [WARNING]   - org.threeten.bp.chrono.ChronoDateImpl$1
    [WARNING]   - org.threeten.bp.temporal.ValueRange
    [WARNING]   - org.threeten.bp.temporal.ChronoUnit
    [WARNING]   - org.threeten.bp.Month$2
    [WARNING]   - 188 more...

### Output mvn dependency:tree

    [INFO] +- com.cronutils:cron-utils:jar:6.0.1:compile
    [INFO] |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
    [INFO] |  +- com.google.guava:guava:jar:18.0:compile
    [INFO] |  +- commons-cli:commons-cli:jar:1.4:compile
    [INFO] |  +- com.jakewharton.threetenabp:threetenabp:aar:1.0.5:compile
    [INFO] |  |  \- org.threeten:threetenbp:jar:no-tzdb:1.3.3:compile
    [INFO] |  \- org.threeten:threetenbp:jar:1.3.2:compile

**Comment by jmrozanec** [comment]
@notes-jj thank you for reporting this!
