### ISSUE TITLE
Incorrect Next Execution Time for "* * */1 * 3"

### ISSUE THREAD

**Issue by kensipe** [jmrozanec/cron-utils#223]
On version 6.0.2 the description and next execution of "* * * * 3" is correct.   "* * */1 * 3" should be equivalent.. however it ignores the day of the week for Wednesday in this case.

```
public class CronMain {

    public static void main(String[] args) {
        printEveryWedFromUnixCron();
    }

    private static void printEveryWedFromUnixCron() {
        CronType type = CronType.valueOf("UNIX");
        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(type);
        CronParser parser = new CronParser(cronDefinition);
        Cron unixCron = parser.parse("* * */1 * 3");
        unixCron.validate();
        CronDescriptor descriptor = CronDescriptor.instance(Locale.US);
        System.out.println(descriptor.describe(unixCron));

        ExecutionTime execTime = ExecutionTime.forCron(unixCron);
        Optional<ZonedDateTime> next = execTime.nextExecution(ZonedDateTime.now());
        System.out.println("current time: " + ZonedDateTime.now());
        System.out.println("execution time: " + next.get());
    }
}
```
output on a Tuesday is:
```
every minute every day at Wednesday day
current time: 2017-09-05T11:31:55.407-05:00[America/Chicago]
execution time: 2017-09-05T11:32-05:00[America/Chicago]
```

```
// cron * * * * 3
every minute at Wednesday day
current time: 2017-09-05T11:34:36.694-05:00[America/Chicago]
execution time: 2017-09-06T00:00-05:00[America/Chicago]
```
Is correct.

**Comment by kensipe** [comment]
For following added test shows the failure:  https://github.com/kensipe/cron-utils/blob/next-execute-failure/src/test/java/com/cronutils/Issue223Test.java

**Comment by jmrozanec** [comment]
@kensipe Thank you for reporting this! We will be happy to merge the test to master if you issue us a pull request! 😄  Thanks!

**Comment by pangyikhei** [comment]
This may be a similar misunderstanding of the UNIX cron definition as in #228.

> Note: The day of a command's execution can be specified by two fields -- day of month, and
>        day of week.  If both fields are restricted (i.e., aren't *), the command will be run when
>        either field matches the current time.  For example,
>        ``30  4	1,15 * 5'' would cause a command to be run at 4:30 am on the 1st and 15th of each
>        month, plus every Friday. One can, however, achieve the desired result by adding a test to
>        the command (see the last example in EXAMPLE CRON FILE below).

* * */1 * 3 is being considered as "restricted" on both day of month and day of week, which causes the UNIX definition to say that 2017-09-05T11:32-05:00 is the next execution time, as Sept. 5 matches on the day of month.

If you used the CRON4J cron definition or the custom cron definition mentioned in Issue #228 then the test will pass.

I'm not 100% confident that */1 counts as restricted in the actual Linux crontab. I don't have a Linux machine handy so if someone can test it out that would be great.

**Comment by jmrozanec** [comment]
@kensipe Solved! Kudos to @pangyikhei and @minidmnv!

**Comment by pangyikhei** [comment]
I got an Ubuntu Linux 16.04.3 LTS machine up and running and tested this.

`* * */1 * 5` doesn't trigger today (Tuesday, October 3, 2017) so `*/1` should be interpreted as `*`. Thanks to @minidmnv for the fix.

Also double checked that it does trigger when either DoW or DoM is matched with `* * 1-5 * 5`. The cron job is triggered even though it is not Friday since the DoM is satisfied.

**Comment by jmrozanec** [comment]
@pangyikhei Thanks! 😄
