### ISSUE TITLE
Getting bad date for last/next execution

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#225]
See commented tests at ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest
- testLastExecutionEveryTwoWeeksStartingWithFirstDayOfYear
- testNextExecutionEveryTwoWeeksStartingWithFirstDayOfYear

**Comment by pangyikhei** [comment]
@jmrozanec I checked out the master branch and uncommented these tests and they are currently passing.

**Comment by jmrozanec** [comment]
@pangyikhei great! We are closing the issue! 😄  Thank you for the update!
