### ISSUE TITLE
Add support for Chinese language

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#226]
We should support Chinese language.

**Comment by shangyilim** [comment]
what kind of chinese language support do you mean?

**Comment by jmrozanec** [comment]
@shangyilim Thank you for reaching out! If we can support simplified Chinese or traditional Chinese, would be great. Are there other options? I apologize for my ignorance. We see many Chinese users for this library, we have no support for Chinese language and think would be a great addition to it. Thanks!

**Comment by shangyilim** [comment]
I meant what kind of language support is needed for this library ? What do chinese users need from this library? Does it mean that `MON-FRI` should be replaced with chinese equivalent? Or rather the documentation should be translated in chinese .

**Comment by lovepoem** [comment]
I fix it in https://github.com/jmrozanec/cron-utils/issues/230

**Comment by jmrozanec** [comment]
@lovepoem Thank you! Merged into master!
@shangyilim do you think translating the README.md to Chinese may help to its adoption in China? If so, we would be glad to see such a contribution!
