### ISSUE TITLE
0 5-35/30 * * * ? -> every 30 minutes every %s between 5 and 35

### ISSUE THREAD

**Issue by dkelkhoff** [jmrozanec/cron-utils#227]
Getting a leaking "%s" in description output, given the following code:

CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
Cron cron = parser.parse("0 5-35/30 * * * ?");
CronDescriptor descriptor = CronDescriptor.instance(Locale.US);
descriptor.describe(cron);

**Comment by jmrozanec** [comment]
@dkelkhoff Thank you for reporting this! Won't you mind contributing a test for this? We will be glad to merge it to master, and fix asap 😄  Thanks!

**Comment by mohanarpit** [comment]
@jmrozanec Came across this project via Hacktoberfest. Looks pretty interesting. Is it OK if I work on this? 

Also, I cloned the project and was trying to compile it locally via `mvn clean assembly:assembly -DdescriptorId=jar-with-dependencies` (as specified in the README). I get an error: 

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project cron-utils: Failed to create assembly: Error adding file-set for 'com.jakewharton.threetenabp:threetenabp:aar:1.0.5' to archive: Error adding archived file-set. PlexusIoResourceCollection not found for: ~/.m2/repository/com/jakewharton/threetenabp/threetenabp/1.0.5/threetenabp-1.0.5.aar: No such archiver: 'aar'. -> [Help 1]
[ERROR] 
`
I even checked out the .travis.yml file to see what the CI server is doing. But I couldn't really see any compilation command there. Additionally, I can see some answers on StackOverflow that recommend adding some build steps to the pom.xml file, but I wanted to ask, am I missing something basic? How do you compile, test & run this on your local machines?

**Comment by jmrozanec** [comment]
@mohanarpit Sure! Go ahead! For compiling, just use the standard mvn clean install: if that passes, the rest will be ok :smile: Thanks!

**Comment by jmrozanec** [comment]
@dkelkhoff @mohanarpit solved! Many thanks to @minidmnv! 😄
