### ISSUE TITLE
Last Day of Month Incorrect for nextExecution

### ISSUE THREAD

**Issue by kensipe** [jmrozanec/cron-utils#244]
I'll send in a test.

The follow cron:
    val cronString = "* 9 * * 1L"

on Oct 2, 2017, should result in Oct 31, but comes back as Oct 30

cron def:

  val cronDefinition: CronDefinition =
    CronDefinitionBuilder.defineCron()
      .withMinutes().and()
      .withHours().and()
      .withDayOfMonth()
      .supportsHash().supportsL().supportsW().and()
      .withMonth().and()
      .withDayOfWeek().withValidRange(0, 7).withMondayDoWValue(1).withIntMapping(7, 0) //we support non-standard non-zero-based numbers!
      .supportsHash().supportsL().supportsW().and()
      .withYear().optional().and()
      .matchDayOfWeekAndDayOfMonth() // the regular UNIX cron definition permits matching either DoW or DoM
      .instance()

**Comment by jmrozanec** [comment]
@kensipe thank you for reporting this. Will try to solve it asap!

**Comment by kensipe** [comment]
https://github.com/jmrozanec/cron-utils/pull/245

**Comment by kensipe** [comment]
I want my Halloween!!! :)

**Comment by jmrozanec** [comment]
@kensipe merged into master!

**Comment by kensipe** [comment]
@jmrozanec this is not a bug after I thought about it... the last element `1L` should be the last monday of the month which is Oct 30.    Could you revert the merge on the test?

**Comment by jmrozanec** [comment]
@kensipe Sure! We are glad it was so easy 😄  Best!

**Comment by syodage** [comment]
ha ha it was a good debugging practice for me, it should be "* 9 1L * *"  get the expected result (Oct 30)

**Comment by jmrozanec** [comment]
@syodage 😄
