### ISSUE TITLE
Most methods utilize definitions from threeten backport.

### ISSUE THREAD

**Issue by georgikoyrushki95** [jmrozanec/cron-utils#248]
Hello, 

I am trying to use your library for a project I am currently working on. In the examples repo you have provided, I see that the methods in cron-utils use classes from java.time. For me, however, it demands for definitions in the threeten back port. I can verify that I have a java 8 sdk. Is it possible that I might have installed the wrong package?

Thanks in advance for your help.

**Comment by jmrozanec** [comment]
@georgikoyrushki95 Hello! We migrated from JDK8 to Threeten, since the API is the same, but allows us to support Android with JDK7 (JDK8 is not fully supported for Android yet). We hope this is not much of an inconvenience. Feedback is appreciated! Thanks!
