### ISSUE TITLE
Bi-weekly schedule fails for Oct 2017

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#249]
Bi-weekly cron does not provide the correct next/previous execution time on Oct 2017. Please see test cases referenced below.

**Comment by pangyikhei** [comment]
The `testNextExecutionEveryTwoWeeksStartingWithFirstDayOfYear` test is not failing on my system.

With regards to the `testLastExecutionEveryTwoWeeksStartingWithFirstDayOfYearIssue249` test, here is a test that checks every day in 2017 (including Jan. 1) for the expected last execution.
The current test seems to expect the wrong date, as I detailed in the comment https://github.com/jmrozanec/cron-utils/commit/42f3d7290ebcf36fd01ebacddac3c1733ffb44c1#commitcomment-24913240

I added a branch to my fork (see https://github.com/pangyikhei/cron-utils/commit/ac4c8de1e1f1542c239997e41889178c29f16898) with some expanded test methods and lastExecution/nextExecution seem to be working for the biweekly schedule starting from the first day of the year.

**Comment by meincs** [comment]
fixed #249 see most recent pull request

**Comment by jmrozanec** [comment]
@pangyikhei @meincs Thank you! Merged!

**Comment by meincs** [comment]
@jmrozanec are there any plans for the next release? It would be very helpful if you could release a new version with this bug being fixed. TX

**Comment by jmrozanec** [comment]
@meincs sure! We can release a new version tomorrow! :smile

**Comment by jmrozanec** [comment]
@meincs Hi! We could not manage to perform a release yet - will be done within a day or two at most. Thanks!
