### ISSUE TITLE
NullPointerException with custom cronExpression without DaysOfMonth

### ISSUE THREAD

**Issue by michaelknigge** [jmrozanec/cron-utils#25]
Hi,

today I've played around with cron-utils but all my efforts to get it working as I expected failed....

I've tried to create a custom expression that contains just fields for "minute", "hour" and "dayOfWeek", so I can configure expressions like "every saturday and sunday at 18:00". But all I've got is a NPE. Her is what I've done:

      final CronDefinition cronDefinition =
              CronDefinitionBuilder.defineCron()
                  .withMinutes().and()
                  .withHours().and()
                  .withDayOfWeek().and()
                  .instance();

      // every monday at 18:00
      final String cronExpression = "0 18 1";

      final CronValidator validator = new CronValidator(cronDefinition);
      System.out.println("isValid:" + validator.isValid(cronExpression));

      final CronParser parser = new CronParser(cronDefinition);
      final Cron cron = parser.parse(cronExpression);

      final ExecutionTime executionTime = ExecutionTime.forCron(cron);

The last line throws an NPE:

    Exception in thread "main" java.lang.NullPointerException
	at com.cronutils.model.time.ExecutionTimeBuilder.validate(ExecutionTimeBuilder.java:114)
	at com.cronutils.model.time.ExecutionTimeBuilder.forDaysOfMonthMatching(ExecutionTimeBuilder.java:100)
	at com.cronutils.model.time.ExecutionTime.forCron(ExecutionTime.java:81)
	at mk.test.Main.testCronUtilsOwnDefinition(Main.java:49)
	at mk.test.Main.main(Main.java:21)

Is it a bug or did I make a mistake?

Thank you, Michael

**Comment by jmrozanec** [comment]
@michaelknigge This is a bug. Thank you for reporting.
Contributions are welcome!

**Comment by jmrozanec** [comment]
@michaelknigge Issue fixed!
