### ISSUE TITLE
invalid nextExecution time in overlap hour (end of dst)

### ISSUE THREAD

**Issue by jack-itb** [jmrozanec/cron-utils#253]
When getting the next execution time for a timezoned datetime, the call to ExecutionTime.nextExecution results in 
`java.lang.IllegalArgumentException: The end instant must be greater or equal to the start`
when it's called in the second overlap hour in the switch from DST to normal time.

Example:
```
ExecutionTime executionTime = null;

CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX);
CronParser parser = new CronParser(cronDefinition);
Cron unixCron = parser.parse("* * * * *");

executionTime = ExecutionTime.forCron(unixCron);

ZonedDateTime now = ZonedDateTime.of(2017, 10, 29, 2, 30, 0, 0, ZoneId.of("Europe/Berlin")).withLaterOffsetAtOverlap();
System.out.println(now);

System.out.println("now=" + now);
System.out.println("next exec time=" + executionTime.nextExecution(now));
if (executionTime.nextExecution(now).isBefore(now))
{
  System.out.println("next execution time before now!");
}
```

Result:
```
2017-10-29T02:30+01:00[Europe/Berlin]
now=2017-10-29T02:30+01:00[Europe/Berlin]
next exec time=2017-10-29T02:31+02:00[Europe/Berlin]
next execution time before now!
```

The problem seams to be the conversion of ZonedDateTime to LocalTime and back to ZonedDateTime in ExecutionTime.nextClosestMatch:
```
newDate =
        ZonedDateTime.of(LocalDateTime.of(date.getYear(), date.getMonthValue(),
                date.getDayOfMonth(), date.getHour(),
                date.getMinute(),0), date.getZone()).plusMinutes(nearestValue.getShifts());
```

Is the conversion necessary?
If it really is, then the new ZonedDateTime should at least get the same offset as the original ZonedDateTime?
```
newDate =
        ZonedDateTime.ofLocal(LocalDateTime.of(date.getYear(), date.getMonthValue(),
                date.getDayOfMonth(), date.getHour(),
                date.getMinute(),0), date.getZone(), date.getOffset()).plusMinutes(nearestValue.getShifts());
```

**Comment by jack-itb** [comment]
Sorry, I just saw that this seems to be fixed in release 6.x!
Could it possibly get backported to version 5.x or 4.x? I try to avoid to use the org.threeten.bp classes...

**Comment by jmrozanec** [comment]
@jack-itb we cannot promise a delivery right now. But if you port it and send a PR, we will do a release with it. Let us know if you require a branch and we will create it! Thanks!

**Comment by jmrozanec** [comment]
@jack-itb we have a new release (com.cronutils/cron-utils "7.0.0") avoiding the org.threeten.bp classes! Is now developed leveraging JDK8. Please let us know if we can close this issue!
