### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by tylergets** [jmrozanec/cron-utils#260]
We are currently using an older version of the library (3.1.0) in our Android application. Due to SDK/API Minimums, the latest version (7.0.0) will not work (Missing java.time, java.util.Optional, and Comparator functions) 

Is there a version/branch of this library that is supported by android? I see the android branch and issue #254 but am confused on the status. 

Thanks and great work on this library!

**Comment by jmrozanec** [comment]
@tylergets Thank you for reaching out! Before merging JDK8 support to master, we created release 6.0.5, which brings latest cron-utils features and still remains compatible with JDK7. Please check if that version works OK for Android!
We would like to maintain JDK8 on master from now on, but we understand there may be many Android versions not yet prepared for JDK8. If using release 6.0.5 in a future is not feasible (new features or bugfixes are required) we will update Android branch and perform 6.x.y releases from there, still compatible with JDK7.
Please let us know if this answers the question and if there is something else we can do for the Android community! 😄

**Comment by jmrozanec** [comment]
@tylergets we are closing this issue. Please feel free to continue the conversation or reach back at any time!
