### ISSUE TITLE
Convert cron string to ScheduleExpression

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#262]
A use case is described [here](https://stackoverflow.com/questions/46344453/how-to-convert-cron-string-to-scheduleexpression-in-java)
We could extend this functionality to provide not only [ScheduleExpression](https://docs.oracle.com/javaee/6/api/javax/ejb/ScheduleExpression.html) instances, but also instances for other schedulers.

**Comment by Naxos84** [comment]
This shouldn't be a big deal. The basics can be converted 1:1 to this ScheduleExpression.

I really would like to try this. But could you show me a place to start (to put the converter to) because i'm not very familiar with the whole project structure.

**Comment by jmrozanec** [comment]
@Naxos84 we agree. We may need to include the Java EE as Maven dependency with a "provided" scope so that we do not force transitivity.
