### ISSUE TITLE
Remove all internal use of deprecated constructors of Always and QuestionMark

### ISSUE THREAD

**Issue by SvenssonWeb** [jmrozanec/cron-utils#264]
Since a decision has been made to deprecate the internal constructor of Always and QuestionMark, all internal usage of these classes should go through inte new recommended implementation `FieldExpression.always()`

**Comment by Naxos84** [comment]
All unittests are completely missed. There the constructor of Always() and QuestionMark() are still used. Is that wanted?

**Comment by jmrozanec** [comment]
@Naxos84 You are welcome to update the deprecated usages and remove the deprecated constructors. Thanks!

**Comment by Naxos84** [comment]
Ok. I am going to do that in the next few days.

Am 17.11.2017 15:49 schrieb "jmrozanec" <notifications@github.com>:

**Comment by SvenssonWeb** [comment]
@Naxos84 I wasn't completely sure how the unit tests should be updated. Using the constructor could have been a valid case, so I left it as is. Thank you for reviewing the update.

**Comment by Naxos84** [comment]
I just updated my fork to remove the deprecated usage of always and questionmark but there are 3 unit tests that are failing. Is that a known issue?
Should I leave them as they are and just remove the usage of the deprecated classes or should I wait until those tests are fixed?

**Comment by SvenssonWeb** [comment]
Yes, this is a known issue. I came across it yesterday, and my fix moved the issue to today. Basically its a modulus issue in the test cases that causes them to fail every 14th day. I have a pull request up at #272

**Comment by SvenssonWeb** [comment]
If you run your tests tomorrow again they should be fine though ;)

**Comment by jmrozanec** [comment]
@Naxos84 @SvenssonWeb can we replicate those 3 tests with the specific date they were failing, and file an issue for this? Must be a bug, and even if happens once in a while, is still a bug 😄 
Perhaps we can upload the test commented, referencing the issue, so that the build wont fail, but we can grep them in the code when needed to fix the issue. Thanks!

**Comment by SvenssonWeb** [comment]
The updated test cases now tests all days under oktober 2017. So this issue is now covered in those tests.

**Comment by jmrozanec** [comment]
Great! Thanks!
