### ISSUE TITLE
Remove unused file SecondsDescriptor.java

### ISSUE THREAD

**Issue by SvenssonWeb** [jmrozanec/cron-utils#273]
[SecondsDescriptor.java](https://github.com/jmrozanec/cron-utils/blob/7a48b5ebc8b5e79bc4c83327f44649aa383e4269/src/main/java/com/cronutils/descriptor/refactor/SecondsDescriptor.java) is not used anywhere.
Is it going to be used in the future?

**Comment by jmrozanec** [comment]
@SvenssonWeb this is a WIP - part of the "enhanced-descriptions" milestone: we want to refactor how descriptions are provided, to reach a new quality level of them. Should not be removed.
