### ISSUE TITLE
Will throw NullpointerException

### ISSUE THREAD

**Issue by SvenssonWeb** [jmrozanec/cron-utils#274]
https://github.com/jmrozanec/cron-utils/blob/7a48b5ebc8b5e79bc4c83327f44649aa383e4269/src/main/java/com/cronutils/model/time/ExecutionTime.java#L196-L199

This piece of logic will always throw at `days.getValues().get(0)`, because `days` is never given a new value.

**Comment by SvenssonWeb** [comment]
I'm looking at rewriting larger parts of this method, and related private methods, to fix this as well as removing exceptions as control statements.

**Comment by Naxos84** [comment]
> because days is never given a new value.

When `years.isEmpty()`(Line 178) evaluates to `true` then days might have a value.

**Comment by SvenssonWeb** [comment]
Yes, but it always returns on line 185

**Comment by Naxos84** [comment]
True. Didn't see that.

Am 20.11.2017 09:47 schrieb "Fredrik Svensson" <notifications@github.com>:

**Comment by SvenssonWeb** [comment]
The code itself in never reached. That was kind of the issue.
If you run a code coverage for all test cases, that specific line of code is never accessed.

**Comment by jmrozanec** [comment]
@SvenssonWeb we are closing the issue.
