### ISSUE TITLE
Add support for "America/Punta_Arenas" timezone

### ISSUE THREAD

**Issue by pojaszek** [jmrozanec/cron-utils#280]
org.threeten.bp.ZoneId.of("org.threeten.bp.ZoneId") throws the below exception:
`Unknown time-zone ID: America/Punta_Arenas
org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: America/Punta_Arenas
	at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:178)`

**Comment by jmrozanec** [comment]
@pojaszek thank you for reporting this. Upgrading to version 7.0.0 does solve the issue? Thanks!

**Comment by pojaszek** [comment]
I think in version 7.0.0 you are using time classes from java 8, not from threetenbp, so that timezone is supported

**Comment by jmrozanec** [comment]
@pojaszek yes, that is right. Our question is whether you can migrate to 7.0.0 so that this issue no longer affects you. 
In any case, we will dig into this issue, provide a solution and release it.

**Comment by pojaszek** [comment]
I have just bumped lib & migrated to 7.0.0. No need to providing workaround in 6.x.x version.

Thanks

**Comment by jmrozanec** [comment]
@pojaszek great to hear that! 😄

**Comment by lodenrogue** [comment]
Can this be closed?

**Comment by jmrozanec** [comment]
@lodenrogue yes 😄 Thanks for reminding! 😄
