### ISSUE TITLE
Add sonarcloud

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#284]
Add [sonarcloud](https://sonarcloud.io/) to get additional reports about code quality.

**Comment by Naxos84** [comment]
You ca assign this to me in You like. There is just 1 step that you need to do yourself. That is: set a token in travis build Job.

**Comment by jmrozanec** [comment]
@Naxos84 thank you for encouraging the use of this tool! [Here we have the dashboard](https://sonarcloud.io/dashboard?id=cron-utils) reporting the first run!
