### ISSUE TITLE
Fix sonarcube issues.

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#285]
Provide fixes for issues detected at [sonarcube](https://sonarcloud.io/dashboard?id=cron-utils)
Our priorities are:
- bugs
- vulnerabilities
- smells

We aim to get an "A" in each of those categories.

**Comment by Naxos84** [comment]
Should the issues in unit tests also be fixed?
If not. Please consider configuring it properly.

**Comment by jmrozanec** [comment]
@Naxos84 is taking over this issue. We will be glad to merge the fixes into master! Thanks!

**Comment by SvenssonWeb** [comment]
A minor analysis of the issues shows that every file gets an error on the copy right disclaimer.
This should probably be fixed with configuration on sonar side.

**Comment by Naxos84** [comment]
I will also fix this. Because the copyright/license should be placed above
the package Definition!

Am 26.11.2017 17:22 schrieb "Fredrik Svensson" <notifications@github.com>:

**Comment by Naxos84** [comment]
See also: http://www.oracle.com/technetwork/java/codeconventions-141855.html

**Comment by jmrozanec** [comment]
@Naxos84 Issues at "test" should be fixed as well. But we should not perform coverage analysis over tests: this is something must be fixed with a configuration.

**Comment by Naxos84** [comment]
@jmrozanec I'm not sure what you (exactly) mean by that.

**Comment by Naxos84** [comment]
This is mostly done. Basic sonarcloud is achieved.
All issues are fixed so that we have an A-rating.

So I think this issue can be closed.

**Comment by jmrozanec** [comment]
@Naxos84 thanks!
