### ISSUE TITLE
Bad last execution time

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#289]
A test is provided at class Issue143Test.

**Comment by jpotts2** [comment]
@jmrozanec,

I am not sure that the expected date in testCase3 on line 76 is correct.

Cron in this test:

`0 0 12 31 1/1 ? *

Quarts docs:
http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

While the test asserts 2015-12-31 at 12:00 noon, the actual result is 2016-10-31 at 12:00 noon. Given the starting date of 2016-12-20, I think the actual result is correct.

**Comment by jpotts2** [comment]
Created a pull request: #295

**Comment by jmrozanec** [comment]
@jpotts2 Merged! Thanks!
