### ISSUE TITLE
Week days are not recognized

### ISSUE THREAD

**Issue by sparklton** [jmrozanec/cron-utils#29]
The following fails as invalid cron expression:
<code>
CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
ExecutionTime executionTime = ExecutionTime.forCron(parser.parse("0 0 3 ? * SAT"));
</code>

Throws <b>java.lang.IllegalArgumentException: Invalid value. Expected some integer, found SAT</b>

The expression was actually taken from working quartz 2.2.1 based system.

**Comment by jmrozanec** [comment]
@sparklton thank you for reporting this. This is similar to the issue reported at #27 
We built a fix for it, and handles the case you describe. As soon as we get some more issues fixed, we will release a new version. If you need this fix urgently, please ping back, and we can do a minor release with this fix only.

**Comment by jmrozanec** [comment]
@sparklton [Version 3.1.0](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.0) was released including this fix.
