### ISSUE TITLE
Custom Def with 3 required fields behaves oddly

### ISSUE THREAD

**Issue by charleshope** [jmrozanec/cron-utils#291]
Creating a custom CronDefinition with only 3 required fields is legal to instantiate, but the parser considers an expression with 4 fields as an error:

> java.lang.IllegalArgumentException: Cron expression contains 4 parts but we expect one of [6, 7]

Test case in  #292

**Comment by jmrozanec** [comment]
@charleshope Thank you for reporting this!

**Comment by minidmnv** [comment]
My commit didn't close this issue already?

**Comment by jmrozanec** [comment]
@minidmnv yes! We apologize for not closing the issue. The feature was released yesterday. Thanks!
