### ISSUE TITLE
Expressions are not comparable objects, no implementation of equals & hashcode

### ISSUE THREAD

**Issue by rhanton** [jmrozanec/cron-utils#297]
I'm working on a system where I'm using cron-utils to simplify the creation/manipulation of a series of scheduled time periods, so I have a Cron that represents the start of all related periods and another Cron that represents the end of those periods. This is becoming somewhat challenging because I cannot easily verify that one field expression = another field expression using .equals(). Could we please implement equals and hashCode methods where it makes sense?

**Comment by jmrozanec** [comment]
@rhanton thank you for reporting this. May we ask you to provide some test cases highlighting the use case? Thanks!

**Comment by jmrozanec** [comment]
@rhanton we are closing the issue due to inactivity. Thanks!

**Comment by francisdb** [comment]
Try this:

```scala
val cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ)
val parser         = new CronParser(cronDefinition)
parser.parse("0 10 0 ? * *") must be equalTo parser.parse("0 10 0 ? * *")
```

I did however see this `equivalent()` method but I see no reason to not have an equals where all fields are just compared?
