### ISSUE TITLE
ExecutionTime.lastExecution doesn't work

### ISSUE THREAD

**Issue by sparklton** [jmrozanec/cron-utils#30]
The following test case fails:

    DateTime now = DateTime.now();
    CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
    ExecutionTime executionTime = ExecutionTime.forCron(parser.parse("0 0 3 ? * 6"));
    DateTime last = executionTime.lastExecution(now);
    DateTime next = executionTime.nextExecution(now);
    Assert.assertNotEquals(last, next);

I expected the <b>last</b> to be "3 AM of the nearest Saturday looking past from now" and <b>next</b> to be "3 AM of the nearest Saturday looking forward". Am I wrong with my expectations?

**Comment by jmrozanec** [comment]
@sparklton you are right. This issue is very similar to the #26 we are working on. Will keep you updated about progress. Help and ideas are welcome! Thank you for reporting the issue.

**Comment by jmrozanec** [comment]
@sparklton Issue fixed! Thank you for reporting this!
