### ISSUE TITLE
Get proper status when building PRs

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#302]
Currently, we do not get proper build status on PRs, making it difficult to oversee the build status we will get once we merge the PR.
@Naxos84 pointed out some plugins that may help with sonarqube:
- [github-plugin](https://docs.sonarqube.org/display/PLUG/GitHub+Plugin)
- [multi-language-project](https://www.sonarqube.org/?id=test%253Amulti-language-project)

**Comment by Naxos84** [comment]
The thing about the build job is that the used sonar-scanner command is not available for PR's.
But as it can be seen [here](https://github.com/bellingard/sample_multi-language-project) it is possible to integrate sonarcloud analysis the same way as it is done with codacy. Also PR's can be analysed with this.
