### ISSUE TITLE
Android API below 24 Throws java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by L4grange** [jmrozanec/cron-utils#309]
Hello guys. First I want to thank you for this great library!

I'm building a mobile app with heavy cron manipulation and this library has helped a ton, doing all the parsing automatically. The library works great on android 6+ (using release 6.0.5 since I need to support Android versions 4.2+)

However, on android 4 and 5, the CronParser throws an exception in the constructor when calling `buildPossibleExpressions(cronDefinition);` due to the fact that in Android API below 24  the method `List.sort()` does not exist. Is there any version fo the library that works with API below 24, or I should download the library and manually make some changes to get it up and running on older android versions? Thank you!

P.S.: If you need a stack trace let me know, but the crash is really simple. The constructor crashes when calling `sortedExpression.sort(CronParserField.createFieldTypeComparator());` because the sort method was added after android API 24.

**Comment by jmrozanec** [comment]
@L4grange thank you for reporting this! We are glad the library is useful to you! 😄  Reviewing the versions, you may find version 6.0.2 fits your needs. Please let us know if works :) Best!

**Comment by L4grange** [comment]
Thank you for your suggestion! Unfortunately when using version 6.0.2 I cannot build the project since grade is giving me the following error:

`
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'org/threeten/bp/format/ChronologyText.properties'
`

I have not been able to resolve this yet, and the only version I can successfully build with is 6.0.4 and up which do not contain the duplicate files. Any other suggestions?

**Comment by jmrozanec** [comment]
@L4grange we have no other suggestions. Perhaps you can download manually and make some changes? In that case, we would be glad to merge the changes in a branch and perform a new 6.x.y release, so that the whole community would benefit from it.

**Comment by L4grange** [comment]
Thank you, I'll take a look on Monday and let you know if I have any luck!

**Comment by L4grange** [comment]
Unfortunately, I was not able to import the library as a standalone module in my Android Project, but I created a Class named AndroidCronParser to do a simple modification to get cron-utils v6.0.5 working on Android 4+:

I simply replaced the line `sortedExpression.sort(CronParserField.createFieldTypeComparator());` with:
`
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
			sortedExpression.sort(CronParserField.createFieldTypeComparator());
		} else {
			Collections.sort(sortedExpression, CronParserField.createFieldTypeComparator());
		}
`

in the `CronParser.java` file in the `buildPossibleExpressions(CronDefinition cronDefinition)` method.

The fix is working on my simulator tests, I will continue testing as I develop my app and let you know if I find any more compatibility issues.

If I ever get the library running as a standalone module I will create a PR for this change. Thank you for help, your time, and this great library!

**Comment by jmrozanec** [comment]
@L4grange Thanks! If you send us a PR, we will be glad to perform a release with it! Thank you for the update! 😄

**Comment by tylergets** [comment]
I submitted PR #326 to get started on fixing this issue.

**Comment by jmrozanec** [comment]
Merged!
