### ISSUE TITLE
Valid Quartz expression fails validation

### ISSUE THREAD

**Issue by Paqrat76** [jmrozanec/cron-utils#31]
Using the samples on http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger, the expression "0 10,44 14 ? 3 WED" fails validation using the isValid(...) method (for CronType.QUARTZ).  The Cron-utils README indicates that the "?" is currently replaced with "*", and that renders the otherwise valid expression invalid. The same is true for "0 0 12 ? * SUN-SAT".

**Comment by jmrozanec** [comment]
@Paqrat76 thank you for reporting this. Will try to fix the issue as soon as possible. Contributions are welcome!

**Comment by jmrozanec** [comment]
@Paqrat76 Issue fixed!

**Comment by jmrozanec** [comment]
@Paqrat76 [Version 3.0.1](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.0) was released including this fix.
