### ISSUE TITLE
Handle CRON expression that will never be true

### ISSUE THREAD

**Issue by alenkacz** [jmrozanec/cron-utils#310]
The library incorrectly handles e.g. this cron expression "0 0 31 2 *" (31.2. which will never be true). What happens when you try to compute the nextExecution for such expression is:
ExecutionTime.nextExecution ends up in an infinite loop incrementing year over and over...

As a solution I propose following:
- add validation for these cases in CronConstraintsFactory
- handle this infinite loop in ExecutionTime (e.g. by giving up when reaching a dat that's 100 years from now?)

I have the validation already implemented so I'll follow up with a PR.
If you agree, I'll also add the fix to the ExecutionTime class.

**Comment by jmrozanec** [comment]
@alenkacz Hi! Thank you for reporting this! We will be glad to merge the fix if you send us the PR! We look forward to it! 😄

**Comment by kensipe** [comment]
@jmrozanec we have a scala solution here:  https://github.com/dcos/metronome/pull/202
It good to connect again!  

Alena is working on a patch for cron-utils now... 
@alenkacz love the idea of a max iterations which would prevent issues for anything else not covered!

**Comment by jmrozanec** [comment]
@kensipe great to connect again! Thank you for the insight! When merged, you can soon expect a new release with the fix. Thanks!

**Comment by alenkacz** [comment]
@jmrozanec I will still follow up with the validation code in next days...

**Comment by jmrozanec** [comment]
@alenkacz Thanks!

**Comment by jmrozanec** [comment]
@alenkacz do we have any updates on this?

**Comment by alenkacz** [comment]
I'll do it this week, but feel free to keep it closed :)

**Comment by jmrozanec** [comment]
@alenkacz thanks!

**Comment by jmrozanec** [comment]
@alenkacz @kensipe release 7.0.2 is now available! Thank you for contributing to cron-utils!
