### ISSUE TITLE
lastExecution method works unexpectedly

### ISSUE THREAD

**Issue by dmitrijs-rjazanovs** [jmrozanec/cron-utils#312]
We have configured quartz2 batch job with following cron: 0 0 20 * * ? * so every day at 20:00.
Our batch job must take some data 1 day before from 20:00. As long as we are not sure that job will triggers in exactly 20:00, we also trying to parse this cron job with following aproach:
ExecutionTime.forCron(quartzCron).lastExecution(ZonedDateTime.now()).get().toLocalDateTime();
I expect that lastExecution will return current date with exactly 20:00, but it returns yesterday 20:00

As workaround works thread.sleep(2000) before lastExecution method, which is weird, because we are feeding parser with ZonedDateTime.now() method

**Comment by jmrozanec** [comment]
@dmitrijs-rjazanovs thank you for reporting this. May we ask for a test, reproducing the issue? We shall find another way to solve the bug rather than using a thread.sleep. You are welcome to help us find a solution for this! Thanks!

**Comment by jmrozanec** [comment]
@pangyikhei sure! We will test and merge it into master. If works, we close the issue. Thanks! :smile:
