### ISSUE TITLE
release 7.0.1: Serialization of com.cronutils.model.Cron instances broken because of javax.ejb.ScheduleExpression dependency with wrong scope

### ISSUE THREAD

**Issue by toby1984** [jmrozanec/cron-utils#314]
The pom.xml declares dependency with scope 'provided' , so using the artifact in another project will not pull in the J2EE API jar.

**Comment by jmrozanec** [comment]
@toby1984 thank you for reporting this! Will work on this and reach back. Thanks!

**Comment by toby1984** [comment]
Sorry, I just now realized that you're intentionally using J2EE because of issue 262 and that the J2EE API dependency was never a part of the regular JDK... so this issue is not related to JDK.

I guess you should just update the README file and state that the J2EE dependency is required during runtime when using reflection.

**Comment by jmrozanec** [comment]
@toby1984 we updated the README.md. But we agree the underlying issue would be if we can keep Cron instance serializable. Is this possible or shall we work towards a solution for it?

**Comment by jmrozanec** [comment]
@toby1984 we just refactored the code in order to make Cron serializable in every case, without the J2EE dependency. Thank you for pointing it out!

**Comment by toby1984** [comment]
Thank you guys, you're doing a great job !

**Comment by jmrozanec** [comment]
@toby1984 thanks! :smile

**Comment by jmrozanec** [comment]
@toby1984 release 7.0.2 is now available! Thank you for contributing to cron-utils!
