### ISSUE TITLE
CronBuilder withDoW using Quartz syntax is off by one

### ISSUE THREAD

**Issue by roddy** [jmrozanec/cron-utils#315]
I tried to write a cron using the `CronBuilder` that modelled the idea of "every Friday at 12:00." I'm using Quartz syntax. Since I couldn't find an example anywhere for `withDoW`, I muddled about until I got this:

```java
CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
CronBuilder builder = CronBuilder.cron(cronDefinition)
                                 .withYear(always())
                                 .withMonth(always())
                                 .withDoW(on(Weekdays.FRIDAY.getWeekday()))
                                 .withDoM(questionMark())
                                 .withHour(on(12))
                                 .withMinute(on(0))
                                 .withSecond(on(0));

Cron cron = builder.instance();
String result = cron.asString();
```

The result is *almost* right -- it results in `0 0 12 ? * 5 *`. Unfortunately, "5" is Thursday in Quartz, not Friday, since Quartz sets 1 to Sunday and 7 to Saturday.

I *think* this is coming from my use of the `Weekdays.FRIDAY.getWeekday()` to set the day of week, but to be honest I was unable to find any other way of setting the day of week using the actual enum value instead of an integer. (`getWeekday` is off by one.) 

The Quartz cron definition itself correctly indicates that Monday is "2" and that the valid values are "1-7".  The only way I could figure to get this done by poking about in the source is to use something like this:

````java
builder.withDoW(on(ConstantsMapper.weekDayMapping(ConstantsMapper.CRONTAB_WEEK_DAY, ConstantsMapper.QUARTZ_WEEK_DAY, Weekdays.FRIDAY.getWeekday()))
````

This just seems ... really nasty and unintuitive. And it means if I switch out the underlying CronDefinition to use something else, I'll need to change it in two places, first in the definition itself, and then a second time down here in the 'mapping'.

**Is this the only way to set the day of week on the builder outside of using raw integers and effectively tying yourself to a particular flavor of cron syntax?**

(I wasn't able to find anything in the examples project or documentation that cover setting day of week.)

This might be related to https://github.com/jmrozanec/cron-utils/issues/103, but I got confused as to what it was talking about (and it appeared to be talking about the Parser, not the Builder).

As a side note, when asking it to describe the cron, it correctly identifies it as "Thursday", even if the rest of the "English" is ... rather awkward:

```java
CronDescriptor descriptor = CronDescriptor.instance(Locale.US);
String describe = descriptor.describe(cron);
System.out.println(describe); // "at 12:00 at Thursday day"
```

**Comment by jmrozanec** [comment]
@roddy Thank you for reporting this. This is a bug 😄 When you define a Quartz cron expression, it also contains the weekdays mapping: (see the `withMondayDoWValue()`)

    CronDefinitionBuilder.defineCron()
                .withSeconds().and()
                .withMinutes().and()
                .withHours().and()
                .withDayOfMonth().supportsL().supportsW().supportsLW().supportsQuestionMark().and()
                .withMonth().and()
                .withDayOfWeek().withValidRange(1, 7).withMondayDoWValue(2).supportsHash().supportsL().supportsQuestionMark().and()
                .withYear().withValidRange(1970, 2099).optional().and()
                .withCronValidation(CronConstraintsFactory.ensureEitherDayOfWeekOrDayOfMonth())
                .instance();

That is why correctly identifies the DoW when mapping to a description, but there is something wrong when generating the cron expression. You are welcome to submit a test for this issue and help us fix it!

The descriptions are definitely something we want to improve. Up to now, we prioritized features that would make cron-utils a great library to operate with all crons; but will soon focus on the description feature again. Descriptions feature requires a careful design in order to provide enough flexibility to accurately describe the pattern across different languages.

**Comment by jmrozanec** [comment]
@roddy we developed a solution for this case and will be glad to receive your input before closing the issue. From now on, you would be able to specify proper DoW values using the following expressions:

        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
        CronBuilder builder = CronBuilder.cron(cronDefinition)
                .withYear(always())
                .withMonth(always())
                .withDoW(on(Weekdays.FRIDAY.getWeekday(cronDefinition)))
                .withDoM(questionMark())
                .withHour(on(12))
                .withMinute(on(0))
                .withSecond(on(0));

When providing the cron definition to the Weekdays.getWeekday method, it will figure out the proper value to be used.

**Comment by roddy** [comment]
This is a great solution! Since it relies on the same CronDefinition, I can switch out the backing syntax just by adjusting the definition in one place.

Quick turnaround too -- nicely done. :grinning:

**Comment by jmrozanec** [comment]
@roddy release 7.0.2 is now available! Thank you for contributing to cron-utils!
