### ISSUE TITLE
Updated dutch translation

### ISSUE THREAD

**Issue by MrKuip** [jmrozanec/cron-utils#316]
I have updated the dutch translation. 
I hope you can include it in one of the next releases.

[CronUtilsI18N_nl.zip](https://github.com/jmrozanec/cron-utils/files/1806856/CronUtilsI18N_nl.zip)

**Comment by jmrozanec** [comment]
@MrKuip Thank you for sending an enhancement to the Dutch translation! We will merge it by EOD. You can expect a new release with it by end of month. Best!

**Comment by jmrozanec** [comment]
@MrKuip fixed! Thanks!

**Comment by jmrozanec** [comment]
@MrKuip release 7.0.2 is now available! Thank you for contributing to cron-utils!
