### ISSUE TITLE
cron-utils.log appears on its own

### ISSUE THREAD

**Issue by morvael** [jmrozanec/cron-utils#317]
I have only attached cron-utils as a compile dependency in Maven project, and after building that project ".\target\cron-utils.log" file appears in project directory. Why is that?

**Comment by jmrozanec** [comment]
@morvael thank you for reporting this. We should change the logging appender, based on context so that the default would be logging into a console and not a file. Will work on fixing it. Best!

**Comment by jmrozanec** [comment]
@morvael Fixed! Thanks for pointing this out!

**Comment by morvael** [comment]
What amazed me was the fact that I have only added a dependency, didn't use any code, and it appeared during _only_ compilation :) Something from cron-utils pom that runs triggers it?

**Comment by jmrozanec** [comment]
@morvael not sure - perhaps on how dependencies are managed. We removed the logging settings that route it into a file, since are no longer needed, and that also solves the issue.

**Comment by jmrozanec** [comment]
@morvael release 7.0.2 is now available! Thank you for contributing to cron-utils!
