### ISSUE TITLE
ExecutionTime.previousClosestMatch(2018-03-26T01:59:59+02:00[Europe/Berlin]) goes into endless loop due daylight savings change

### ISSUE THREAD

**Issue by cbgxhub** [jmrozanec/cron-utils#319]
ExecutionTime.previousClosestMatch(2018-03-26T01:59:59+02:00[Europe/Berlin]) goes into endless loop due to daylight savings Change (At 2am)

Problem is reproducable on Unix and Win7 in TimeZone 'Berlin';

I used:
        <dependency>
           <groupId>com.cronutils</groupId>
           <artifactId>cron-utils</artifactId>
           <version>7.0.1</version>
        </dependency>

ExecutionTime.previousClosestMatch(final ZonedDateTime date)
2018-03-26T01:59:59+02:00[Europe/Berlin]
ExecutionTimeResult{time=2018-03-25T03:00+02:00[Europe/Berlin], isMatch=false}
ExecutionTimeResult{time=2018-03-25T03:00+02:00[Europe/Berlin], isMatch=false}
ExecutionTimeResult{time=2018-03-25T03:00+02:00[Europe/Berlin], isMatch=false}

in:
    private ZonedDateTime previousClosestMatch(final ZonedDateTime date) throws NoSuchValueException {
        ExecutionTimeResult result = new ExecutionTimeResult(date, false);
        do {
            result = potentialPreviousClosestMatch(result.getTime());
        } while (!result.isMatch());
        return result.getTime();
    }

**Comment by jmrozanec** [comment]
@cbgxhub thank you for reporting this! May we ask for a PR with the corresponding test? Thanks!

**Comment by cbgxhub** [comment]
Hi jmrozanec,

The email that you sent me is corrupt, please use my previous description for PR.

Here Test Code to reproduce the problem:
Please note that this code/Junit test will hang at ‘2018-03-25T02:00’ !!

            CronParser cronparser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX));

            @Test
            // Daylightsaving change in EU is - 2018-03-25T02:00
            // - Bug319: endless loop/fails/hangs at 2018-03-25T02:00 and 2018-03-26T02:00
            public void testPreviousClosestMatchDailightSavingsChangeBug319_loop() throws NoSuchValueException {
                        for (int month = 1; month < 13; month++) {
                                   for (int day = 1; day < 29; day++) {
                                               ZonedDateTime date = ZonedDateTime.of(2018, month, day, 2, 00, 00, 0, ZoneId.of("Europe/Berlin"));
                                               System.out.print(date);
                                               Cron cron = cronparser.parse("00 02 * * * ");
                                               ExecutionTime exectime = ExecutionTime.forCron(cron);
                                               ZonedDateTime lastrun = exectime.lastExecution(date).get();
                                               System.out.println("-ok");
                                   }
                        }
            }

Thanks,
Regards,
Cbgxhub


Von: jmrozanec [mailto:notifications@github.com]
Gesendet: Montag, 26. März 2018 14:54
An: jmrozanec/cron-utils
Cc: Bolterauer, Christian (Allianz Deutschland, externer Mitarbeiter); Mention
Betreff: [NEWSLETTER] Re: [jmrozanec/cron-utils] ExecutionTime.previousClosestMatch(2018-03-26T01:59:59+02:00[Europe/Berlin]) goes into endless loop due daylight savings change (#319)

Diese Nachricht enthielt potentiell unsichere
HTML Skripte. Diese wurden entfernt.
Die Nachricht kann nun gelesen, geoeffnet oder
bearbeitet werden.

===================================================

This message contained potentially unsafe HTML script
code that was removed.
Now you can safely view, open or edit this message.

@cbgxhub<https://github.com/cbgxhub> thank you for reporting this! May we ask for a PR with the corresponding test? Thanks!

**Comment by jmrozanec** [comment]
@cbgxhub Thanks! Will merge the test into master and comment the test annotation to avoid running until the issue is fixed.

**Comment by pkoenig10** [comment]
I have also hit this issue multiple times. Ideally cronutils would have iteration limits to prevent infinite loops. Exceptions can be handled but infinite loops can cause pretty serious issues, especially since many cronutils methods cannot be interrupted.

**Comment by jmrozanec** [comment]
@pkoenig10 this is a good suggestion. Will try to implement over the week and release a new version with the quick-fix. Thanks! 😄
