### ISSUE TITLE
Buggy Descriptor: Throwing ArrayIndexOutOfBoundsException and UnknownFormatConversionExceptions

### ISSUE THREAD

**Issue by rkkoszewski** [jmrozanec/cron-utils#32]
Hello, is it a known issue that the descriptor is throwing weird formatting and array exceptions?

This is my code:
```java
try{
String cronExpr = "% HERE CRON EXPRESSION %";
  CronDefinition cronDefinition =  CronDefinitionBuilder.instanceDefinitionFor(CronType.CRON4J);
  CronParser parser = new CronParser(cronDefinition);
  CronDescriptor descriptor = CronDescriptor.instance(Locale.UK);
  descriptor.describe(parser.parse(cronExpr)
}catch(Exception e){
		e.printStackTrace();
}
```

When I use:
__* 1,2,3,4,5,6 * 1,2,3 *__
I get:
__java.lang.ArrayIndexOutOfBoundsException: 1__

When I use:
__* 1 1,2 * 4__
I get:
__java.util.UnknownFormatConversionException: Conversion = 'p'__

Both examples return TRUE while validation.

More info:
CronType.CRON4J and CronType.UNIX has the same bug.
CronUtils 3.0 and 2.0 has the same bug.

I have htime-1.0, joda-time-2.4, guava-18.0, commons-lang3-3.4 in the classpath.

Could somebody try to replicate the issue?

**Comment by jmrozanec** [comment]
@rkkoszewski thank you for reporting this. I was able to reproduce the issue. Will upload the corresponding tests soon. You are welcome to contribute a fix!

**Comment by jmrozanec** [comment]
@rkkoszewski Issue fixed. Thank you for reporting this!

**Comment by jmrozanec** [comment]
@rkkoszewski [Version 3.0.1](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.0) was released including this fix.
