### ISSUE TITLE
quartz cron convert to spring schedule cron

### ISSUE THREAD

**Issue by kangtajt007** [jmrozanec/cron-utils#320]
That's a wonderful project, but I met some problem: we use spring schedule in our project.
When we use the cron-utils builder a cron expression， it seems to be the format of quartz which is 7 units，but we need the spring schedule format which is 6 units. How to resolve it?
  Thanks very much!

**Comment by jmrozanec** [comment]
@kandatajt007 this snippet may solve the issue:

    CronDefinitionBuilder.defineCron()
                .withSeconds().and()
                .withMinutes().and()
                .withHours().and()
                .withDayOfMonth().supportsL().supportsW().supportsLW().supportsQuestionMark().and()
                .withMonth().and()
                .withDayOfWeek().withValidRange(1, 7).withMondayDoWValue(2).supportsHash().supportsL().supportsQuestionMark().and()
                .withCronValidation(CronConstraintsFactory.ensureEitherDayOfWeekOrDayOfMonth())
                .instance();

Please let us know if was useful! Best!

**Comment by kangtajt007** [comment]
@jmrozanec  Thks  a lot, This is very useful for us. We test with those code.
```java
@Test
    public void testSpringSchedule(){
    	CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
    			.withSeconds().and()
    			.withMinutes().and()
    			.withHours().and()
    			.withDayOfMonth().supportsL().supportsW().supportsLW().supportsQuestionMark().and()
    			.withMonth().and()
    			.withDayOfWeek().withValidRange(1, 7).withMondayDoWValue(2).supportsHash().supportsL().supportsQuestionMark().and()
    			.withCronValidation(CronConstraintsFactory.ensureEitherDayOfWeekOrDayOfMonth())
    			.instance();

    	CronBuilder builder = CronBuilder.cron(cronDefinition)
    			.withMonth(always())
    			.withDoW(questionMark())
    			.withDoM(always())
    			.withHour(always())
    			.withMinute(every(on(0), 5))
    			.withSecond(always());

    	Cron cron = builder.instance();
    	String result = cron.asString();

    	assertEquals("* 0/5 * * * ?", result);
    }
```

**Comment by jmrozanec** [comment]
@kangtajt007 Thanks! Next release will include this definition along with the quartz() and unix() 😄 Best!

**Comment by jmrozanec** [comment]
@kangtajt007 release 7.0.2 is now available! Thank you for contributing to cron-utils!
