### ISSUE TITLE
Log4j root logger level

### ISSUE THREAD

**Issue by jpnffigueiredo** [jmrozanec/cron-utils#325]
Hi,

Why do you use log4j.rootLogger=DEBUG ... ? Using your lib in other applications is affecting existing logging configurations.

Can you consider use something like this:
``
log4j.category.com.cronutils=DEBUG, stdout
``

Or even this:
``
log4j.category.com.cronutils=INFO, stdout
``

**Comment by jmrozanec** [comment]
@jpnffigueiredo thank you for reporting this. Will fix soon and include in the next release. Thanks!

**Comment by jmrozanec** [comment]
@jpnffigueiredo Fixed! Thank you for reporting this!
