### ISSUE TITLE
System messages need to be differentiated

### ISSUE THREAD

**Issue by lukas1984** [jmrozanec/cron-utils#327]
System messages like "at" can be translated in multiple ways, depending on each language's grammar.

For example, in Italian:
"at 6:00" -> "alle 6:00"
"at 10 minutes" -> "al minuto 10"

Currently it is not possible to correctly translate, because there is only one "at" message. There should be one for each case.

**Comment by jmrozanec** [comment]
@lukas1984 thanks for pointing this out! We are working on it with some neural translation models. We hope this will provide us better translations. Will post some code soon. Thanks!

**Comment by jmrozanec** [comment]
@lukas1984 this issue will be handled as part of #3 Will be closing this for now. You are welcome to help us generate descriptions in order to come up with good models for translation into Italian language! 😄
