### ISSUE TITLE
Manifest classpath, maven dep and compiling with -Werror results in failure

### ISSUE THREAD

**Issue by kyleboyle** [jmrozanec/cron-utils#331]
Using maven dep com/cronutils/cron-utils/7.0.2/cron-utils-7.0.2.jar

warning: [path] bad path element "~/.m2/repository/com/cronutils/cron-utils/7.0.2/slf4j-api-1.7.12.jar": no such file or directory
error: warnings found and -Werror specified
[total 81ms]
1 error
1 warning

Please remove `Class-Path: slf4j-api-1.7.12.jar` from `META-INF/MANIFEST.MF`

**Comment by jmrozanec** [comment]
@kyleboyle thank you for reporting this! Will solve and release a new version asap. Thanks! 😄

**Comment by jmrozanec** [comment]
@kyleboyle should be solved now! Thanks!
