### ISSUE TITLE
Infinite loop when daylight savings time starts at midnight

### ISSUE THREAD

**Issue by pkoenig10** [jmrozanec/cron-utils#332]
The following test will infinite loop:
```
@Test
public void testIsMatchDailightSavingsChange_loop() {
    CronParser cronparser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX));
    ZonedDateTime date = ZonedDateTime.of(2018, 8, 12, 3, 0, 0, 0, ZoneId.of("America/Santiago"));
    Cron cron = cronparser.parse("0 6 * * *");
    ExecutionTime exectime = ExecutionTime.forCron(cron);
    exectime.isMatch(date);
}
```

When the given date is:
`2018-08-12T01:59:59-03:00[America/Santiago]`

This line repeatedly returns the given date, resulting in an infinite loop:
https://github.com/jmrozanec/cron-utils/blob/7.0.2/src/main/java/com/cronutils/model/time/SingleExecutionTime.java#L415

The evaluation sequence looks like:
```
newDate = date // 2018-08-12T01:59:59
newDate = newDate.truncatedTo(DAYS) // 2018-08-12T01:00:00 (because there is no 0th hour)
newDate = newDate. plusDays(1) // 2018-08-13T01:00:00
newDate = newDate. minusSeconds(1) // 2018-08-13T00:59:59
newDate = newDate. minusDays(1) // 2018-08-12T01:59:59 (because 0:59:59 is really 1:59:59)
```

Having both `plusDays` and `minusDays` causes unintuitive behavior due to the local time resolution in the `minusDays` call.

**Comment by jmrozanec** [comment]
@pkoenig10 thank you for contributing to cron-utils! The PR was merged and a new version released! :smile:
