### ISSUE TITLE
Better descriptions

### ISSUE THREAD

**Issue by wesoos** [jmrozanec/cron-utils#335]
Hello, is there a timeline for the better descriptions milestone?

**Comment by jmrozanec** [comment]
@wesoos thank you for reaching out. Our main blocker is how to load a Keras model on Java - any help regarding that is welcome! If solved, we would roll out first enhanced descriptions asap. No timeline is provided by now due to that issue. Thanks!

**Comment by wesoos** [comment]
Hi, I don’t anything about Keras.  I found this, which I’m sure you have also…

https://deeplearning4j.org/


Thanks
Wessel Oosthuizen

________________________________

**Comment by jmrozanec** [comment]
Hi! Yes, we saw that :smile: Perhaps we can port the model to that library and retrain using [this](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/EncoderDecoderLSTM.java) as an example. Thanks!
