### ISSUE TITLE
problems with every day of week

### ISSUE THREAD

**Issue by chirag100366** [jmrozanec/cron-utils#336]
I have a Unix cron string like "* * * * */3", which I expect to mean "At every minute on every 3rd day-of-week". That is, every Wednesday and Saturday(3rd and 6th day of a week). But I am seeing unexpected behaviour for describe(cron) , as well as  nextExecution() method.

  
```
@Test
public void testEveryDayPerWeek () { 
CronParser cronParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX));
String cronString="* * * * */3";
Cron cron=cronParser.parse(cronString);
System.out.print(CronDescriptor.instance().describe(cron));
ExecutionTime executionTime=ExecutionTime.forCron(cron);
Optional<ZonedDateTime> nextExecution = executionTime
                .nextExecution(ZonedDateTime.of(2018, 2, 8, 0, 0, 0, 0, ZoneId.of("UTC")));
        Assert.assertEquals(nextExecution.get(),ZonedDateTime.of(2018, 2, 10, 0, 0, 0, 0, ZoneId.of("UTC")));
    }
```

Output:
```
every minute every Wednesday days
java.lang.AssertionError: 
Expected :2018-02-10T00:00Z[UTC]
Actual   :2018-03-03T00:00Z[UTC]
```

**Comment by jmrozanec** [comment]
@chirag100366 thank you for reporting this. May we ask you for a PR with the test for the issue? Thanks!

**Comment by pangyikhei** [comment]
I'll work on this one. Should `*/3` include Sunday?

From https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/deployment_guide/ch-autotasks

> The forward slash (/) can be used to specify step values. The value of an integer can be skipped within a range by following the range with /<integer>. For example, 0-59/2 can be used to define every other minute in the minute field. Step values can also be used with an asterisk. For instance, the value */3 can be used in the month field to run the job every third month.

I checked with some other online cron generators and they seem to start with the "first" value when using `/`

So every third month would be Jan (1), Apr (4), Jul (7), etc.
Assuming the week starts on Sunday, every third day of the week would be Sunday, Wednesday, Saturday

**Comment by chirag100366** [comment]
Yes, I think */3 should include Sunday.

**Comment by jmrozanec** [comment]
@chirag100366 fixed! Kudos to @pangyikhei!
