### ISSUE TITLE
Incorrect handling of day-of-week range which crosses last day of week boundary

### ISSUE THREAD

**Issue by ctonsing** [jmrozanec/cron-utils#340]
When using a schedule definition which contains a day-of-week range which crosses the last-day-of-week boundary, then when we call ExecutionTime.timeFromLastExecution(ZonedDateTime date) method, it goes into a long-running loop and doesn't find the last execution time. The problem seems to be in the com.cronutils.model.time.generator.BetweenDayOfWeekValueGenerator(CronField cronField, int year, int month, WeekDay mondayDoWValue) constructor. Here, if the day-of-week is defined as for example SAT-SUN, the constructor's "from" variable is 7 and the "to" variable is 1, which means the body of the for loop is never entered since "from" > "to" from the start. In other words, there is no wrapping of the int values around the end of week. To reproduce the problem, you can use this test:

```java
@Test
// This test will enter a (bounded) infinite loop searching for last execution time
public void testGetTimeFromLastExecutionForScheduleWithDayOfWeekRangeCrossingLastDayOfWeekBoundary() {
        String schedule = "0 0 * ? * MON-SUN *";
        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(QUARTZ);
        CronParser parser = new CronParser(cronDefinition);
        Cron quartzCron = parser.parse(schedule);

        ZonedDateTime time = ZonedDateTime.now();
        ExecutionTime executionTime = ExecutionTime.forCron(quartzCron);

        // Time from last execution to now
        Duration timeFromLastExecution = executionTime.timeFromLastExecution(time).get();
        Assert.assertTrue(timeFromLastExecution.toMinutes() <= 60 );
    }

```

**Comment by jmrozanec** [comment]
@ctonsing thank you for reporting this and contributing the test to cron-utils! The test was merged into master. Best!
