### ISSUE TITLE
Slash in cron exp

### ISSUE THREAD

**Issue by musaddiquesanderwale** [jmrozanec/cron-utils#345]
I am using CronBuilder to genrate the cronexpression i want to generate expression 
0 */2 * ? * *
I am not able to find Slash symbol in api

**Comment by toughpheeckouse** [comment]
may be you are looking for [Every class](https://github.com/jmrozanec/cron-utils/blob/master/src/main/java/com/cronutils/model/field/expression/Every.java).

First constructor is what you need
```java
 public Every(final IntegerFieldValue time) {
        this(always(), time);
    }
```

**Comment by jmrozanec** [comment]
Thanks @toughpheeckouse!
