### ISSUE TITLE
Valid quartz range expression is considered invalid. Range validations should be contextual to cron definition.

### ISSUE THREAD

**Issue by Paqrat76** [jmrozanec/cron-utils#35]
Version 3.1.0
Quartz parser fails for day-of-week range of SUN-SAT.  The Quartz definition appears correct but when the Quartz-based parser is created, the "DAY_OF_WEEK" constraints.stringMapping values are incorrect.  MON = 1 even though mondayDoWValue = 2.

Use following test in CronParserQuartzIntegrationTest to reproduce:
    @Test
    public void testSunToSat() {
        // FAILS SUN-SAT: SUN = 7 and SAT = 6
        parser.parse("0 0 12 ? * SUN-SAT");
    }

Stack trace:
java.lang.IllegalArgumentException: Bad range defined! Defined range should satisfy from <= to, but was [%s, %s]
	at com.cronutils.model.field.expression.Between.validate(Between.java:63)
	at com.cronutils.model.field.expression.Between.<init>(Between.java:39)
	at com.cronutils.model.field.expression.Between.<init>(Between.java:31)
	at com.cronutils.parser.field.FieldParser.parseBetween(FieldParser.java:93)
	at com.cronutils.parser.field.FieldParser.parse(FieldParser.java:69)
	at com.cronutils.parser.field.CronParserField.parse(CronParserField.java:68)
	at com.cronutils.parser.CronParser.parse(CronParser.java:96)
	at com.cronutils.parser.CronParserQuartzIntegrationTest.testSunToSat(CronParserQuartzIntegrationTest.java:129)

refer to debug values below:
![image](https://cloud.githubusercontent.com/assets/6545618/9382686/f93afccc-4710-11e5-9468-d8f5fa71501f.png)

**Comment by jmrozanec** [comment]
@Paqrat76 Thank you for reporting this!
The example you present, it has two parts:
- **range values**: SUN-SAT is considered invalid by the parser
- **Monday value mapping**: DoW strings are mapped as MON->1 ... SUN->7, while Monday DoW value is considered 2.

## Range values
Current cron-utils implementation considers ranges should be specified writing A-B, where the following property should be always met: A<=B. If A>B, range is considered invalid.
This is why the example you present fails to be parsed: SUN>SAT.
Despite Unix implementations fail in such a case, Quartz executes normally. Current behavior is a bug for Quartz case. We will add flexibility on the range validation to be performed.

## Monday value mapping
cron-utils always maps strings to values MON->1 ... SUN->7, regardless of cron implementation (See: FieldConstraintBuilder::daysOfWeekMapping).
Monday mapping specifies which concrete value is assigned to Monday by the cron specification. Example: Quartz considers SUN=1, MON=2. Using this knowledge, as well as if lowest value is zero or one, cron-utils will perform required mappings when necessary, translating internal representation to required values.
From the above, the fact that Monday string mapping and Monday reference value are not the same, is expected and does not affect the specific parser.

**Comment by jmrozanec** [comment]
@Paqrat76 issue solved. We rebuilt some parsing logic, and gained flexibility on how we represent crons and how we enforce validations.

**Comment by jmrozanec** [comment]
@Paqrat76 New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
