### ISSUE TITLE
javax.ejb.ScheduleExpression must be tagged as optional dependency

### ISSUE THREAD

**Issue by gsontag** [jmrozanec/cron-utils#359]
I try to use cron-utils in a karaf instance, and, because of the CronUtils class that import javax.ejb.ScheduleExpression, the manifest require javax.ejb as a mandatory package for this unused functionality.

**Comment by jmrozanec** [comment]
@gsontag thank you for reporting this. If you have a minute to send a PR we can release today a new version with the fix, otherwise we may delay some days. Thanks! 😄
