### ISSUE TITLE
Documentation needs to be updated for the CLI

### ISSUE THREAD

**Issue by josephtaylor** [jmrozanec/cron-utils#362]
The documentation doesn't mention anything about the CLI portion of the library being moved to a different artifact

**Comment by jmrozanec** [comment]
@josephtaylor thank you for reaching out. You are right - we shall mention libraries where functionality was decentralised. Will update soon :smile: You are welcome to contribute anything you find more helpful. Thanks!

**Comment by jmrozanec** [comment]
@josephtaylor done! Thank you for the suggestion!
