### ISSUE TITLE
QUARTZ: Incorrect next execution time

### ISSUE THREAD

**Issue by Blemicek** [jmrozanec/cron-utils#363]
The next execution for QUARTZ cron expression `* 1 * * * ?` at `2019-01-01T00:01Z` should be `2019-01-01T01:01Z` not `2019-01-01T00:01:01Z`.

**Comment by pangyikhei** [comment]
I believe that `2019-01-01T00:01:01Z` is the correct next execution time for that cron expression.
You specified * as the value for the seconds, so it should match every second of minute 1 of every hour of every day of every month of every year.

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html
Wild-cards (the ‘*’ character) can be used to say “every” possible value of this field.

You should use `0 1 * * * ?` if you intend to only get the minute 1 of every hour of every day of every month of every year.

I submitted PR #397 with tests for the two expressions `0 1 * * * ?` and `* 1 * * * ?`
