### ISSUE TITLE
Start year must be less than stop year

### ISSUE THREAD

**Issue by palerique** [jmrozanec/cron-utils#365]
Dears,

This cron expression: `0 0 0 ? * * 2016-2010` isn't a valid cron expression because the starting year is after the ending year.

It is being described by the tool like:
`at 00:00 every year between 2016 and 2010`

Is it possible to tackle this?

**Comment by jmrozanec** [comment]
@palerique thank you for reporting this! We can tackle this as a validation when ranges are requested. May we ask for a test? Best! 😄

**Comment by ph-redknee** [comment]
Well...

Due to my project characteristics I tackled it in the Object that wrap cron-utils.

```
  @Test
  void shouldBeFalseWhenUsingWrongYearsRanges() {
    Assert.assertThat("Start year must be less than stop year",
        CronExpressionValidator.isValidExpression("0 0 0 ? * * 2016-2010"), is(false));
  }
``` 

And on `CronExpressionValidator` I am ensuring this using that approach:
```
  private static boolean isNotAValidYearRange(Cron cron) {
    CronField cronField = cron.retrieve(YEAR);

    if (cronField != null) {
      FieldExpression expression = cronField.getExpression();

      Between between = expression instanceof Between ? ((Between) expression) : null;

      if (between != null) {
        return toInt(between.getFrom()) > toInt(between.getTo());
      }
    }
    return false;
  }

  private static int toInt(final FieldValue<?> fieldValue) {
    if (fieldValue instanceof IntegerFieldValue) {
      return ((IntegerFieldValue) fieldValue).getValue();
    }
    throw new IllegalArgumentException("Non integer values at intervals are not fully supported yet.");
  }
```

Maybe we can use this as a starting point.

**Comment by jmrozanec** [comment]
@palerique fixed! Now we can define strict ranges per field, ensuring this no longer happens for year fields also. Thank you for reporting this!

**Comment by jmrozanec** [comment]
@palerique @ph-redknee  a [new release](https://github.com/jmrozanec/cron-utils/milestone/17) is available. Best!
