### ISSUE TITLE
Convert cron expression to ISO8601 format

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#367]
There was a request for a similar feature [here](https://stackoverflow.com/questions/36008028/convert-cron-expression-to-iso8601-format)
ISO 86601 specification available [here](https://en.wikipedia.org/wiki/ISO_8601#Durations)

**Comment by albertotn** [comment]
I'd like to take of this during hacktoberfest, could you assign me ?

**Comment by jmrozanec** [comment]
@albertotn sure! Thanks!

**Comment by albertotn** [comment]
I'm here again to check and see this still open, I think @jmrozanec  you can close it ?

**Comment by jmrozanec** [comment]
@albertotn closed! Thanks! 😄
