### ISSUE TITLE
Validation incorrectly allows a trailing comma in a list

### ISSUE THREAD

**Issue by NielsDoucet** [jmrozanec/cron-utils#368]
The following testcase illustrates the issue:
```
	public static void main(String[] args) {
		validateExpression(CronType.CRON4J, "1,2, * * * *");
		validateExpression(CronType.CRON4J, "1, * * * *");
		validateExpression(CronType.QUARTZ, "1,2, * * * * ?");
		validateExpression(CronType.QUARTZ, "1, * * * * ?");
		validateExpression(CronType.SPRING, "1,2, * * * * ?");
		validateExpression(CronType.SPRING, "1, * * * * ?");
		validateExpression(CronType.UNIX, "1,2, * * * *");
		validateExpression(CronType.UNIX, "1, * * * *");
	}

	private static void validateExpression(CronType cronType, String expression) {
		CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(cronType);
		CronParser parser = new CronParser(cronDefinition);
		try {
			System.out.println("Validating expression: " + expression + " using " + cronType + " definition");
			parser.parse(expression);
			System.out.println("this shouldn't be valid!");
		} catch (IllegalArgumentException e) {
			System.out.println("expected failure: " + e.getMessage());
		}
	}
```
This generates the following output
```
Validating expression: 1,2, * * * * using CRON4J definition
this shouldn't be valid!
Validating expression: 1, * * * * using CRON4J definition
expected failure: Failed to parse '1, * * * *'. Missing steps for expression: 1,
Validating expression: 1,2, * * * * ? using QUARTZ definition
this shouldn't be valid!
Validating expression: 1, * * * * ? using QUARTZ definition
expected failure: Failed to parse '1, * * * * ?'. Missing steps for expression: 1,
Validating expression: 1,2, * * * * ? using SPRING definition
this shouldn't be valid!
Validating expression: 1, * * * * ? using SPRING definition
expected failure: Failed to parse '1, * * * * ?'. Missing steps for expression: 1,
Validating expression: 1,2, * * * * using UNIX definition
this shouldn't be valid!
Validating expression: 1, * * * * using UNIX definition
expected failure: Failed to parse '1, * * * *'. Missing steps for expression: 1,

Process finished with exit code 0
```

FieldParser.parse method relies on String.split, which filters out trailing empty results.
This means that this trailing token doesn't get noticed.
The case with "1," as input correctly fails, as it expects multiple tokens to be present after splitting, but there is only 1.

**Comment by jmrozanec** [comment]
@NielsDoucet thank you for reporting this and the detailed explanation! 😄 If you don't mind, we would ask a PR with this tests and would be glad to get some help on solving this. Thanks!

**Comment by NielsDoucet** [comment]
I'll provide a fix for this issue as well as #369 and #370 during the week-end.
They should be fairly straightforward.

**Comment by jmrozanec** [comment]
Thanks!

**Comment by NielsDoucet** [comment]
I have a fix ready for this, but I'm waiting for #372 to be merged, as I'm reusing the test code changes I made there.

**Comment by jmrozanec** [comment]
@NielsDoucet just saw your message - you are welcome to push changes and complement existing code and tests.

**Comment by NielsDoucet** [comment]
@jmrozanec I see you already fixed it, so no reason to apply another fix :)
Is a new bugfix release planned for the near future?
I use this library as a validator (jsr 303) and these were a few corner cases that gave me false negatives.
I'm happy to contribute the validator as well, if that is something you'd like to add.

**Comment by jmrozanec** [comment]
@NielsDoucet the validator would be a great addition to cron-utils! We will release a new version today EOD 😄

**Comment by jmrozanec** [comment]
@NielsDoucet a [new release](https://github.com/jmrozanec/cron-utils/milestone/17) is available with this changes. Best!
