### ISSUE TITLE
IllegalArgumentException for Last Day of Week pattern '0 0 1 ? 1/1 MONL *'

### ISSUE THREAD

**Issue by robryals** [jmrozanec/cron-utils#375]
IllegalArgumentException: Invalid chars in expression! Expression: MONL Invalid chars: MONL

It seems that FieldParser L_PATTERN should also accept MON-FRI.
 
private static final Pattern L_PATTERN = Pattern.compile("[0-9]L", Pattern.CASE_INSENSITIVE);

**Comment by jmrozanec** [comment]
@robryals thank you for reporting this issue! Will have a look at it as soon as possible. We would appreciate a PR with the corresponding test. Thanks!

**Comment by jmrozanec** [comment]
@robryals this issue is fixed! A new release will follow today EOD. Thanks!

**Comment by jmrozanec** [comment]
@robryals  a [new release](https://github.com/jmrozanec/cron-utils/milestone/17) is available. Best!

**Comment by robryals** [comment]
Thank you !
