### ISSUE TITLE
Migrate cron expression from Quartz To Spring

### ISSUE THREAD

**Issue by tubean** [jmrozanec/cron-utils#377]
Thank you for this tool. But I met an issue when I use CronMapper. It only supports migrate from Quartz to Unix or Cron4j. How can I migrate from Quartz to Spring expression?

**Comment by jmrozanec** [comment]
@tubean you can migrate to any cron expression, as long as you provide the target definition. Please let us know if further help is required or an issue for a bugfix must be created. Thanks! :smile:

**Comment by tubean** [comment]
@jmrozanec thank you for your reply. When I see class CronMapper, there are 4 methods  _fromCron4jToQuartz()_, _fromQuartzToCron4j()_, _fromQuartzToUnix()_ and _fromUnixToQuartz()_ but not found any method which migrates from Quartz to Spring expression. Did you mean we can use the constructor of **CronMapper** to build the new one? But I am not sure how to define **cronRules** for it 😄

**Comment by jmrozanec** [comment]
@tubean you are right about the rules - are not intuitive. Let us check by EOD and provide an accurate answer 😄 Best!

**Comment by jmrozanec** [comment]
@tubean we are working on a fix for this. You can expect a new release with fixes on Friday 😄 Thank you for reporting it!

**Comment by tubean** [comment]
@jmrozanec Great! Thank you so much 👍

**Comment by jmrozanec** [comment]
@tubean this feature was added and a new version will be released today with it. Best!

**Comment by jmrozanec** [comment]
@tubean a [new release](https://github.com/jmrozanec/cron-utils/milestone/17) is available with this feature. Best!

**Comment by tubean** [comment]
@jmrozanec Thanks!
