### ISSUE TITLE
every 2 min schedule doesn't roll over to next hour

### ISSUE THREAD

**Issue by alex-ivanov** [jmrozanec/cron-utils#38]
Sorry for scala, but it should be pretty clear:

    object CronError extends App {
      val cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX)
      val cron = new CronParser(CronSchedule.cronDefinition).parse("0 */2 * * * *")
      val executionTime = ExecutionTime.forCron(cron)
      val time = DateTime.parse("2015-09-05T13:56:00.000-07:00")
      val next = executionTime.nextExecution(time)
      val shouldBeInNextHour = executionTime.nextExecution(next)
      val text = CronDescriptor.instance(Locale.US).describe(cron)
      println(s"Schedule: $text")
      println(s"Original time: $time")
      println(s"Next event time: $next")
      println(s"It should be in next hour: $shouldBeInNextHour")
    }
Library version: 3.1.0

PS. at the same time pattern "0 */1 * * * *" works fine.

**Comment by jmrozanec** [comment]
@alex-ivanov Thank you for reporting this! The code is clear. Will try to find a solution soon.

**Comment by mkaskov** [comment]
the same problem with hour -> day. wirk fine 0 0 */1 * * *, but dont work for 2 every
0 0 */2 * * *
0 0 /2 * * *

**Comment by jmrozanec** [comment]
@mkaskov thank you for bringing up new cases. We are working on a fix for this and related issues.

**Comment by jmrozanec** [comment]
@alex-ivanov @mkaskov The issue was solved. Will release a new version of cron-utils before the weekend. Thank you for reporting the cases!

**Comment by jmrozanec** [comment]
@alex-ivanov @mkaskov  [Version 3.1.1](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.1) was released including this fix!
