### ISSUE TITLE
Cannot specify a path for resourceBundle in CronDescriptor.java

### ISSUE THREAD

**Issue by vbradnitski** [jmrozanec/cron-utils#381]
a path to resourceBundle is set to `String BUNDLE = "CronUtilsI18N"` value and cannot be specified. In my case I use it in one of OSGI bundles and have no ability to change ClassLoader settings, so all "CronUtilsI18N*.properties" must be placed in the root of target jar. 

Woudn't you mind to add new constructor to use custom ClassLoader or do it like it done in "refactor/TimeDescriptor.java" to make it possible to use custom resourceBundle?

**Comment by jmrozanec** [comment]
@vbradnitski thank you for reporting this. We will check this case and come back with an answer. Thanks!
