### ISSUE TITLE
Last execution must truncate milliseconds

### ISSUE THREAD

**Issue by pgorin** [jmrozanec/cron-utils#382]
Hi!
First of all, thanks for your great work!
I need help for maybe an issue when getting last execution of a UNIX cron expression (SingleExecutionTime implementation).

Look at this example:
ExecutionTime.forCron(new CronParser(CronDefinitionBuilder.instanceDefinitionFor(UNIX)).parse("0 0 * * WED")).lastExecution(OffsetDateTime.of(2019, 6, 12, 0, 0, 0, 123, UTC).toZonedDateTime)

I think there is an issue when dealing with milliseconds. I was expecting that, in the given example, the lastExecution date is "2019-06-12T00:00:00.000Z", but actually is  "2019-06-05T00:00:00.000Z", a week before. If you notice, the given datetime to evaluate lastExecution is not exactly at 0 milliseconds, instead is a bit later :) (123 millis). So, I think that the correct result is the closest previous execution, at 0 milliseconds exactly.

Look inside the code, maybe the problem is that potentialPreviousClosestMatch method is returning exactly the same inpute datetime when the former one matches the given cron expression. What do you think if, knowing that the calculation does not require to consider milliseconds, then the last line:
return new ExecutionTimeResult(date, true)
truncates milliseconds to 0.

I think this is a more correctly answer when dealing with lastExecution (maybe the problem is also when fetching nextExecution).

Regards,
Patricio.

**Comment by jmrozanec** [comment]
Hola! 🇦🇷Nice observation! I will be glad to merge the PR and test if this works 😄 Do you have time for it?

**Comment by pgorin** [comment]
Great, thank you for your rapid responde. I will make the PR asap.

**Comment by jmrozanec** [comment]
@pgorin thank you for the PR! Is now merged - a release will follow tonight 😄 Best!

**Comment by jmrozanec** [comment]
@pgorin I could not release yesterday - will be done today. Best!

**Comment by pgorin** [comment]
Hi! Is there a chance that you can make the new release in the next hours? :)

**Comment by jmrozanec** [comment]
@pgorin yes - will ping you as soon as is released - most probably before 13:00 ARG 😄

**Comment by pgorin** [comment]
Great!!!! 😀

**Comment by jmrozanec** [comment]
@pgorin we have a failing test preventing the release - even though Travis builds were ok. Will work on it and release after solving the issue. Best!

**Comment by pgorin** [comment]
Mmmmm, what test is failing? When I've cloned the repo there is one test already failing.

**Comment by jmrozanec** [comment]
The CronParserQuartzIntegrationTest.testLastDayOfWeek()

**Comment by pgorin** [comment]
Exactly, this is the failure test that I mentioned to you. Can you check this?
If you look at this CI run (the previous PR to mine) this test is already failing:
https://travis-ci.org/jmrozanec/cron-utils/builds/530221507?utm_source=github_status&utm_medium=notification

**Comment by pgorin** [comment]
Any news about this?

**Comment by jmrozanec** [comment]
@pgorin we got the issue fixed - will release today before EOD ARG.

**Comment by pgorin** [comment]
Great!!!

**Comment by jmrozanec** [comment]
@pgorin released as 9.0.0! Thank you for reporting and fixing it! 😄 Saludos!

**Comment by pgorin** [comment]
Thank you a lot! Saludos from Argentina!
