### ISSUE TITLE
Parsing last DoW drops last special character

### ISSUE THREAD

**Issue by pkoenig10** [jmrozanec/cron-utils#385]
See https://github.com/jmrozanec/cron-utils/issues/384#issuecomment-506443328

**Comment by pkoenig10** [comment]
@jmrozanec can you make a new release with this fix?

**Comment by jmrozanec** [comment]
@pkoenig10 yes, you can expect it within 3hs 😄Will ping back when done.

**Comment by pkoenig10** [comment]
@jmrozanec any update on making a new release?

**Comment by jmrozanec** [comment]
@pkoenig10 released!

**Comment by pkoenig10** [comment]
@jmrozanec was the release actually tagged? I don't see it
https://github.com/jmrozanec/cron-utils/releases
https://mvnrepository.com/artifact/com.cronutils/cron-utils

**Comment by jmrozanec** [comment]
@pkoenig10 was released to Maven Central but forgot to push the tagged version to GitHub. Now is pushed to GitHub as well :smile: Thanks for pointing it out! 
On mvnrepository you can expect some delay due to indexing of new artifacts, but should be available on Central already as 9.0.1
