### ISSUE TITLE
No Proguard/R8 Rules

### ISSUE THREAD

**Issue by dsuresh-ap** [jmrozanec/cron-utils#390]
This library doesn't have any defined Proguard or R8 rules. We had to add `-keep class com.cronutils.model.field.definition.FieldDefinition` to avoid the following exception:
```
java.lang.NoClassDefFoundError (FieldDefinition.java line 93)
```

Version: 8.1.1

**Comment by jmrozanec** [comment]
@dsuresh-ap thank you for rising the issue. Do you have time to help on this? Best!

**Comment by dsuresh-ap** [comment]
Another rule I believe we needed to add:
```
-keep class com.cronutils.model.field.definition.FieldDefinition
-keepclassmembers class com.cronutils.model.field.definition.FieldDefinition {
        public static *** createFieldDefinitionComparator();
    }
```

Not sure if this is the best way to add these rules since it is specific to our app but we found `NoClassDefFoundError` with the class and its static method.

**Comment by jmrozanec** [comment]
@dsuresh-ap thank you for submitting the rules - we really appreciate them! Will try to include them ASAP. Contributions are always welcome! If you have some time to set them up, we will be grateful.

**Comment by dsuresh-ap** [comment]
@jmrozanec This is actually not a Proguard issue. We missed the note in the Readme that states <Android 26 should not upgrade past version `6.0.6`. Will make an new issue suggesting if this repo could have a changelog or release notes to keep track of changes.
