### ISSUE TITLE
Please point out in readme that should use version 6.0.6 for Android device below API 24

### ISSUE THREAD

**Issue by SJX516** [jmrozanec/cron-utils#392]
I searched the version is useful in the closed issues and it should be more clear

**Comment by jmrozanec** [comment]
@SJX516 thank you for the feedback. We just added some notes on the README.md Does that suffice the requirement? Best!

**Comment by SJX516** [comment]
that's enough, thanks

**Comment by jmrozanec** [comment]
@SJX516 a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for contributing to cron-utils!
