### ISSUE TITLE
Cron is invalid?

### ISSUE THREAD

**Issue by yangjiajun2014** [jmrozanec/cron-utils#396]
Cron-utils says '0 0 12-0 ? * 3' is a valid cron when I use version 8.1.1.But when I updated to 9.0.1,'0 0 12-0 ? * 3' became invalid.

**Comment by jmrozanec** [comment]
@yangjiajun2014 thank you for reporting this. May we ask you to add more context? Ex.: which cron definition are you using and submit a test for it? Thanks!

**Comment by yangjiajun2014** [comment]
I use CronType.QUARTZ.My code looks like:
CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
CronParser parser=new CronParser(cronDefinition);
try {
			parser.parse(cron);
} catch (Exception e) {
			return false;
}
return true;

**Comment by pangyikhei** [comment]
Quartz apparently supports overflowing ranges
See https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/CronExpression.java

```
 * <li>Overflowing ranges is supported - that is, having a larger number on 
 * the left hand side than the right. You might do 22-2 to catch 10 o'clock 
 * at night until 2 o'clock in the morning, or you might have NOV-FEB. It is 
 * very important to note that overuse of overflowing ranges creates ranges 
 * that don't make sense and no effort has been made to determine which 
 * interpretation CronExpression chooses. An example would be 
 * "0 0 14-6 ? * FRI-MON". </li>
```

@jmrozanec I can work on this one.

**Comment by jmrozanec** [comment]
@yangjiajun2014 @pangyikhei @mfaatev @NikitaNovozhilovWork a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for contributing to cron-utils!
