### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Joao-Neves** [jmrozanec/cron-utils#40]
Hello,

I just started using your library and noticed a typo in the README.md file.

On line:
```
//Get date for next execution
DateTime nextExecution = executionTime.timeToNextExecution(now));
```

Should be:
```
//Get date for next execution
DateTime nextExecution = executionTime.nextExecution(now));
```

Hope it helps.

**Comment by jmrozanec** [comment]
@Joao-Neves Thank you for reporting this! Typo fixed!

**Comment by jmrozanec** [comment]
@Joao-Neves [Version 3.1.1](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.1) was released!

**Comment by Joao-Neves** [comment]
Thank you for the heads up.
I've update my dependencies.

Best regards,
João Neves

No dia 20/10/2015, às 00:50, jmrozanec <notifications@github.com> escreveu:
