### ISSUE TITLE
slf4j transitive dependecy

### ISSUE THREAD

**Issue by albertotn** [jmrozanec/cron-utils#401]
**Description**

I'm using cron-utils as dependency in my project, packaged as war and deployed in wildfly 17.0.1. All works fine, but during wildfly's startup there is:

>  WFLYSRV0059: Class Path entry slf4j-api-1.7.12.jar in /C:/Users/.../WEB-INF/lib/cron-utils-9.0.0.jar  does not point to a valid jar for a Class-Path reference.

My project is a gradle based one, so I've declared only dependency to cron-utils.
With gradle it's possible to display dependency tree (using _gradle dependecies -q_) and so it's easy to spot dependency version requirement:

> +--- com.cronutils:cron-utils:9.0.0
> |    \--- org.slf4j:slf4j-api:1.7.12 -> 1.7.25

What we can see with "1.7.12 > 1.7.25" is because of other dependencies, slf4j-api will require higher version, for example swagger-core (require 1.7.22 version):

> |    +--- io.swagger:swagger-core:1.5.21
> |    |    +--- org.apache.commons:commons-lang3:3.2.1 -> 3.9
> |    |    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25

**Analysis**

Lookin for a solution, I've found inside cron-utils's jar versione 9.0.0 there is in manifest file this entry:

> Class-Path: slf4j-api-1.7.12.jar

I'm not sure why this, so I wonder if there is something I can do about this. 
I've tried to exclude cron-utils's transitive dependency but is declared inside jar's classpath, so in the end this warning will be always present

**Solution**

Could be feasible to remove slf4j-api dependency and ( of course ) remove all logs from cron-utils? 
If you think this is acceptable I'd like to take this taks in a fork and submit a PR.

**Comment by jmrozanec** [comment]
@albertotn we need logging, so removing all logs from cron-utils is not an option. But it would be great if we can iterate this, to ensure the dependency can be provided but is not forced to the ones who use cron-utils. An option it would be to change the scope of the dependency to "provided" - would that satisfy the case? Will be glad to further discuss the issue and get some help on this.

**Comment by albertotn** [comment]
Thanks @jmrozanec for your feedback!
I think a "pure library" to be general should be without any dependency, even log one. I understand your concern and need.

If you want I could take this issue, investigate on provided and submit a PR ?

**Comment by jmrozanec** [comment]
@albertotn sure! As long as the solution is not to remove logging 😉Thanks!

**Comment by jmrozanec** [comment]
@albertotn do we have any updates on this?

**Comment by albertotn** [comment]
not yet, I'm still motivated to investigate on it

**Comment by albertotn** [comment]
@jmrozanec I've updated my fork from master and after a mvn install get this error on test:

> Failed tests:
>   CronConverterTest.testCronConverterBuilder:66 expected:<30 1[0] * * ?> but was:<30 1[1] * * ?>
>   CronConverterTest.testCronConverterBuilder:66 expected:<50 [2] * * ?> but was:<50 [3] * * ?>

**Comment by jmrozanec** [comment]
@albertotn thanks! Best!

**Comment by jmrozanec** [comment]
@albertotn a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for contributing to cron-utils!

**Comment by maikebertpsc** [comment]
Hi,
may I ask what was the actual fix here?

In our JBoss we still get the following warnings with version 9.1.0:

> 2020-09-11 13:57:54,516 WARN   [org.jboss.as.server.deployment]  WFLYSRV0059: Class Path entry slf4j-api-1.7.30.jar in /content/merchant-center-web.war/WEB-INF/lib/cron-utils.jar  does not point to a valid jar for a Class-Path reference.
> 2020-09-11 13:57:54,516 WARN   [org.jboss.as.server.deployment]  WFLYSRV0059: Class Path entry slf4j-simple-1.7.30.jar in /content/merchant-center-web.war/WEB-INF/lib/cron-utils.jar  does not point to a valid jar for a Class-Path reference.
> 2020-09-11 13:57:54,517 WARN   [org.jboss.as.server.deployment]  WFLYSRV0059: Class Path entry commons-lang3-3.9.jar in /content/merchant-center-web.war/WEB-INF/lib/cron-utils.jar  does not point to a valid jar for a Class-Path reference.
> 2020-09-11 13:57:54,517 WARN   [org.jboss.as.server.deployment]  WFLYSRV0059: Class Path entry lombok-1.18.10.jar in /content/merchant-center-web.war/WEB-INF/lib/cron-utils.jar  does not point to a valid jar for a Class-Path reference.

I assume best would be to not have these class path entries in the MANIFEST:

> Class-Path: slf4j-api-1.7.30.jar slf4j-simple-1.7.30.jar commons-lang3
>  -3.9.jar lombok-1.18.10.jar
