### ISSUE TITLE
lastExecution calculates incorrect result for less-than-annual schedules

### ISSUE THREAD

**Issue by sbandler** [jmrozanec/cron-utils#402]
lastExecution seems to be ignoring the quartz year field when calculating the lastExecution. 

Setting "now" to 1/15/2015 0:0:0:0 UTC, using quartz expression "0 0 0 1 3 ? 2001/2", the last execution should be 3/1/2013, however the result produced is 3/1/2014. 

If you generate last execution and check if its a match, it returns false. 

if you generate next execution, it returns the correct result.

if you generate next execution and then the last before that, it returns an incorrect result.

**Comment by jmrozanec** [comment]
@sbandler thank you for reporting this. Can you submit a PR with the corresponding tests for the issue? Thanks! 😄

**Comment by IndeedSi** [comment]
May I take this issue? I still need some time but should be able to get this fixed tomorrow.

**Comment by jmrozanec** [comment]
@IndeedSi sure! Go ahead!
