### ISSUE TITLE
MON-FRI constraint ignored on nextExecution 

### ISSUE THREAD

**Issue by michaelboyles** [jmrozanec/cron-utils#406]
This block of code will return next executions on Saturdays and Sundays, even though they are not allowed by the cron.

    final CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.SPRING);
    final CronParser parser = new CronParser(cronDefinition);
    ExecutionTime execTime = ExecutionTime.forCron(parser.parse("0 5 0 * * MON-FRI"));
    execTime.nextExecution(/*a saturday*/);

I narrowed the problem down to here (SingleExecutionTime line 500). `getExpression` is not an instance of QuestionMark, so it is the second half of the ternary which is wrong in this case

	this.daysOfWeekCronField.getExpression() instanceof QuestionMark ? (List)FieldValueGeneratorFactory.createDayOfMonthValueGeneratorInstance(this.daysOfMonthCronField, year, month).generateCandidates(1, lengthOfMonth).stream().distinct().sorted().collect(Collectors.toList()) : (List)Stream.concat(FieldValueGeneratorFactory.createDayOfWeekValueGeneratorInstance(this.daysOfWeekCronField, year, month, mondayDoWValue).generateCandidates(1, lengthOfMonth).stream(), FieldValueGeneratorFactory.createDayOfMonthValueGeneratorInstance(this.daysOfMonthCronField, year, month).generateCandidates(1, lengthOfMonth).stream()).distinct().sorted().collect(Collectors.toList())

The day of week generator generates the right thing, however this stream is combined with the day of month generator which returns every date for the month, effectively overriding the day of week result.

`Stream.concat` should not be used, it should be some kind of union.

**Comment by jmrozanec** [comment]
@michaelboyles thank you for reporting this. May we ask you to submit a PR with a test? Thanks!

**Comment by michaelboyles** [comment]
As it turns out, this issue has been fixed since 9.0.1. I sent you a PR for the passing test, just so you can add to your test suite to prevent regression.

https://github.com/jmrozanec/cron-utils/pull/407
