### ISSUE TITLE
Incorrect time sequence generated

### ISSUE THREAD

**Issue by maxmorozov** [jmrozanec/cron-utils#408]
For expression "0 10/4 * * *" (every 4 hours starting from 10) generated time sequence is: 6, 10, 14, 18, 22 . Expected sequence: 10, 14, 18, 22

**Comment by jmrozanec** [comment]
@maxmorozov thank you for reporting this. Can you submit a test case that better describes the context? Thanks!

**Comment by maxmorozov** [comment]
CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
                .withMinutes().withStrictRange().withValidRange(0, 60).and()
                .withHours().withStrictRange().and()
                .withDayOfMonth().supportsL().withStrictRange().and()
                .withMonth().withStrictRange().and()
                .withDayOfWeek().withValidRange(0, 7).withMondayDoWValue(1).withIntMapping(7, 0).supportsHash().supportsL().withStrictRange().and()
                .instance();

        final CronParser parser = new CronParser(cronDefinition);
        ExecutionTime execTime = ExecutionTime.forCron(parser.parse("0 10/4 * * *"));
        final ZonedDateTime startDate = ZonedDateTime.parse("2019-11-08T00:00Z");
        Optional<ZonedDateTime> next = execTime.nextExecution(startDate);
        assertEquals(ZonedDateTime.parse("2019-11-08T10:00Z"), next.get());

**Comment by jmrozanec** [comment]
@maxmorozov thanks! Can you send a PR?

**Comment by maxmorozov** [comment]
I have not tried to fix it yet. 
If I make the fix I will send PR

**Comment by jmrozanec** [comment]
@maxmorozov thank you for contributing the fix! 😄

**Comment by jmrozanec** [comment]
@maxmorozov a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for contributing to cron-utils!
