### ISSUE TITLE
lastExecution and nextExecution do not work

### ISSUE THREAD

**Issue by kwalsh413** [jmrozanec/cron-utils#41]
for everything other than a dayOfWeek value == 1, nextExecution and lastExecution do not return correct results. Example below should return a date of 9/23 while it returns 9/30. Similiarly other days return a week further then they should. Only 1 gives the correct value of 9/21.  I tried with previous versions of this and although i get a different result, it is still wrong. with previous versions i always get the next day (9/19)

CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX);
CronParser parser = new CronParser(cronDefinition);
			 Cron myCron = parser.parse("0 3 * * 3");
DateTime now = DateTime.now();
		     ExecutionTime executionTime = ExecutionTime.forCron(myCron);
		     DateTime nextExecution = executionTime.nextExecution(now);

**Comment by jmrozanec** [comment]
@kwalsh413 thank you for reporting this. Will review this issue as part of the fix for #37 and #38 
Contributions are welcome!

**Comment by jmrozanec** [comment]
@kwalsh413 the issue was fixed! Will release a new version of cron-utils to Maven central before weekend.

**Comment by jmrozanec** [comment]
@kwalsh413 [Version 3.1.1](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.1) was released including this fix!
