### ISSUE TITLE
Wrong intervals in error message on invalid period

### ISSUE THREAD

**Issue by melonhead901** [jmrozanec/cron-utils#413]
Attempting to parse expression `* * * */12 *` gives the error message 
"Failed to parse '* * * */12 *'. Period 12 not in range (1, 12]"

The range listing is wrong, it should be [1, 12)

**Comment by Haarolean** [comment]
Same problem here. 
Had to use a workaround: define a year.

**Comment by jmrozanec** [comment]
@melonhead901 thank you for reporting this. We pushed a fix for it! Best!

**Comment by jmrozanec** [comment]
@melonhead901 a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for contributing to cron-utils!
