### ISSUE TITLE
Quartz: Bad intervals and worse error messages

### ISSUE THREAD

**Issue by Eyal-Shalev** [jmrozanec/cron-utils#418]
Running the cron string `0 0 2 ? * 1/7 *` throws the following error: `Period 7 not in range (1, 7]`.
According to the quartz documentation the range should be `[1,7]`, and sites like [Cron Expression Generator & Explainer - Quartz](https://www.freeformatter.com/cron-expression-generator-quartz.html) agree.

Even worse, `7` is actually in the range `(1,7]`, but `1` isn't, see the wiki page on math intervals: [Interval (mathematics)](https://en.wikipedia.org/wiki/Interval_(mathematics))

**Comment by jmrozanec** [comment]
@Eyal-Shalev thank you for reporting this. May we ask a PR with a test to reproduce the issue? Thanks!

**Comment by Eyal-Shalev** [comment]
Added a PR with a failing test

**Comment by jmrozanec** [comment]
@Eyal-Shalev thank you for reporting this. Fixes were made and pushed into master. Thanks! 😄

**Comment by jmrozanec** [comment]
@Eyal-Shalev a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for contributing to cron-utils!
