### ISSUE TITLE
A cron-utils bug by withValidRange

### ISSUE THREAD

**Issue by HongZhaoHua** [jmrozanec/cron-utils#428]
define CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ)

use cron "0 0 12 * * ?"

and use dateTime = ZonedDateTime.of(1900, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC);

now, run execution.nextExecution(dateTime);

you will get the result is 1900-1-1T12:00

but in fact, the result must be 1970-1-1T12:00 because CronType.QUARTZ was limit the year range from 1970 to 2099.

**Comment by HongZhaoHua** [comment]
here is the unit test. plz check it.

    @Test
    public void testBoundary() {
        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
        CronParser parser = new CronParser(cronDefinition);
        ExecutionTime execution = ExecutionTime.forCron(parser.parse("0 0 12 * * ?"));
        {
            ZonedDateTime dateTime = ZonedDateTime.of(1900, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC);
            dateTime = execution.nextExecution(dateTime).orElse(null);
            Assert.assertEquals(ZonedDateTime.of(1970, 1, 1, 12, 0, 0, 0, ZoneOffset.UTC), dateTime);
        }
        {
            ZonedDateTime dateTime = ZonedDateTime.of(2150, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC);
            dateTime = execution.lastExecution(dateTime).orElse(null);
            Assert.assertEquals(ZonedDateTime.of(2099, 12, 31, 12, 0, 0, 0, ZoneOffset.UTC), dateTime);
        }
    }

**Comment by HongZhaoHua** [comment]
version is 9.0.2.

**Comment by jmrozanec** [comment]
@HongZhaoHua thanks! If is not too much to ask, may you send us a PR with the proposed test? Thanks!

**Comment by HongZhaoHua** [comment]
@jmrozanec 
The proposed test was on the 2th floor, don't u see it?
^^

**Comment by jmrozanec** [comment]
@HongZhaoHua sure we see it 😄 But on github we usually contribute code as PR and not through comments. If you have some minutes and could be so kind to post a PR, we will be glad to merge it. Thanks!

**Comment by IndeedSi** [comment]
I'm wondering if this is really a bug. It is true that QUARTZ cron expression only takes year between 1970 and 2099, but do we have that limit for the execution time?  
"0 0 12 * * ?" means a job which fires at 12:00:00pm every day. I don't see how this expression limits the fire dates to be within 1970, 2099.

**Comment by jmrozanec** [comment]
@IndeedSi we shall support the definition, including the constraints.

**Comment by IndeedSi** [comment]
@jmrozanec  Gotcha. I have got a change for passing the constraint from cron definition to execution time.
