### ISSUE TITLE
New release with converters ?

### ISSUE THREAD

**Issue by albertotn** [jmrozanec/cron-utils#429]
I notice new development on this useful library and hope you will release a 9.0.3 version ( with converters ) on maven central repository. Do you have any time frame for this ? Thanks!

**Comment by jmrozanec** [comment]
@albertotn we can release this week! 😄 Will post an update when done! Best!

**Comment by cmorriss** [comment]
Could use this as well! This is particularly useful as I'm creating scheduled rules in AWS CloudWatch which are in GMT, however I'd like to present to the user in the local time zone. This is perfect for performing the conversion back and forth.

**Comment by jmrozanec** [comment]
@cmorriss that is a great use case! Thanks for sharing! 😄 We will post an update after releasing this weekend.

**Comment by cmorriss** [comment]
Any update of the new release?

**Comment by jmrozanec** [comment]
@cmorriss @albertotn a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for the heads up!
