### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings

### ISSUE THREAD

**Issue by natros** [jmrozanec/cron-utils#434]
cron-utils should not provide any slf4j implementation like `slf4j-simple` to avoid multiple slf4j bindings in classpath

**Comment by jmrozanec** [comment]
@natros thank you for the insight. May we ask you for a PR with a fix? Will be glad to check and merge. Thanks! :smile:

**Comment by francisdb** [comment]
@jmrozanec can this please be released?

**Comment by jmrozanec** [comment]
@francisdb sure. Will release today EOD. Thank you for pushing forward! 😄

**Comment by jmrozanec** [comment]
@francisdb a new version was released! We apologize for the delay! 😄

**Comment by francisdb** [comment]
Thanks a lot, no need for apologies!
