### ISSUE TITLE
Create changelog or add release notes

### ISSUE THREAD

**Issue by dsuresh-ap** [jmrozanec/cron-utils#436]
Is it possible to have a changelog for changes between releases or add release notes to every new version?

Example use case: We been using 8.1.1 and just realized that older Android versions are only supported on 6.0.6. However we don't know how much has changed between 6.0.6 and 8.1.1.

**Comment by jmrozanec** [comment]
@dsuresh-ap we log all changes in the release notes. Best!

**Comment by dsuresh-ap** [comment]
@jmrozanec Could you link me to the release notes? I went to the Releases and did not see any changes.

**Comment by jmrozanec** [comment]
@dsuresh-ap [here an example](https://github.com/jmrozanec/cron-utils/milestone/19?closed=1)

**Comment by dsuresh-ap** [comment]
Correct me if I am mistaken but I see a list of issues that were fixed for Milestone 9.10. If that is correct then what I meant by this issue was to provide a Changelog in a plain text format like some other libraries. Ex. [Changelog for Realm](https://github.com/realm/realm-java/blob/master/CHANGELOG.md)

If that is not feasible or something that won't be considered then please feel free to close the issue. It would be a nice to have. Thanks!

**Comment by jmrozanec** [comment]
@dsuresh-ap it is feasible, but we don't see an added value vs. cost of maintenance. The issue was already closed due to this.
