### ISSUE TITLE
Improvement: avoid declaring Lombok as a transitive dependency

### ISSUE THREAD

**Issue by jaguililla** [jmrozanec/cron-utils#437]
In the latest release (9.1.0) the Lombok dependency is included, however, it won't be needed at runtime ¿could it be set as "compile only"?

Thanks for your great library!

**Comment by jmrozanec** [comment]
@jaguililla sure, we can do that! If you send a PR with the change, we will be glad to merge it. Thanks! 😄

**Comment by jaguililla** [comment]
The proposed change is in the #438 PR.
