### ISSUE TITLE
Empty description for Quartz Cron Expression: * 0 * * * ?

### ISSUE THREAD

**Issue by littleYanzi** [jmrozanec/cron-utils#439]
I got empty description from CronDescriptor for Cron Expression: * 0 * * * ?, I think this is NOT correct.

**Comment by jmrozanec** [comment]
@littleYanzi thank you for reporting this. May we ask you for a PR with a test? Thanks!

**Comment by albertotn** [comment]
I'd like to take care of this during hacktoberfest, could you assign me ?

**Comment by jmrozanec** [comment]
@albertotn sure! Thanks!
