### ISSUE TITLE
Incorrect description for Quartz Cron Expression: * 2,1/31 * * * ?

### ISSUE THREAD

**Issue by littleYanzi** [jmrozanec/cron-utils#440]
I got the following description from CronDescriptor for Cron Expression: * 2,1/31 * * * ?
at and 2 minutes and every 31 minutes

The description is not accurate, this might be ok, but the word 'and' following the 'at' is a clear issue, I think at least the word 'and' right after word 'at' should be removed.

**Comment by jmrozanec** [comment]
@littleYanzi thank you for reporting this. We will be glad to merge a test with this issue if you submit the PR. Thanks!

**Comment by albertotn** [comment]
I'd like to take care of this during hacktoberfest, could you assign me ?

**Comment by jmrozanec** [comment]
@albertotn sure! Thanks!

**Comment by edmeme** [comment]
There's another element missing in the description that is bothering me. It should read "**Every second** at 2 minutes and every 31 minutes" (and I'd say "every second at minute 2 and every 31 minutes" is more clear)
