### ISSUE TITLE
Schedule to run every 24day?

### ISSUE THREAD

**Issue by TaridaGeorge** [jmrozanec/cron-utils#441]
Is it possible to schedule every 24 day? How can I do that with CronBuilder?

I've tried something like this:

12 15 */24 -> Run every from 24 day to 24 at 12:15 But it doesn't work. I get this exception

Invalid cron expression: 12 15 */24. Both, a day-of-week AND a day-of-month parameter, are not supported.

**Comment by jmrozanec** [comment]
@TaridaGeorge is possible! 😄  Below we provide a snippet of code, where you can cron for an event to happen every 24 days or on 24th each month:

```
        CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
        CronDescriptor descriptor = CronDescriptor.instance(Locale.UK);
        System.out.println(descriptor.describe(parser.parse("0 0 0 24 * ? *")));
        System.out.println(descriptor.describe(parser.parse("0 0 0 */24 * ? *")));
```

Hope this helps! If any further questions arise, will be glad to answer! 😄

**Comment by Ice32** [comment]
This is unclear to me. I'm assuming that, when you say "Every 24 days", the starting point is the first day of the month? Is there a way to handle execution every 24 days starting with some custom date?
