### ISSUE TITLE
executionTime.nextExecution(startDateTime) error

### ISSUE THREAD

**Issue by zhanxingcheng** [jmrozanec/cron-utils#444]
**1. cron desc:**     "0 40 08 ? * *"    

**2. code desc:**
DateTime startDateTime = new DateTime(1601426291898L);  //  2020-09-30T08:38:11.898+08:00
startDateTime = executionTime.nextExecution(startDateTime); // startDateTime changed 2020-10-01T08:40:00.000+08:00

**3. question desc:**  2020-09-30T08:40:00.000+08:00 was losted

**Comment by zhanxingcheng** [comment]
<dependency>
            <groupId>com.cronutils</groupId>
            <artifactId>cron-utils</artifactId>
            <version>4.1.2</version>
        </dependency>

**Comment by jmrozanec** [comment]
@zhanxingcheng thank you for reporting this. We very much appreciate it! May we ask for a PR with a test for the case you described? Thank you! 😄

**Comment by charchithere** [comment]
hey! i would like to work on this Issue

**Comment by jmrozanec** [comment]
@charchithere go for it! Thanks!

**Comment by jmrozanec** [comment]
@charchithere any updates on this issue?
