### ISSUE TITLE
Human readable expression is incorect

### ISSUE THREAD

**Issue by DPovilas** [jmrozanec/cron-utils#457]
Hi, consider crontab expression:
`*/2,1 * * * * <some job>`
This job should start at first minute of every hour and then start at every second minute. **cron-utils** translates it like this: 

> Job will execute at and 1 minutes and every 2 minutes.

This is how this expression is translated into human readable format on [contab.guru](https://crontab.guru/#*/2,1_*_*_*_*) 

> At every 2nd minute and 1.

I think **cron-utils** needs to clarify the translation for this specific case.

**Comment by jmrozanec** [comment]
@DPovilas thank you for reporting this. May we ask you to submit a PR with the corresponding tests? Thanks!

**Comment by DPovilas** [comment]
Actually, I ran some tests. `CronDescriptor` defines this expression like this:

> at minute 1 and every 2 minutes

This is a correct description. Maybe this problem was fixed after the release of 9.1.1 version. I think you can close this issue. I'm not going to do a PR, because it seems that this issue was solved.
