### ISSUE TITLE
CronBuilder accepting -1 as argument for UNIX

### ISSUE THREAD

**Issue by barunhalderkolkata** [jmrozanec/cron-utils#459]
```
Cron cron = CronBuilder.cron(CronDefinitionBuilder.instanceDefinitionFor(UNIX))
                    .withDoM(always())
                    .withMonth(always())
                    .withDoW(always())
                    .withHour(on(-1))
                    .withMinute(on(5))
                    .instance();
```

This is creating cron object instead of throwing error like `java.lang.IllegalArgumentException: Value -1 not in range [0, 23]`

And this is failing eventually while trying to parse.

**Comment by jmrozanec** [comment]
@barunhalderkolkata thank you for reporting this! May we ask a PR with a test? Thanks!

**Comment by jmrozanec** [comment]
@barunhalderkolkata Fixed!
