### ISSUE TITLE
Verify if DateTime matches a crontab

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#46]
Add feature to verify if DateTime matches a crontab.

**Comment by jmrozanec** [comment]
Feature requested by @mjsaber at gitter.

**Comment by jmrozanec** [comment]
This same feature is requested at a [stackoverflow question](http://stackoverflow.com/questions/26632880/compare-cron-expression-with-current-time)

**Comment by f-aubert** [comment]
Hello, i'm not sure if this the good place to post. But couldn't it be implemented simply by making the Method nextClosestMatch in Class ExecutionTime "public"?
Then simply: date.equals(executionTime.nextClosestMatch(date));
It might not be the most efficient way but at least the method could be provided in the next release? I'm also counting on it.

**Comment by jmrozanec** [comment]
@f-aubert Hello! Thank you for posting on this issue. 
I think the proposed method is not solving most cases: if you want to verify if it matches any date, then checking just against the next is not enough; example: verify against a date in the past. You also can't approximate to checking against a range, since if an event happens every second or a million years, you would be checking a large amount of moments or not, without ensuring a correct answer.
We require a new method, to validate field per field if that expression matches a given date, and return the result.
I am now solving issue #59. As soon as we finish that one, we will pick this one. You are welcome to contribute!

**Comment by jmrozanec** [comment]
@mjsaber @f-aubert implemented as #71

**Comment by jmrozanec** [comment]
@f-aubert @mjsaber Final implementation was not complicated: if a date is valid, then the following check should be true: nextExecution(lastExecution(date)).equals(date)
executionTime.isMatch(date) performs that validation and returns the equals result.
