### ISSUE TITLE
Incorrect description for "* /30 * * * *"

### ISSUE THREAD

**Issue by norbertroamsys** [jmrozanec/cron-utils#462]
Actual result :  "every 30 minutes"

Expected Result : SOMETHING LIKE "**Every second**, every 30 minutes, starting at minutes past the hour"
Please see: https://bradymholt.github.io/cron-expression-descriptor/ as one "reference".

It looks like the "seconds" part is ignored because "0 /30 * * * *" or "1 /30 * * * *" will generate the same output.

Test case/Code:
```
try {
    CronDescriptor cd = CronDescriptor.instance(Locale.ENGLISH);
    CronParser parser = new CronParser (CronDefinitionBuilder.instanceDefinitionFor(CronType.SPRING));
    final String cronExpression = "* /30 * * * *";
    Cron c = parser.parse(cronExpression);
    System.out.println("Expression:\t"+cronExpression);
    System.out.println("Description:\t"+cd.describe(c));
    CronExpression ce = new CronExpression(cronExpression);
    System.out.println("Next start:\t"+ce.getNextValidTimeAfter(new Date()));
} catch (Exception e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}

```

We find this smart library very helpful and hope that the issue may be easy to fix. 

Thanks for support and/or feedback!

**Comment by jmrozanec** [comment]
@norbertroamsys thank you for reporting this. May we ask you to submit the test code as a PR? Thanks!

**Comment by norbertroamsys** [comment]
Hi @jmrozanec - I hope that's how it is suiteable for you. The JUnit test which contains the issue is set to `Ignore`. So you may merge and build it without fixing ;-).

**Comment by jmrozanec** [comment]
@norbertroamsys thank you! And have a happy new year! 😄
