### ISSUE TITLE
Suggestion: Remove commons-lang3 dependency

### ISSUE THREAD

**Issue by dangtranhoang** [jmrozanec/cron-utils#464]
Hi,

**cron-utils** only use _StringUtils.isNumeric_ in _BaseCronTransformer_ and _StringUtils.join_ in _CronConverter_. Moreover, **cron-utils** already has its own StringUtils class.

Maybe you can merge those two functions from _apache's StringUtils_ into _cron-utils' StringUtils_ so we can remove _commons-lang3_ dependency.

Thanks.

**Comment by jmrozanec** [comment]
@dangtranhoang that is a good suggestion! Thank you! If you have time, we would appreciate the PR with the proposed changes. Best!

**Comment by dangtranhoang** [comment]
@jmrozanec, please check #465

**Comment by jmrozanec** [comment]
@dangtranhoang thanks! 😄

**Comment by jmrozanec** [comment]
@dangtranhoang merged!

**Comment by jmrozanec** [comment]
@dangtranhoang a new release was published with the fix! 😄
