### ISSUE TITLE
Weekday.SUNDAY with Quartz definition returns invalid int

### ISSUE THREAD

**Issue by watermark** [jmrozanec/cron-utils#466]
Using the latest version 9.1.3, SUNDAY returns the wrong value when the QUARTZ definition is used.

```
CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
int value = Weekday.SUNDAY.getWeekday(cronDefinition);
```

value contains the int "8" where it should be "1".  "8" is an invalid value, so the CronBuilder fails.

**Comment by jmrozanec** [comment]
@watermark may we ask you for a PR with a test for this case? Thank you! 😄

**Comment by jmrozanec** [comment]
@watermark we are unable to reproduce the issue. May we ask for a PR with the test? Best!
