### ISSUE TITLE
I wonder if there is a spring to quartz mapper

### ISSUE THREAD

**Issue by aristotll** [jmrozanec/cron-utils#472]

**Comment by aristotll** [comment]
<img width="620" alt="Snipaste_2021-03-26_11-08-50" src="https://user-images.githubusercontent.com/13341544/112573803-f62dd680-8e27-11eb-8cb3-d40e288a2b9b.png">

**Comment by jmrozanec** [comment]
@aristotll thank you for reporting this. Though you can always build your own custom mapper, we agree this would be a nice addition. Will make an effort to add it over the weekend and release a new version! 😄 If you have time to contribute it, that would be great. Thanks!

**Comment by jmrozanec** [comment]
@aristotll done! You can expect a release within a day! Thanks! 😄

**Comment by jmrozanec** [comment]
@aristotll a new release was published with the feature! 😄
