### ISSUE TITLE
Migrate to JDK 16

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#474]

**Comment by jmrozanec** [comment]
Most of the dependencies were upgraded. Two tests were commented due to this [Powermock issue](https://github.com/powermock/powermock/issues/1094)

**Comment by albertotn** [comment]
@jmrozanec if you want I'd like to help as part of hacktoberfest ( if you can label this issue too )

**Comment by jmrozanec** [comment]
@albertotn done!

**Comment by jmrozanec** [comment]
@albertotn thanks! 😄
