### ISSUE TITLE
Incorrect mapping of intervals of day of week from unix to quartz

### ISSUE THREAD

**Issue by hibnico** [jmrozanec/cron-utils#495]
Mapping from unix to quartz, the day of week needs to switch by one. The mapper is switching every number it finds in the day of the week expression. But the number for an interval shouldn't be switched.

For instance, in Unix, "* * * * */2" means every minute every 2 days of the week. The mapper translate it into "* * * * */3", which has a different meaning: every minute every 3 days of the week.

Also, while trying to fix the issue, I have found out that the parsing in unix doesn't execute the "int mapping" for interval. "1/3" means every 3 days, starting monday. In Unix 7 is remapped to 0, but this remapping is not applied there, "7/3" should be parsed as "0/3".

**Comment by jmrozanec** [comment]
@hibnico version 9.1.7 was released with this fix! Thanks! 😄
