### ISSUE TITLE
IllegalArgumentException upgrading from 5.0.5 to 9.1.3

### ISSUE THREAD

**Issue by sserbousek** [jmrozanec/cron-utils#499]
Hello, I am upgrading a series of libraries which transitively includes a CronUtils upgrade from 5.0.5 to (currently) 9.1.3. One of our existing tests is failing for a method that detects and converts Unix cron to Quartz cron.

Test case to reproduce:
```java
    /**
     * We want to convert Unix cron expressions to Quartz cron expressions. This is a known format we expect.
     * 9.1.3 Result: 
     * java.lang.IllegalArgumentException: Failed to parse '12 1 * ? *'. Invalid expression: ?
     */
    @Test
    public void testCronExpressionForConversionToQuartz() {
        final CronParser unixParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX));
        final CronMapper unixToQuartz = CronMapper.fromUnixToQuartz();
        String unixExpression = "12 1 * ? *";
        // Works on 5.0.5, throws IllegalArgumentException in 9.1.3
        Cron unixCron = unixParser.parse(unixExpression);
        // Goal: Convert unix expressions to quartz.
        String quartzExpression = unixToQuartz.map(unixCron).asString();
        // This is what we expected.
        assertEquals("0 12 1 * ? ? *", quartzExpression);
    }
```

As someone not very familiar with the various cron syntaxes/dialects, I'm hoping someone can help determine whether this is a regression, or something that can be configured for old behavior, or otherwise. 

Any insight into this is much appreciated.

**Comment by jmrozanec** [comment]
@sserbousek thank you for reporting this! May we ask you a PR with the test provided above? Thanks! 😄

**Comment by sserbousek** [comment]
PR provided above, thanks.

**Comment by sserbousek** [comment]
Any chance of this one getting fixed?

**Comment by jmrozanec** [comment]
@jmrozanec we can have a look over the weekend. If you have some time to contribute a fix, it will be much appreciated. Thanks! 😄

**Comment by lodenrogue** [comment]
`?` is not a valid token in unix cron. Maybe you meant to use `*`?

Here's the documentation for unix cron:
https://www.ibm.com/docs/en/db2/11.5?topic=task-unix-cron-format

**Comment by jmrozanec** [comment]
@lodenrogue thank you for looking into this and providing an answer. @sserbousek we are closing the issue, given the answer above. Best!
