### ISSUE TITLE
lastExecution can return dates in the future when cron definition contains "day of week"

### ISSUE THREAD

**Issue by dwilkie81** [jmrozanec/cron-utils#50]
For cron expressions which specify a day of the week to run on, ExecutionTime.lastExecution can return a date in the future if the last execution was in the previous month.

E.g. for cron expression "0 11 * * 1" if you try to get the last execution as of "2015-11-02T00:10:00" it will return "2015-11-16T11:00:00" rather than "2015-10-26T11:00:00" as expected.

This appear to be due to a bug in TimeNode.java which doesn't return the correct shift value when getting the nearest backward value.

It looks like a similar bug was fixed in TimeNode.getNearestForwardValue as part of issue #37

**Comment by jmrozanec** [comment]
@dwilkie81 Thank you for reporting and contributing a fix! Pull request was merged into master!
