### ISSUE TITLE
Spring cron definition should allow L, W, LW

### ISSUE THREAD

**Issue by esommars** [jmrozanec/cron-utils#501]
According to this release: https://spring.io/blog/2020/11/10/new-in-spring-5-3-improved-cron-expressions
The day-of-month should support L, W and LW.

**Comment by jmrozanec** [comment]
@esommars thank you for the heads up. We will check for this functionality, and make sure is supported. Best!

**Comment by korthout** [comment]
@jmrozanec Could you help guide how support could be added?

Am I correct that it's as easy as marking the [SPRING `CronDefinition` for day of the month](https://github.com/jmrozanec/cron-utils/blob/master/src/main/java/com/cronutils/model/definition/CronDefinitionBuilder.java#L398) to now support these using `supportsL()` and `supportsW()`?

**Comment by korthout** [comment]
@jmrozanec Wow, that's a fast response! 😄 

And that's great to hear! Let me know if you need my help in any way. Otherwise, thanks for this!

**Comment by jmrozanec** [comment]
@korthout thanks! 😄 You are welcome!

**Comment by jmrozanec** [comment]
@korthout the feature was added, and a new version (9.1.8) was released with it. We provide full compliance with the features listed in the new Spring cron version, including nicknames. We hope you find it useful! 😄 Any feedback will be appreciated!

**Comment by esommars** [comment]
> @esommars, the feature was added, and a new version was released (9.1.8)! :) Thank you for drawing attention to this!

Very nice! :)

**Comment by korthout** [comment]
This is great! Thanks a lot 🚀 

> Any feedback will be appreciated!

I'll make sure to reach out if we run into any issues.
