### ISSUE TITLE
Support for Predefined Schedules extension

### ISSUE THREAD

**Issue by Spikhalskiy** [jmrozanec/cron-utils#505]
Some cron parsers do support predefined schedules like
`@yearly`, `@monthly`, `@weekly`, etc

For example:
https://pkg.go.dev/github.com/robfig/cron#hdr-Predefined_schedules
https://linux.die.net/man/5/crontab Section #Extensions

Would be great to get them in cron-utils

**Comment by jmrozanec** [comment]
@Spikhalskiy thank you for this idea. We will work on this functionality. Help is always welcome! 😄

**Comment by Spikhalskiy** [comment]
@jmrozanec Thanks for the confirmation! I will let you know if I have some time to work on it.

**Comment by jmrozanec** [comment]
@Spikhalskiy implemented! 😄 A release will follow soon. Thanks!

**Comment by jmrozanec** [comment]
@Spikhalskiy release 9.1.7 was published! Thanks! 😄
