### ISSUE TITLE
Suuport fro Japanese locale

### ISSUE THREAD

**Issue by harshadsindhav** [jmrozanec/cron-utils#510]
Hi Guys,
Kudos for fantastic work!!
Do we have any planning for Japanese locale support ? Are we planning this ?
Thank You for your support.
-Harshad

**Comment by jmrozanec** [comment]
@harshadsindhav thanks! 😄 If you are willing to contribute to the locale, we will be glad to merge and release a version. Do we have a deal? 😄

**Comment by jmrozanec** [comment]
@harshadsindhav supported! A new release is coming soon! 😄

**Comment by jmrozanec** [comment]
@harshadsindhav release 9.1.7 was published!
