### ISSUE TITLE
Get fire count between two dates

### ISSUE THREAD

**Issue by aloifolia** [jmrozanec/cron-utils#514]
It would be useful to not only be able to calculate one adjacent execution time but either 
- to get a full range of execution times between two specified dates (like in the [Quartz library](https://www.quartz-scheduler.org/api/2.1.7/org/quartz/TriggerUtils.html#computeFireTimesBetween(org.quartz.spi.OperableTrigger,%20org.quartz.Calendar,%20java.util.Date,%20java.util.Date))) or
- to get a count of execution times between two specified dates.

Is this something that could be implemented efficiently? The only bad workaround for this functionality with cron-utils (that I found) is to iteratively jump from date to the next via the `lastExecution` method.

**Comment by jmrozanec** [comment]
@aloifolia thank you for the suggestion. We agree this could be useful, but at the same time could lead to an explosion of results (e.g., every second execution within a year). A count could be much more efficient. We are open to discussing and implementing such a feature. Ideas and contributions are welcome! 😄

**Comment by lodenrogue** [comment]
I'm trying to understand the request here. You want a number of times a given cron expressions **will** trigger between two given dates?

**Comment by jmrozanec** [comment]
@lodenrogue Both are requested 😄 If you have time to implement any of those, it would be a great addition to the library! 🚀

**Comment by lodenrogue** [comment]
@jmrozanec Sure. I can work on that. Where in the code do you think it would fit best? I just discovered this repo yesterday so I'm not too familiar with the code yet..

**Comment by lodenrogue** [comment]
@jmrozanec Gave it a best guess: https://github.com/jmrozanec/cron-utils/pull/524

**Comment by jmrozanec** [comment]
@lodenrogue thanks! We merged it into master! 😄 Some improvements may be required for large intervals and frequent executions, but for now, we at least support this functionality. Thanks! 😄

**Comment by lodenrogue** [comment]
My pleasure!
