### ISSUE TITLE
Add thread safety info to javadoc

### ISSUE THREAD

**Issue by YotillaAntoni** [jmrozanec/cron-utils#515]
Currently, classes like `CronParser` or `CronDefinition` that must be build to parse expressions looks like they are thread safe. But the javadoc or the documentation doesn't say it anywhere.

It would be nice if the javadoc stated this if they indeed are thread safe, and there are no plans to make them mutable, because library users could safely assume that they only need an instance of this classes and don't need to build them every time.

**Comment by jmrozanec** [comment]
@YotillaAntoni thank you for the suggestion! We just documented the thread-safety for both proposed classes. Best!

**Comment by jmrozanec** [comment]
@YotillaAntoni release 9.1.7 was published!
