### ISSUE TITLE
Input Validation Vulnerability in Dependency

### ISSUE THREAD

**Issue by echristeson** [jmrozanec/cron-utils#517]
`org.glassfish:javax.el:3.0.0` has an input validation vulnerability
[SNYK-JAVA-ORGGLASSFISH-2841368](https://security.snyk.io/vuln/SNYK-JAVA-ORGGLASSFISH-2841368
)
It has been [fixed in 3.0.4](https://github.com/jakartaee/expression-language/pull/160#issuecomment-900834537) but it appears that the project changed to `org.glassfish.jakarta.el`

**Comment by jmrozanec** [comment]
@echristeson fixed!

**Comment by cykirsch** [comment]
@jmrozanec Thanks! Do you have a timeline in mind for your next release?

**Comment by jmrozanec** [comment]
@cykirsch let's aim for this weekend! 😄 We will update you, when released!

**Comment by jmrozanec** [comment]
@cykirsch @echristeson release 9.1.7 was published!
