### ISSUE TITLE
Expressions containing multiple days of the week are not handled correctly.

### ISSUE THREAD

**Issue by dwilkie81** [jmrozanec/cron-utils#52]
For cron expressions where multiple days of the week are defined, the lastExecution can be wrong.  For example the expression "* * * * 1,2" which should run every minute on Mondays and Tuesdays will actually be treated as running every minute on the 1st and 2nd of the month.

This appears to be due to FieldValueGeneratorFactory not handling "And" expressions correctly for Day of Week.  On/Between expressions are handled by specific OnDayOfWeekValueGenerator and BetweenDayOfWeekValueGenerate, but And expressions are handled by the AndFieldValueGenerator.

**Comment by jmrozanec** [comment]
@dwilkie81 Thank you for reporting and providing a fix for this! A new version was released with it!
