### ISSUE TITLE
Could cron-utils support x weeks to execute

### ISSUE THREAD

**Issue by Nordlichtwzx** [jmrozanec/cron-utils#525]

**Comment by jmrozanec** [comment]
@Nordlichtwzx could you provide a more informative description, and perhaps some examples or a test case? 😄  Thanks!

**Comment by jmrozanec** [comment]
@Nordlichtwzx may we ask for some additional details regarding this task? If no more details are provided, we will close the issue due to insufficient context. Thanks! 😄

**Comment by Nordlichtwzx** [comment]
just like every two weeks wednesdays and Thursdays to execute

**Comment by jmrozanec** [comment]
@Nordlichtwzx thanks! 😄

**Comment by Spikhalskiy** [comment]
Same as https://github.com/jmrozanec/cron-utils/issues/506

**Comment by jmrozanec** [comment]
https://stackoverflow.com/questions/46109358/how-to-create-a-cron-expression-for-every-2-weeks

**Comment by jmrozanec** [comment]
Closing as a duplicate of issue #506
