### ISSUE TITLE
Next execution for day of week seems to be wrong

### ISSUE THREAD

**Issue by kpgalligan** [jmrozanec/cron-utils#54]
I just started using the library, but the first test I ran seems to fail.  I'm trying to specify minute, hour of day, and day of week.  It looks like late in month has trouble.  Using version 3.1.2.  If I get some time I'll try to dig, but it'll be a bit before that happens.

See the following.

public class ScheduleHelperTest
{
    DateFormat dfSimple = new SimpleDateFormat("hh:mm:ss MM/dd/yyyy a");
    DateFormat df = new SimpleDateFormat("hh:mm:ss EEE, MMM dd yyyy a");

    @Test
    public void testBasicCron() throws ParseException
    {
        printDate("3:15:00 11/20/2015 PM");
        printDate("3:15:00 11/27/2015 PM");
//        printDate("3:15:00 11/29/2015 PM");
//        printDate("3:15:00 11/30/2015 PM");
//        printDate("3:15:00 12/01/2015 PM");
//        printDate("3:15:00 12/02/2015 PM");
//        printDate("3:15:00 12/29/2015 PM");
//        printDate("3:15:00 12/30/2015 PM");
//        printDate("3:15:00 12/31/2015 PM");
    }

    private void printDate(String startDate) throws ParseException
    {
        Date now = dfSimple.parse(startDate);
        System.out.println("Starting: "+ df.format(now));
        printNextDate(now, "0 6 * * 0");//Sunday
        printNextDate(now, "0 6 * * 1");
        printNextDate(now, "0 6 * * 2");
        printNextDate(now, "0 6 * * 3");
        printNextDate(now, "0 6 * * 4");
        printNextDate(now, "0 6 * * 5");
        printNextDate(now, "0 6 * * 6");
    }

    private void printNextDate(Date now, String cronString)
    {
        Date date = nextSchedule(cronString, now);
        System.out.println("Next time: " + df.format(date));
    }

    public static Date nextSchedule(String cronString, Date lastExecution)
    {
        DateTime now = new DateTime(lastExecution);
        CronParser cronParser =new CronParser(
                CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX));
        Cron cron = cronParser.parse(cronString);

        ExecutionTime executionTime = ExecutionTime.forCron(cron);
        DateTime nextExecution = executionTime.nextExecution(now);

        return nextExecution.toDate();
    }
}

Starting: 03:15:00 Fri, Nov 20 2015 PM
Next time: 06:00:00 Sun, Nov 22 2015 AM
Next time: 06:00:00 Mon, Nov 23 2015 AM <-- As expected, one day later
Next time: 06:00:00 Tue, Nov 24 2015 AM
Next time: 06:00:00 Wed, Nov 25 2015 AM
Next time: 06:00:00 Thu, Nov 26 2015 AM
Next time: 06:00:00 Fri, Nov 27 2015 AM
Next time: 06:00:00 Sat, Nov 21 2015 AM
Starting: 03:15:00 Fri, Nov 27 2015 PM
Next time: 06:00:00 Sun, Nov 29 2015 AM
Next time: 06:00:00 Mon, Dec 07 2015 AM <-- Jumps an extra week
Next time: 06:00:00 Tue, Dec 08 2015 AM
Next time: 06:00:00 Wed, Dec 02 2015 AM
Next time: 06:00:00 Thu, Dec 03 2015 AM
Next time: 06:00:00 Fri, Dec 04 2015 AM
Next time: 06:00:00 Sat, Nov 28 2015 AM

**Comment by jmrozanec** [comment]
@kpgalligan Thank you for reporting this! Let me know if you get time to dig into this! Fixes are always welcome!

**Comment by fsi206914** [comment]
Was ready to use cron-utils, but found this bug. Any idea where goes wrong? I may take a look. @jmrozanec

**Comment by jmrozanec** [comment]
@kpgalligan @fsi206914 issue solved! @fsi206914 you can now use cron-utils ;)
Kudos to @thachhoang for providing the solution!

**Comment by jmrozanec** [comment]
@kpgalligan @fsi206914 @thachhoang [Version 4.1.1](https://github.com/jmrozanec/cron-utils/releases/tag/4.1.1) was released with this fixes!
