### ISSUE TITLE
pom.xml.jdk16 not tested?

### ISSUE THREAD

**Issue by mccartney** [jmrozanec/cron-utils#544]
It seems like the copy of the Maven configuration file: `pom.xml.jdk16` is not tested by Github actions at all. Not sure if this is intended, but it seems like nothing is checking the soundness of that file.

**Comment by jmrozanec** [comment]
@mccartney, currently, that pom is not used. We may get back to it to update the project according to the JDK 17 (LTS). When updating to a newer LTS JDK, we weigh to what extent the JDK is adopted in production settings to ensure the library can be used by most projects.
