### ISSUE TITLE
UNIX Cron to QUARTZ expressions incorrect

### ISSUE THREAD

**Issue by chasegawa** [jmrozanec/cron-utils#56]
Quartz does not support specifying both a day-of-week and a day-of-month value (you must currently use the '?' character in one of these fields).

For example: 0 0 0 * * 1 * is *not* legal in quartz, instead it must be: 0 0 0 ? * 1 * 

Code such as: 
```java
        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX);
        CronDefinition quartzDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
        CronMapper cronMapper = new CronMapper(cronDefinition, quartzDefinition);
        CronParser cronParser = new CronParser(cronDefinition);
        Cron cronCron = cronParser.parse(cronString);
        Cron quartzCron = cronMapper.map(cronCron);
        String result = quartzCron.asString();
```
Will take 0 0/2 * * * and produce 0 /2 * * * * - it should be 0 /2 * * ? * (or possibly 0 /2 ? * * *)

Using quartz 2.2.2 and cron-utils 3.1.2

**Comment by jmrozanec** [comment]
@chasegawa Thank you for reporting this! Just for the record: the issue is similar to the one reported in #36 
Contributions are welcome!

**Comment by jmrozanec** [comment]
@chasegawa we fixed the issue! Thanks for reporting it!

**Comment by jmrozanec** [comment]
@chasegawa New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
