### ISSUE TITLE
BetweenDayOfWeekValueGenerator does not work for the first day of a month in some cases.

### ISSUE THREAD

**Issue by rtennantventuretech** [jmrozanec/cron-utils#57]
With this CronDefinition:
```
CronDefinitionBuilder.defineCron()
            .withMinutes().and()
            .withHours().and()
            .withDayOfMonth()
                .supportsL().supportsW()
                .and()
            .withMonth().and()
            .withDayOfWeek()
                .withMondayDoWValue(1)
                .withValidRange(1, 7)
                .supportsHash().supportsL()
                .and()
            .withYear().and()
                .lastFieldOptional()
```

and this cron expression:
`"30 3 * * MON-FRI"`

`executionTime.nextExecution(1970-01-01....)` returns 1970-01-02... instead of 1970-01-01. It seems to always do this on when the first day of the month falls within the DoW range. It looks like an initial case type bug. The BetweenDayOfWeekValueGenerator will never return the value 1 in this case - only the value 8.

The result is that if I execute this over the year of 1970, I'd expect to get 261 days. Instead I get 245 days. 

Based on this bug for the year 1970, I'd expect to lose 8 days. I'm losing 16 days though. Taking a quick look at the output, it appears the same issue exists for the last day of the month when the last day falls within the DoW range. For example, cron-utils will not return 1970-07-31 (a Friday) for the above cron expression.

**Comment by jmrozanec** [comment]
Calendar for January 1970:

Su   | Mo	   | Tu    | We    | Th    | Fr    | Sa 
------ | ------- | ------ | ------- | ------- | ------- | ------
xx 	| xx 	| xx 	| xx 	| 01	| 02	| 03 
04	| 05	| 06	| 07	| 08	| 09	| 10 
11	| 12	| 13	| 14	| 15	| 16	| 17 
18	| 19	| 20	| 21	| 22	| 23	| 24 
25	| 26	| 27	| 28	| 29	| 30	| 31

**Comment by jmrozanec** [comment]
@rtennantventuretech Fixed!

**Comment by jmrozanec** [comment]
@rtennantventuretech New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
