### ISSUE TITLE
Incorrect parsing of step values: "0 1/2 * * *" -> "0 /2 * * *"

### ISSUE THREAD

**Issue by dimw** [jmrozanec/cron-utils#58]
When using UNIX cron type (other not tested), the cron parser produces incorrect values for some step values (the one with slashes), e.g.:

Input | Parser output | Comment
------------ | ------------- | ---
```0 0/1 * * *``` |  ```0  * * *``` | The hour field is missing/empty.
```0 1/2 * * *``` | ```0 /2 * * *``` | The hour field should remain 1/2.
```0/1 * * * *```  |  ```* * * *``` | The minute field is missing/emtpy.
```1/2 * * * *``` | ```/2 * * * *``` | The minute field should remain 1/2.

Test used with cron-utils:3.1.2:
```java
public class StepValuesTest {

    private CronParser cronParser;

    @Before
    public void setup() {
        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX);
        cronParser = new CronParser(cronDefinition);
    }

    @Test
    public void everyEvenHourShouldBeParsedCorrectly() {
        Cron cron = cronParser.parse("0 0/1 * * *");
        assertThat(cron.asString(), anyOf(is("0 0/1 * * *"), is("0 /1 * * *"), is("0 * * * *")));
    }

    @Test
    public void everyOddHourShouldBeParsedCorrectly() {
        Cron cron = cronParser.parse("0 1/2 * * *");
        assertThat(cron.asString(), is("0 1/2 * * *"));
    }

    @Test
    public void everyEvenMinuteShouldBeParsedCorrectly() {
        Cron cron = cronParser.parse("0/1 * * * *");
        assertThat(cron.asString(), anyOf(is("0/1 * * * *"), is("/1 * * * *"), is("* * * * *")));
    }

    @Test
    public void everyOddMinuteShouldBeParsedCorrectly() {
        Cron cron = cronParser.parse("1/2 * * * *");
        assertThat(cron.asString(), is("1/2 * * * *"));
    }

}
```

**Comment by jmrozanec** [comment]
@dimw thank you for reporting this issue and providing unit tests to reproduce it!

**Comment by jmrozanec** [comment]
@dimw New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
