### ISSUE TITLE
Can we have a release?

### ISSUE THREAD

**Issue by J0B10** [jmrozanec/cron-utils#580]
Sorry to bother, but since #534 and #531 I'm waiting for a release and nothing happened so far. 😅 

In fact BetonQuest/BetonQuest#2319 is on our Backlog since july last year and still blocked due to a missing release. 

So I would greatly appreciate it if you could release a new version of cron-utils in the near future.

Thanks for your work!

**Comment by jmrozanec** [comment]
@J0B10 sure. You can expect a release in the following days. Best!

**Comment by Wolf2323** [comment]
Hey, i am also from BetonQuest and i want to give you a little push on that topic ;)

**Comment by jmrozanec** [comment]
@Wolf2323 @J0B10 @SaltyAimbOtter, we apologize for the delay. We will be releasing a new version today.

**Comment by SaltyAimbOtter** [comment]
It has been a rather long day :wink:

**Comment by jmrozanec** [comment]
@SaltyAimbOtter Indeed, we confirm it has been a long day! 😅 But now we have released a new version! 😃 @J0B10 @SaltyAimbOtter @Wolf2323 [release 9.2.1 is out!](https://central.sonatype.com/artifact/com.cronutils/cron-utils/9.2.1). We appreciate your patience. We are grateful you pushed us to release a new version! 😎
