### ISSUE TITLE
Cron Field endRange may not be correct

### ISSUE THREAD

**Issue by renliangyu857** [jmrozanec/cron-utils#602]
![企业微信截图_16850064062768](https://github.com/jmrozanec/cron-utils/assets/28523136/61dbdc9a-bae2-41ae-a007-9ae16015925c)
the second/minute endRange maybe 60
the hour endRange maybe 24
the week endRange maybe 7 ?

**Comment by jmrozanec** [comment]
@renliangyu857 depends on the Cron definition. E.g., [crontab](https://manpages.ubuntu.com/manpages/bionic/man5/crontab.5.html) accepts a range of 0-7, but with 0=7, which makes an effective cron range of 0-6 with mapping 7->0. If you find a case where the cron does not behave as expected, we will be grateful for a PR with the test case. Meanwhile, we close this issue.
