### ISSUE TITLE
both a day-of-week AND a day-of-month parameter should fail for QUARTZ

### ISSUE THREAD

**Issue by francisdb** [jmrozanec/cron-utils#63]
CronExpression `0 30 17 4 1 * 2016` is invalid for quartz but parsing succeeds using cron-utils in quartz mode

Error reported by quartz:
`Support for specifying both a day-of-week AND a day-of-month parameter is not implemented.`

**Comment by jmrozanec** [comment]
@francisdb thank you for reporting the issue.

**Comment by jmrozanec** [comment]
@francisdb We fixed the issue! Will be releasing a new version soon.

**Comment by jmrozanec** [comment]
@francisdb New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)

**Comment by francisdb** [comment]
thanks

**Comment by tomqwpl** [comment]
The constraint causes an NPE if you don't have a DAY_OF_WEEK field at all.
I'm constructing a cron expression using the builder API, providing a day-of-month value but no day-of-week value, and it causes an NPE.

**Comment by jmrozanec** [comment]
@tomqwpl thank you for the insight! If you have time for a quick PR we merge it to master and release s new version with the fix. Thanks!
