### ISSUE TITLE
Incorrect next execution time for ranges

### ISSUE THREAD

**Issue by Joao-Neves** [jmrozanec/cron-utils#64]
Next execution time is not being computed correctly for ranges:

```
        final CronType cronType = CronType.QUARTZ;
        final CronParser quartzParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(cronType));
        ExecutionTime executionTime = ExecutionTime.forCron(quartzParser.parse("* 10-20 * * * * 2099"));
        DateTime nextTime = executionTime.nextExecution(DateTime.now());
        assertNotNull(nextTime);
        assertEquals(10, nextTime.getMinuteOfHour());
```

This yields:
```
java.lang.AssertionError: 
Expected :10
Actual   :11
```
On the last assertion.

**Comment by jmrozanec** [comment]
@Joao-Neves thank you for reporting this!

**Comment by kallem** [comment]
@jmrozanec I'd like to also contribute on this library. Is there a channel for general discussion somewhere? I have some general questions which are not related to exactly only single issue.

**Comment by jmrozanec** [comment]
@kallem sure! Feel free to ask questions at [gitter](https://gitter.im/jmrozanec/cron-utils). We use that chat for general questions, and to announce new releases.

**Comment by jmrozanec** [comment]
@Joao-Neves @kallem Fixed!
