### ISSUE TITLE
Getting next execution fails on leap-year when using day-of-week

### ISSUE THREAD

**Issue by HughJeffner** [jmrozanec/cron-utils#69]
Noticed this behavior today:

```
CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX));
ExecutionTime time = ExecutionTime.forCron(parser.parse("0 * * * 1-5"));
time.nextExecution(new DateTime(2016, 2, 29, 11, 0));
```
Expected output: 2016-02-29T12:00:00.000-06:00
Actual output: 2016-03-02T00:00:00.000-06:00

Omitting the day-of-week specifier in the crontab returns the correct result.

**Comment by HughJeffner** [comment]
Maybe related to #54?  I only just noticed the strange result today (Feb29) so I just assumed it was an edge case.

**Comment by jmrozanec** [comment]
@HughJeffner thank you for reporting this. When possible, can you submit a pull request with the tests to verify it?

**Comment by jmrozanec** [comment]
@HughJeffner Fixed!

**Comment by HughJeffner** [comment]
Nice, thanks for the fast response!

**Comment by jmrozanec** [comment]
@HughJeffner you are welcome!
