### ISSUE TITLE
Illegal question mark value on cron pattern assumed valid.

### ISSUE THREAD

**Issue by DanoOM** [jmrozanec/cron-utils#70]
(Version 3.1.5) 
Given the following Cron Expression: 0 0 12 1W ?
And calling ExecutionTime.nextExecution(DateTime) (Using CronType.Quartz), generates the following exception:

java.lang.IllegalArgumentException: Values must not be empty
at org.apache.commons.lang3.Validate.notEmpty(Validate.java:300)
at com.cronutils.model.time.TimeNode.<init>(TimeNode.java:31)
at com.cronutils.model.time.ExecutionTime.generateDays(ExecutionTime.java:304)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:142)
at com.cronutils.model.time.ExecutionTime.nextExecution(ExecutionTime.java:123) 

note calling the validator/descriptor both yield valid results.  
(Also I tested this on non leap-years same result).

**Comment by jmrozanec** [comment]
@DanoOM thank you for reporting the issue. You are most welcome to contribute a test for it, and help us find a solution.

**Comment by jmrozanec** [comment]
@DanoOM Issue fixed. The real cause for it, was that we were accepting '?' value on fields where was invalid. Fixing that we get a correct behavior. Please notice, I slightly modified the cron expression you gave, to match Quartz definition (a field was missing) in such a way that I could reproduce the issue. After debugging we solved it by checking if '?' value was valid for field being parsed.
