### ISSUE TITLE
Stacktrace printed

### ISSUE THREAD

**Issue by francisdb** [jmrozanec/cron-utils#72]
I guess this should not happen?

https://github.com/jmrozanec/cron-utils/blob/dfbf4127afd2c28b6e44a76e2379be59e6137556/src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java#L70
```
com.cronutils.model.time.generator.NoSuchValueException
	at com.cronutils.model.time.generator.EveryFieldValueGenerator.generateNextValue(EveryFieldValueGenerator.java:43)
	at com.cronutils.model.time.generator.EveryFieldValueGenerator.generateCandidatesNotIncludingIntervalExtremes(EveryFieldValueGenerator.java:67)
	at com.cronutils.model.time.generator.FieldValueGenerator.generateCandidates(FieldValueGenerator.java:55)
	at com.cronutils.model.time.ExecutionTimeBuilder.forMinutesMatching(ExecutionTimeBuilder.java:51)
	at com.cronutils.model.time.ExecutionTime.forCron(ExecutionTime.java:92)
```

**Comment by jmrozanec** [comment]
@francisdb this should not happen :) Fixed!

**Comment by jmrozanec** [comment]
@francisdb If no value exists in interval, we return an empty list. Exception should not take place. We may log it to keep track of such a case, just to be sure to have information on potential bug. Maybe I am missing something?

**Comment by francisdb** [comment]
Happens somewhere deep in our tests, need to have a look

**Comment by jmrozanec** [comment]
@francisdb ok

**Comment by francisdb** [comment]
Here is code to reproduce the issue

```java
String cronText = "0 0/15 * * * ?";
CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
Cron cron = parser.parse(cronText);
CronExpression.validateExpression(cronText);
final ExecutionTime executionTime = ExecutionTime.forCron(cron);
```

**Comment by jmrozanec** [comment]
@francisdb Thank you! Will add the corresponding test.

**Comment by augusto-altman** [comment]
When this fix is going to be released?

**Comment by jmrozanec** [comment]
@augusto-altman Hello Augusto, we have no fix for it yet. I may have a look to this issue during weekend, but cannot guarantee to solve it. Anyway, a new release will be created until Sunday, with some new issues we fixed. If you have some spare time, you are always welcome to contribute.

**Comment by jmrozanec** [comment]
@augusto-altman I could not manage to get a release done by today. Will release over the week.

**Comment by augusto-altman** [comment]
@jmrozanec No problem! Thank you very much :D

**Comment by thachhoang** [comment]
> The expected behavior in that part of the code is that if no value exists in interval, we should return an empty list. Exceptions should not take place.

This line: https://github.com/jmrozanec/cron-utils/blob/be89265e0b9066f6ccc985e26f56abc9f95e82b2/src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java#L79

I think the exception is actually used as a stopping condition for the while loop. Compare another generator class, where the same exception is simply swallowed:

https://github.com/jmrozanec/cron-utils/blob/be89265e0b9066f6ccc985e26f56abc9f95e82b2/src/main/java/com/cronutils/model/time/generator/OnDayOfMonthValueGenerator.java#L64

**Comment by jmrozanec** [comment]
@francisdb @augusto-altman The observation @thachhoang made is accurate. Added some comments to code and removed the log causing confusion. @thachhoang thank you for looking into this!
