### ISSUE TITLE
nextExecution not working as expected for several patterns

### ISSUE THREAD

**Issue by ole108** [jmrozanec/cron-utils#77]
This code:

    package com.something.test;

    import org.joda.time.DateTime;
    import com.cronutils.model.definition.CronDefinition;
    import com.cronutils.model.definition.CronDefinitionBuilder;
    import com.cronutils.model.time.ExecutionTime;
    import com.cronutils.model.time.generator.NoSuchValueException;
    import com.cronutils.parser.CronParser;

    public class CronUtilsTests {

        private static CronDefinition cronDefinition =
                CronDefinitionBuilder.defineCron()
                        .withMinutes().and()
                        .withHours().and()
                        .withDayOfMonth()
                        .supportsHash().supportsL().supportsW().supportsQuestionMark().and()
                        .withMonth().and()
                        .withDayOfWeek()
                        .withIntMapping(7, 0)
                        .supportsHash().supportsL().supportsW().supportsQuestionMark().and()
                        .lastFieldOptional()
                        .instance();

        private static String every2hours =     "0 0/2 * * ?";          // every 2 hours, every day
        private static String daily =           "0 8 1/1 * ?";          // 0800 everyday
        private static String weekly =          "0 8 ? * MON";          // 0800 every monday
        private static String every8Days =      "0 8 1/8 * ?";          // weekly event, fridays, march-may

        public static void main(String[] args) throws NoSuchValueException {
            testCronPattern(daily);             // works fine
            testCronPattern(every2hours);       // dont work (loops through same day of month)
            testCronPattern(weekly);            // loops through dates of same month
            testCronPattern(every8Days);        // loops through dates of same month
        }

        private static void testCronPattern(String pattern) {
            CronParser parser = new CronParser(cronDefinition);
            DateTime next = DateTime.now();
            int counter = 0;
            ExecutionTime executionTime = ExecutionTime.forCron(parser.parse(pattern));

            System.out.println("\nstart calculating time for: " + pattern);

            while (counter < 20) {
                try {
                    next = executionTime.nextExecution(next);
                    System.out.println("start: " + next.toString().substring(0, 10) + " - " + next.toString().substring(11, 16));
                    counter++;
                } catch (IllegalArgumentException e) {
                    counter = 50;
                }
            }
        }

    }
​
Produces the right result for the first pattern (daily). But for all others the result goes wrong (never the first execution of executionTime.nextExecution, though).
.nextExecution(...) jumps back in time at some "barrier":

- For every2hours it stays on the same day and doesn't report midnight at all.
- For weekly it stays in the same month (so it jump back in the same month instead of going to the next month).
- For every8Days it does the same as for weekly. Just reported because it is a second way to trigger the problem.

**Comment by falkorichter** [comment]
:+1:

**Comment by jmrozanec** [comment]
@ole108 thank you for reporting the issue and for the examples provided.

**Comment by ole108** [comment]
We accidentally used an outdated version of con-utils (3.1.0) instead of 3.1.6.
We are experiencing no problems with 3.1.6. :smile: 

So sorry for the report. I am closing it now.

**Comment by jmrozanec** [comment]
@ole108 thanks!
