### ISSUE TITLE
ExecutionTime.forCron fails on pattern "0 0/30 * * * ?"

### ISSUE THREAD

**Issue by rwiesemann** [jmrozanec/cron-utils#78]
I use cronutils version *3.6.1*.
The Crontype.QUARTZ pattern "0 0/30 * * * ?" fails on 
````
CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor( CronType.QUARTZ );
CronParser parser = new CronParser( cronDefinition );
Cron cron = parser.parse( "0 0/30 * * * ?" );
ExecutionTime time = ExecutionTime.forCron( cron );
Duration timeToNextExecution = time.timeToNextExecution( DateTime.now() );
````
with exception

````
14:22:35,227 ERROR [STDERR] com.cronutils.model.time.generator.NoSuchValueException
14:22:35,228 ERROR [STDERR]     at com.cronutils.model.time.generator.EveryFieldValueGenerator.generateNextValue(EveryFieldValueGenerator.java:43)
14:22:35,228 ERROR [STDERR]     at com.cronutils.model.time.generator.EveryFieldValueGenerator.generateCandidatesNotIncludingIntervalExtremes(EveryFieldValueGenerator.java:67)
14:22:35,229 ERROR [STDERR]     at com.cronutils.model.time.generator.FieldValueGenerator.generateCandidates(FieldValueGenerator.java:55)
14:22:35,229 ERROR [STDERR]     at com.cronutils.model.time.ExecutionTimeBuilder.forMinutesMatching(ExecutionTimeBuilder.java:51)
14:22:35,230 ERROR [STDERR]     at com.cronutils.model.time.ExecutionTime.forCron(ExecutionTime.java:92)
14:22:35,230 ERROR [STDERR]     at de.psi.messaging.purge.MessagePurgeTrigger.getDelay(MessagePurgeTrigger.java:35)
````

**Comment by jmrozanec** [comment]
@rwiesemann thank you for reporting this. You are welcome to help on the issue contributing a test for it.

**Comment by maehld** [comment]
I've run into the same problem. Apparently your code is throwing NoSuchValueExceptions but catches them in EveryFieldValueGenerator.generateCandidatesNotIncludingIntervalExtremes. As the resulting execution times are OK in my testing I would recommend not logging the exception as it seems to be a normal case with intervals. Getting rid of the exception completely would be perhaps even better.

FYI the test cases also encounter the exception when running but as you've not configured logging in your test cases they do not show on the console.

If you're interesed I would be happy to provide a pull request for a rework without the exception.

Thanks

Dominik

**Comment by kostapc** [comment]
Same issue with any intervals.
test code: https://gist.github.com/kostapc/3917d8ec50af8bf665023145456db5d5

**Comment by kostapc** [comment]
@maehld can you please public your fixes, maybe on your fork - i will pick it. Right now i work with this issue.

**Comment by maehld** [comment]
Hi. I will try to get a fork working by tomorrow.

**Comment by jmrozanec** [comment]
@maehld @kostapc Thank you both for working on this issue. I would be happy to receive your PR and merge to master if you provide a working solution for it.

**Comment by jmrozanec** [comment]
@maehld @kostapc I just merged a bigger refactor into master branch. Please check and update your forks, to avoid working on a stale version. Looking forward to your patch!

**Comment by jmrozanec** [comment]
@maehld @kostapc Just created a [new branch](https://github.com/jmrozanec/cron-utils/tree/issue58), where some changes were introduced to fix issue #58 that may be related to this same problem. Not merging into master yet, since there are some tests failing. A review over introduced changes and additional fixes would be welcome.

**Comment by kostapc** [comment]
@jmrozanec thanks a lot for you work!

**Comment by maehld** [comment]
I will have a look tomorrow at the branch. Sorry for not getting something to work by friday but work got in the way.

**Comment by jmrozanec** [comment]
@maehld sure! No problem!

**Comment by jmrozanec** [comment]
@maehld @kostapc Just merged a new refactor into master. Minor changes were introduced into the model on how we represent Always, Every and Between; in order to have a more natural representation of the cron in the model.

**Comment by kostapc** [comment]
i fix log level in some cases and provide extended tests valued for me. @jmrozanec - you do all main work! Thank a lot! Waiting for next release in maven repo.

**Comment by jmrozanec** [comment]
@kostapc @maehld @rwiesemann Merged! Thank you for contributing to cron-utils!

**Comment by jmrozanec** [comment]
@kostapc @maehld @rwiesemann new version released!
