### ISSUE TITLE
calculated execution date is wrong

### ISSUE THREAD

**Issue by emmanueltouzery** [jmrozanec/cron-utils#79]
this might be a duplicate of bug #54.

I attach  reproduction program showing the issue.
If you run it with `mvn exec:java`, the output is `2014-12-08T08:00:00.000+01:00`.

but I would expect it to be the 1st of december. The cron expression is unix "0 8 * * 1" (8:00 on mondays), and I give the start date of 2014-11-30 (which was a sunday).

So the date I get is good, but I don't understand why the the december 1st was skipped...

[cronutilsbug.zip](https://github.com/jmrozanec/cron-utils/files/208187/cronutilsbug.zip)

**Comment by jmrozanec** [comment]
@emmanueltouzery thank you for reporting this! Will try to have a look at it over the weekend. You are welcome to contribute a test for this specific case.

**Comment by jmrozanec** [comment]
@emmanueltouzery thanks!

**Comment by jmrozanec** [comment]
@emmanueltouzery @lpbak contributed a fix to the issue! Will be available soon, with the next cron-utils release! Thanks @lpbak !
