### ISSUE TITLE
Support Java 8 time

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#8]
Current implementation was developed using joda-time, since provides great date and time utils. 
A new date, time and calendar API was released at Java 8. Since we want to keep compatibility with previous JDK versions, we want to maintain a branch with joda-time dependency, and another to leverage the new Java 8 API.

**Comment by jmrozanec** [comment]
@JensWalter thanks for forking cron-utils! Would you mind merging forked changes into a new branch?

**Comment by JensWalter** [comment]
Sure, but so far I didn't came to the point where I could actually test my implementation. So far I only got to the point where it compiles.
So I could merge it back, but the current status is rather experimental. So should I merge back or first try to test a little more?

**Comment by jmrozanec** [comment]
Please try to test it more. Quality matters! Thanks!

**Comment by jmrozanec** [comment]
Once we have this branch, it would be great to setup different classifiers, to produce compatible versions for different JDKs. A resource on this [here](http://stackoverflow.com/questions/3092085/building-same-project-in-maven-with-different-artifactid-based-on-jdk-used)

**Comment by jmrozanec** [comment]
@JensWalter Hi! are you still willing to migrate this project to JDK8?
If doing so, it would be an opportunity to get rid of guava, since there were some complaints on how heavy that dependency is, and in JDK8 we have full support for Functions.

**Comment by jmrozanec** [comment]
We are migrating cron-utils to JDK8. This task will be developed on branch [jdk8](https://github.com/jmrozanec/cron-utils/tree/jdk8) 
With this migration effort we are also removing guava dependency, in order to avoid unnecessary dependencies on libraries.

**Comment by jmrozanec** [comment]
Migration to JDK8 was done. Replacing JodaTime for Java Time remains.

**Comment by espiegel** [comment]
For replacing JodaTime with Java 8's API do we want to migrate all methods that return a joda time "DateTime" object with Java 8's "LocalDateTime" or "ZonedDateTime" ?

I'm leaning towards "LocalDateTime". Just wondering what are your thoughts on this matter.

**Comment by jmrozanec** [comment]
@espiegel we are willing to replace all methods regarding Jodatime "DateTime". This would be a major change. I would lean towards ZonedDateTime, since better reflects behavior "DateTime" provides us today. Note that there are several cases, where DateTime gives us a notion of timezone where the time was being used.

**Comment by espiegel** [comment]
@jmrozanec Sounds good, I'll get started on that later this week.

**Comment by jmrozanec** [comment]
@espiegel Great! Looking forward to merge the changes!

**Comment by jmrozanec** [comment]
@JensWalter The feature was contributed by @espiegel at [PR#107](https://github.com/jmrozanec/cron-utils/pull/107) Thank you @espiegel for tackling this!
