### ISSUE TITLE
Bug: candidate values are false when combining Range, and multiple Patterns

### ISSUE THREAD

**Issue by f-aubert** [jmrozanec/cron-utils#83]
Hello,

The following test fails:
CronParser cronParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(com.cronutils.model.CronType.QUARTZ));
        assertEquals(ExecutionTime.forCron(cronParser.parse("* * 21-23,0-4 * * *")).isMatch(new DateTime(2014, 9, 20, 20, 0, 0)), false); // test Fail!!!
        assertEquals(ExecutionTime.forCron(cronParser.parse("* * 21-23,0-4 * * *")).isMatch(new DateTime(2014, 9, 20, 21, 0, 0)), true);
        assertEquals(ExecutionTime.forCron(cronParser.parse("* * 21-23,0-4 * * *")).isMatch(new DateTime(2014, 9, 20, 0, 0, 0)), true);
        assertEquals(ExecutionTime.forCron(cronParser.parse("* * 21-23,0-4 * * *")).isMatch(new DateTime(2014, 9, 20, 4, 0, 0)), true);
        assertEquals(ExecutionTime.forCron(cronParser.parse("* * 21-23,0-4 * * *")).isMatch(new DateTime(2014, 9, 20, 5, 0, 0)), false); // test Fail!!!

Hints:
For a reason I can't explain the BetweenFieldValueGenerator.generateNextValue(int reference) Method, on line 31, make use of an 'Every' Object which in turns doesn't check on range to and from bounds.

Best regards

**Comment by jmrozanec** [comment]
@f-aubert thank you for reporting this! Won't you mind to send a pull request with the corresponding tests?

**Comment by abush** [comment]
I've created a pull request to resolve this issue here: https://github.com/jmrozanec/cron-utils/pull/85

**Comment by jmrozanec** [comment]
@abush Thank you for solving this issue! The pull request was merged into master. Within this weekend we release a new version of the library including your contribution!

**Comment by jmrozanec** [comment]
@f-aubert The issue was solved. We are releasing a new version with the fix this weekend!

**Comment by f-aubert** [comment]
Thanks you both for the patch, and the merge. Looking forward for the release.

**Comment by jmrozanec** [comment]
@f-aubert @abush New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
