### ISSUE TITLE
Reported error contains other expression than the one provided

### ISSUE THREAD

**Issue by francisdb** [jmrozanec/cron-utils#90]
parsing `0/1 * * * * *` for quartz returns

`Invalid CRON expression: Invalid cron expression: * * * * * *. Both, a day-of-week AND a day-of-month parameter, are not supported.`

I would expect the error to contain the actual expression

**Comment by jmrozanec** [comment]
@francisdb This is a bug. The message should return the expression. Thank you for reporting it!

**Comment by jmrozanec** [comment]
@francisdb Fixed!

**Comment by francisdb** [comment]
👍

**Comment by jmrozanec** [comment]
@francisdb The fix may not provide the same expression, but always one that is equivalent to the specified. Most times will be the same string.

**Comment by jmrozanec** [comment]
Fix published in [release 4.0.1](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.1)

**Comment by francisdb** [comment]
@jmrozanec then this still is confusing...

**Comment by francisdb** [comment]
with 5.0.5 we now get this:

`Failed to parse '0/1 * * * * *'. Invalid cron expression: 0 * * * * *. Both, a day-of-week AND a day-of-month parameter, are not supported.`

Which is ok for my part

**Comment by jmrozanec** [comment]
@francisdb great! Glad that you find the new message more useful. Thank you for the feedback!
