### ISSUE TITLE
Bad next execution time

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#92]
@tcn reported us the following issue:
Bad next execution time: this schedules for 7th of june rather than 31st of may. The exact location where things go wrong appears to be in generateCandidatesNotIncludingIntervalExtremes(), specifically the while(reference<end).

        final CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(UNIX));
        final DateTime now = DateTime.parse("2016-05-24T01:02:50");//.withTimeAtStartOfDay();
        //final DateTime now = DateTime.parse("2016-06-07T00:01:02");//.withTimeAtStartOfDay();
        final ExecutionTime executionTime = ExecutionTime.forCron(parser.parse("1 0 * * tue"));
        final Timestamp nextExecution = new Timestamp(executionTime.nextExecution(now).getMillis());
        System.out.println(nextExecution);

**Comment by tcn** [comment]
Changing the loop condition from < to <= actually works in this specific case. The method's name indicates that it's < on purpose, though.

**Comment by jmrozanec** [comment]
@tcn great! Will review the method and conditions. Thanks!

**Comment by jmrozanec** [comment]
@lpbak sure!

**Comment by jmrozanec** [comment]
@lpbak merged! I removed the Test annotation to avoid a failing test on our builds.

**Comment by fsi206914** [comment]
This should be related to #54 .They seem both jumping over the current week.

**Comment by fsi206914** [comment]
@tcn which class is the generateCandidatesNotIncludingIntervalExtremes method located at?

**Comment by fsi206914** [comment]
Hi @jmrozanec @tcn , I noticed that the code goes wrong on every weekday on some month, like 3-31, 5-31, 7-31. Other cases looks good. May I know how generateCandidatesNotIncludingIntervalExtremes works.

**Comment by jmrozanec** [comment]
Hi @fsi206914 ! The method should generate valid candidates in a given interval and return them, except for the extremes provided if those would be valid candidates also. The extremes are later verified in another place and added if necessary.

**Comment by jmrozanec** [comment]
@fsi206914  let me know, if I can provide any further help on this! Thanks for looking into the issue!

**Comment by thachhoang** [comment]
I think the problem is in `OnDayOfWeekValueGenerator`. L and hash values are unique in a month, so they're not affected. None values have multiple valid options.

The method `generateNoneValues`, according to the javadoc, accepts either -1 or a value it previously returned. In practice it gets passed any day of the month. The test case @tcn provided would pass if in:


https://github.com/jmrozanec/cron-utils/blob/f8833af8968e32b448910b017031927e80432292/src/main/java/com/cronutils/model/time/generator/OnDayOfWeekValueGenerator.java#L163

we replace this section:
```
if (baseDay > reference) {
	return baseDay;
}
return reference + 7;
```
with:
```
if (reference < 1) {
	return baseDay;
}
while (baseDay <= reference) {
    baseDay += 7;
}
return baseDay;
```

**Comment by jmrozanec** [comment]
@thachhoang thank you for the fix! That solves the issue, and also provides a solution to issue #54 
@tcn @fsi206914 @lpbak issue solved!

**Comment by jmrozanec** [comment]
@tcn @fsi206914 @lpbak @thachhoang  [Version 4.1.1](https://github.com/jmrozanec/cron-utils/releases/tag/4.1.1) was released with this fixes!
