### ISSUE TITLE
French Bundle missing keys

### ISSUE THREAD

**Issue by pkgoddard** [jmrozanec/cron-utils#94]
Missing Keys
days=jours (missing)
months=les mois (missing)
years=les années (missing)
last_weekday_of_month=dernière semaine du mois (missing)

**Comment by jmrozanec** [comment]
@pkgoddard Thank you for pointing out this issue. If you don't mind, a pull request will be most welcome. Otherwise, I will add it soon. Thanks!

**Comment by jmrozanec** [comment]
@pkgoddard Just added the missing keys. Thank you for reporting the issue! Will inform you about the next release, so that you can leverage the fix.
