### ISSUE TITLE
How to build 0 0/6 * * * UNIX type cron expression using CronBuilder ?

### ISSUE THREAD

**Issue by rohit5ram** [jmrozanec/cron-utils#98]
Thank you for this beautiful library. I need help on a little issue.

I get frequency in seconds. I need to build a cron expression from them. Below is my code. It generates the expression as 0 6 0 0 0 for input frequency 21600. But I require it as 0 0/6 0 0 0. Please help me.

int hours = (int) (seconds / 3600);
int minutes = (int) ((seconds % 3600) / 60);
FieldExpression hoursExp = FieldExpressionFactory.on(hours);
FieldExpression minutesExp = FieldExpressionFactory.on(minutes);
Cron cron = CronBuilder.cron(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX))
                .withHour(hoursExp)
                .withMinute(minutesExp)
                .withDoM(always())
                .withMonth(always())
                .withDoW(always())
                .instance();

**Comment by jmrozanec** [comment]
@rohit5ram If you need to execute something every 21600 seconds (6hs), then the cron expression would be 0 */6 * * *
Please let me know if I you have any doubts!

**Comment by rohit5ram** [comment]
Hi @jmrozanec Thank you for the reply. Well my doubt is that how can i generate a cron expression 0 */6 * * * using your CronBuilder. I am unable to figure out which FieldExpression to use. The code that i copied above generates something like 0 6 * * *. How can i make it generate 0 */6 * * * ?

**Comment by jmrozanec** [comment]
@rohit5ram I would use the following code:

    Cron cron = CronBuilder.cron(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX))
    .withMinute(on(0))
    .withHour(every(6))
    .withDoM(always())
    .withMonth(always())
    .withDoW(always())
    .instance();

**Comment by rohit5ram** [comment]
@jmrozanec Thank you. My final code is below.

public static String buildCronFromSeconds(long seconds, CronType cronType) {
        int hours = (int) (seconds / 3600);
        int minutes = (int) ((seconds % 3600) / 60);
        FieldExpression hoursExp = on(hours);
        FieldExpression minutesExp = on(minutes);
        if (hours > 0) hoursExp = every(hours);
        if (minutes > 0) minutesExp = every(minutes);

        Cron cron = CronBuilder.cron(CronDefinitionBuilder.instanceDefinitionFor(cronType))
                .withHour(hoursExp)
                .withMinute(minutesExp)
                .withDoM(always())
                .withMonth(always())
                .withDoW(always())
                .instance();
        CronMapper cronMapper;
        switch (cronType) {
            case QUARTZ:
                cronMapper = CronMapper.fromUnixToQuartz();
                cron = cronMapper.map(cron);
                break;
            case CRON4J:
                cronMapper = CronMapper.fromUnixToQuartz();
                cron = cronMapper.map(cron);
                cronMapper = CronMapper.fromQuartzToCron4j();
                cron = cronMapper.map(cron);
                break;
        }
        return cron.asString();
    }

**Comment by jmrozanec** [comment]
@rohit5ram thank you for sharing the solution!
